import Sqpack.BentzFam
import Sqpack.Bentz4Data

/-!
# `s(k² − 4) = k` for every `k ≥ 8`, from one finite hypothesis (`Valid9`)

The `k² − 4` family of `search/QUADRANT_EXACT.md` (`qx2_k4x_k008`: `R = w = 3`, pitch `1/5`, `σ =
0`, `D = 214770225571/200000000000 ≈ 1.07385 > 1`, Lebesgue from `a = 14/5`) as an instance of the
generic reduction `BentzFam.lean`:

* `Valid9` — **the hypothesis**, stated on the box file `search/qx2_data/K4_k008_box9.txt` verbatim
  (`box9Cover`, from `Bentz4Data.boxSegs`/`boxPolyVerts`/`boxPolyW`, generated by
  `lean/scripts/gen_bentzfam_data.py`): every closed unit square in `[0,9]²` has mass `≥ 1`.
* `fam4` — the family (`K4_k008_family.txt` as two code tables); `famCover fam4 k` is `μ_k` for
  every `k`.
* `box9Cover_measure` — `famCover fam4 9` *is* the box file (kernel evaluation of the list checks).
* `famCover_total4` — the total mass of `μ_k` is `k² − 4D` for every `k ≥ 7`.
* **`bentz4_of_valid9`** — `Valid9 → ∀ k ≥ 8, minSide (k² − 4) = k`.

`notes/lean-k2m4-reduction.md`.
-/

open MeasureTheory Finset
open scoped ENNReal

namespace SquarePacking
namespace Bentz4

open BentzFam

/-! ## 1.  The hypothesis: the box cover `K4_k008_box9.txt` -/

/-- **The box cover `search/qx2_data/K4_k008_box9.txt`** (FORMAT.md v1: container `[0,9]²`,
coordinates `X/5`, masses `w/(2·10¹²)`), verbatim: no points; the 2076 segments of `boxSegs`
(`(X0/5, Y0/5)`–`(X1/5, Y1/5)`, mass `w/(2·10¹²)` spread uniformly by length), indexed by their
position in the file; the one polygon `boxPolyVerts` (the intersection of the left half-planes of
its directed edges) with mass `boxPolyW/(2·10¹²)` spread uniformly by area. -/
noncomputable def box9Cover : MixedCover Empty (Fin boxSegs.length) Unit :=
  fileCover 2000000000000 boxSegs boxPolyVerts boxPolyW

/-- **`Valid9`**: every closed unit square inside `[0,9]²` has mass `≥ 1` under the box cover.  This
is what the Python certificate asserts (Lemma Z for `θ = 0` and the box checker `qx2_zm.py`, run
`qxzm_full`, for `θ > 0`, over the D4 domain; VERIFIED-D4, 0 uncertified). -/
def Valid9 : Prop :=
  ∀ (c : ℝ × ℝ) (θ : ℝ), sq c θ 1 ⊆ box 9 → 1 ≤ box9Cover.measure (sq c θ 1)

/-! ## 2.  The family -/

/-- The family `K4_k008_family.txt`: `R = 3`, Lebesgue from `14/5`, masses in units `1/(2·10¹²)`. -/
def fam4 : Fam where
  R := 3
  A := 14
  den := 2000000000000
  tab := famTab
  tab2 := famTab2

theorem fam4_out : OutZero fam4 := by decide +kernel

/-! ## 3.  `famCover fam4 9` is the box file (kernel evaluation) -/

theorem boxSegs_ok : boxSegs.all (segOK fam4 9) = true := by decide +kernel

theorem boxKeys_eq : boxSegs.map (fun e => keyN (fileIx fam4 9 e)) = boxKeys := by decide +kernel

theorem gridKeys_eq : gridKeys fam4 9 = boxGridKeys := by decide +kernel

theorem boxKeys_sort : msort 32 boxKeys = boxGridKeys := by decide +kernel

theorem boxGridKeys_strict : strictB boxGridKeys = true := by decide +kernel

lemma boxPolyVerts_eq :
    boxPolyVerts = [(14, 14), (5 * 9 - 14, 14), (5 * 9 - 14, 5 * 9 - 14), (14, 5 * 9 - 14)] := rfl

/-- **The box file's measure is `μ₉` of the family.** -/
theorem box9Cover_measure : box9Cover.measure = (famCover fam4 9).measure :=
  fileCover_measure fam4 fam4_out 9 boxSegs boxPolyVerts boxPolyW boxSegs_ok (by norm_num) boxKeys
    boxKeys_eq (boxKeys_sort.trans gridKeys_eq.symm) (gridKeys_eq ▸ boxGridKeys_strict)
    (by rw [boxPolyVerts_eq]; exact convPoly_sq 14 9 (by norm_num))
    (by simp only [boxPolyW, fam4]; norm_num)

/-! ## 4.  Accounting -/

theorem hpoly_false (m : ℕ) : Hpoly fam4 false m = 42732189097180 + m * 11200000000000 := by
  have h00 : H00 3 (tabW famTab) = 42732189097180 := by decide +kernel
  have h01 : H01 3 (tabW famTab) = 7630891120660 := by decide +kernel
  have h10 : H10 3 (tabW famTab) = 3569108879340 := by decide +kernel
  have h11 : H11 3 (tabW famTab) = 0 := by decide +kernel
  simp only [Hpoly, fam4, Fam.layer, Bool.false_eq_true, if_false, h00, h01, h10, h11]
  ring

theorem hpoly_true (m : ℕ) : Hpoly fam4 true m = 12406391400 := by
  have h00 : H00 3 (tabW famTab2) = 12406391400 := by decide +kernel
  have h01 : H01 3 (tabW famTab2) = 0 := by decide +kernel
  have h10 : H10 3 (tabW famTab2) = 0 := by decide +kernel
  have h11 : H11 3 (tabW famTab2) = 0 := by decide +kernel
  simp only [Hpoly, fam4, Fam.layer, if_true, h00, h01, h10, h11]
  ring

/-- **Accounting**: `μ_k([0,k]²) ≤ total = k² − 4D`, `D = 214770225571/200000000000`, for every `k ≥
7`. -/
theorem famCover_total4 (m : ℕ) :
    (famCover fam4 (m + 7)).total
      = (((m + 7 : ℕ) : ℝ)) ^ 2 - 4 * (214770225571 / 200000000000) := by
  have h := famCover_total fam4 m
  rw [show m + 2 * fam4.R + 1 = m + 7 from rfl, hpoly_false, hpoly_true] at h
  rw [h]
  simp only [fam4]
  push_cast
  ring

/-! ## 5.  The end theorem -/

/-- **`s(k² − 4) = k` for all `k ≥ 8`, from `Valid9`.** -/
theorem bentz4_of_valid9 (h : Valid9) : ∀ k : ℕ, 8 ≤ k → minSide (k ^ 2 - 4) = k := by
  intro k hk
  have hval : ∀ (c : ℝ × ℝ) (θ : ℝ), sq c θ 1 ⊆ box ((2 * fam4.R + 3 : ℕ) : ℝ) →
      1 ≤ (famCover fam4 (2 * fam4.R + 3)).measure (sq c θ 1) := fun c θ hS => by
    rw [show 2 * fam4.R + 3 = 9 from rfl] at hS ⊢
    have h9 := h c θ (by rwa [Nat.cast_ofNat] at hS)
    rwa [box9Cover_measure] at h9
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 7 := ⟨k - 7, by omega⟩
  have h4 : 4 < (m + 7) ^ 2 := by nlinarith
  refine minSide_eq fam4 fam4_out (by decide) hval (by simp only [fam4]; omega) (by omega) ?_
    (by rw [pow_two]; exact Nat.sub_le _ _)
  rw [famCover_total4, Nat.cast_sub h4.le]
  push_cast
  norm_num

end Bentz4
end SquarePacking
