import Sqpack.MixedMeasure
import Sqpack.BentzData

/-!
# `s(k² − 3) = k` for every `k ≥ 6`, from one finite hypothesis (`Valid7`)

`search/QUADRANT_EXACT.md` builds a fixed-profile family (`R = w = 2`, pitch `1/5`, `σ = 0`,
`D = 423621306389/500000000000 > 3/4`) and certifies in Python (Lemma Z + `qx2_zm.py` run V3, `certificates/k2m3/`) that
its box measure `μ₇` on `[0,7]²` — the cover file `search/qx2_data/L4_k02_box7.txt` — gives every
closed unit square in `[0,7]²` mass `≥ 1`.  This file proves, in Lean, everything else:

* `Valid7` — **the hypothesis**, stated on the box file verbatim (`box7Cover`, from
  `BentzData.boxSegs`/`boxPolyVerts`/`boxPolyW`, generated by `lean/scripts/gen_bentz_data.py`).
* `famCover k` — the family measure `μ_k` on `[0,k]²` for every `k`: unit segments of the
  `1/5`-grid whose masses depend only on (offset from the nearer wall | phase in the band zone) of
  the segment's cell and line, from the family table `famTab`; plus Lebesgue on `[9/5, k − 9/5]²`.
* `box7Cover_measure` — `famCover 7` *is* the box file (kernel evaluation: every file segment is a
  unit grid segment with the family's mass, no two coincide, and every segment of `μ₇` with
  non-zero mass is in the file; the polygon is `[9/5, 26/5]²` with mass = area).
* `famCover_total` — accounting: the total mass of `μ_k` is `k² − 4D` for every `k ≥ 4`.
* `mass_shift` — localisation: for `k ≥ 6` every closed unit square in `[0,k]²` has the same
  `μ_k`-mass as some integer translate of it in `[0,7]²` has under `μ₇` (one integer shift per
  axis: keep, move the far wall `k` to `7`, or move a range inside the open band zone into `(2,5)`;
  `Good`).
* **`bentz_of_valid7`** — `Valid7 → ∀ k ≥ 6, minSide (k² − 3) = k` (with `not_packs_of_measure`
  for the lower bound and `packs_grid` for the upper bound).

Opt-in (not imported by `Sqpack.lean`): `lake build Sqpack.Bentz`.  `notes/lean-bentz-reduction.md`.
-/

open MeasureTheory Finset
open scoped ENNReal

namespace SquarePacking
namespace Bentz

/-! ## 1.  The hypothesis: the box cover `L4_k02_box7.txt` -/

/-- The convex polygon with vertex list `vs` (coordinates `X/D`, counter-clockwise): the points on
the left of, or on, every directed edge `vᵢ → vᵢ₊₁` (indices mod the length). -/
def convPoly (D : ℕ) (vs : List (ℕ × ℕ)) : Set (ℝ × ℝ) :=
  {p | ∀ e ∈ vs.zip (vs.rotate 1),
    0 ≤ ((e.2.1 : ℝ) / D - (e.1.1 : ℝ) / D) * (p.2 - (e.1.2 : ℝ) / D)
      - ((e.2.2 : ℝ) / D - (e.1.2 : ℝ) / D) * (p.1 - (e.1.1 : ℝ) / D)}

/-- **The box cover `search/qx2_data/L4_k02_box7.txt`** (FORMAT.md v1: container `[0,7]²`,
coordinates `X/5`, masses `w/10¹²`), verbatim: no points; the 800 segments of `boxSegs`
(`(X0/5, Y0/5)`–`(X1/5, Y1/5)`, mass `w/10¹²` spread uniformly by length), indexed by their line
number; the one polygon `boxPolyVerts` with mass `boxPolyW/10¹²` spread uniformly by area. -/
noncomputable def box7Cover : MixedCover Empty (Fin boxSegs.length) Unit where
  pts := ∅
  pt := fun e => e.elim
  pw := fun e => e.elim
  segs := univ
  sa := fun j => (((boxSegs.get j).1 : ℝ) / 5, ((boxSegs.get j).2.1 : ℝ) / 5)
  sb := fun j => (((boxSegs.get j).2.2.1 : ℝ) / 5, ((boxSegs.get j).2.2.2.1 : ℝ) / 5)
  sw := fun j => ((boxSegs.get j).2.2.2.2 : ℝ) / 1000000000000
  polys := univ
  poly := fun _ => convPoly 5 boxPolyVerts
  gw := fun _ => (boxPolyW : ℝ) / 1000000000000

/-- **`Valid7`**: every closed unit square inside `[0,7]²` has mass `≥ 1` under the measure `μ₇` of
the box cover.  This is what the Python certificate asserts (`search/QUADRANT_EXACT.md` §3, §6:
Lemma Z for `θ = 0` and the box checker run V3 of `qx2_zm.py` for `θ > 0`, over the D4 domain). -/
def Valid7 : Prop :=
  ∀ (c : ℝ × ℝ) (θ : ℝ), sq c θ 1 ⊆ box 7 → 1 ≤ box7Cover.measure (sq c θ 1)

/-! ## 2.  The family measures `μ_k`

Unit segments of the `1/5`-grid are indexed by `(o, i, j) : Bool × ℤ × ℤ`: `o = false` is the
horizontal segment `(i/5, j/5)`–`((i+1)/5, j/5)`, `o = true` the vertical one
`(i/5, j/5)`–`(i/5, (j+1)/5)`.  In `[0,k]²` a *cell* `[i/5, (i+1)/5]` and a *line* `j/5` of one
coordinate get a code: its offset `0..9` from the nearer wall when it lies within `2 = R` of it
(`cellT`, `lineT`), or `10 + phase` in the band zone `[2, k − 2]` (the band's closed ends `2` and
`k − 2` are band lines of phase 0), or `15` outside `[0,k]`.  The mass of a horizontal segment is
`famTab[16·(code of its x-cell) + (code of its y-line)]`, of a vertical one the diagonal image.
This *is* the family: corner module at the four corners (offsets from both walls), the profile on
`[R, k − R]` along the four walls (phase along the wall, offset from it), nothing else except the
Lebesgue square `[9/5, k − 9/5]²`.  (`famCover 7` is the box file: `box7Cover_measure`.) -/

/-- The code of the cell `[i/5, (i+1)/5]` in `[0,k]`. -/
def cellT (k : ℕ) (i : ℤ) : ℤ :=
  if i < 0 ∨ 5 * (k : ℤ) ≤ i then 15
  else if i < 10 then i
  else if 5 * (k : ℤ) - 10 ≤ i then 5 * (k : ℤ) - 1 - i
  else 10 + i % 5

/-- The code of the line `j/5` in `[0,k]`. -/
def lineT (k : ℕ) (j : ℤ) : ℤ :=
  if j < 0 ∨ 5 * (k : ℤ) < j then 15
  else if j < 10 then j
  else if 5 * (k : ℤ) - 10 < j then 5 * (k : ℤ) - j
  else 10 + j % 5

/-- The table entry. -/
def tabW (c l : ℤ) : ℕ := famTab.getD (16 * c.toNat + l.toNat) 0

/-- Segment indices. -/
abbrev SegIx := Bool × ℤ × ℤ

/-- The mass of a unit segment in `μ_k`, in units of `10⁻¹²`. -/
def wN (k : ℕ) (s : SegIx) : ℕ :=
  if s.1 then tabW (cellT k s.2.2) (lineT k s.2.1) else tabW (cellT k s.2.1) (lineT k s.2.2)

/-- The endpoints of a unit segment. -/
noncomputable def segA (s : SegIx) : ℝ × ℝ := ((s.2.1 : ℝ) / 5, (s.2.2 : ℝ) / 5)
noncomputable def segB (s : SegIx) : ℝ × ℝ :=
  if s.1 then ((s.2.1 : ℝ) / 5, ((s.2.2 : ℝ) + 1) / 5) else (((s.2.1 : ℝ) + 1) / 5, (s.2.2 : ℝ) / 5)

/-- `{0, …, 5k} ⊆ ℤ`. -/
def idx (k : ℕ) : Finset ℤ := (range (5 * k + 1)).map ⟨Nat.cast, Nat.cast_injective⟩

/-- The segment indices of `[0,k]²` (all of them; the masses vanish off the support). -/
def grid (k : ℕ) : Finset SegIx := univ ×ˢ (idx k ×ˢ idx k)

/-- The Lebesgue square `[9/5, k − 9/5]²`. -/
def lebSq (k : ℕ) : Set (ℝ × ℝ) :=
  Set.Icc (9 / 5 : ℝ) ((k : ℝ) - 9 / 5) ×ˢ Set.Icc (9 / 5 : ℝ) ((k : ℝ) - 9 / 5)

/-- **The family measure `μ_k` on `[0,k]²`**, as a mixed cover. -/
noncomputable def famCover (k : ℕ) : MixedCover Empty SegIx Unit where
  pts := ∅
  pt := fun e => e.elim
  pw := fun e => e.elim
  segs := grid k
  sa := segA
  sb := segB
  sw := fun s => (wN k s : ℝ) / 1000000000000
  polys := univ
  poly := fun _ => lebSq k
  gw := fun _ => ((k : ℝ) - 18 / 5) ^ 2

/-! ## 3.  `famCover 7` is the box file (kernel evaluation) -/

/-- The grid index of a file segment. -/
def fileIx (e : ℕ × ℕ × ℕ × ℕ × ℕ) : SegIx :=
  if e.2.1 = e.2.2.2.1 then (false, ((min e.1 e.2.2.1 : ℕ) : ℤ), (e.2.1 : ℤ))
  else (true, (e.1 : ℤ), ((min e.2.1 e.2.2.2.1 : ℕ) : ℤ))

/-- A file segment is a unit segment of the `1/5`-grid (either orientation), with positive mass
equal to the family's. -/
def segOK (e : ℕ × ℕ × ℕ × ℕ × ℕ) : Bool :=
  ((e.2.1 == e.2.2.2.1 && (e.2.2.1 == e.1 + 1 || e.1 == e.2.2.1 + 1)) ||
    (e.1 == e.2.2.1 && (e.2.2.2.1 == e.2.1 + 1 || e.2.1 == e.2.2.2.1 + 1))) &&
  (0 < e.2.2.2.2 && wN 7 (fileIx e) == e.2.2.2.2)

theorem boxSegs_ok : boxSegs.all segOK = true := by decide +kernel

theorem boxSegs_nodup : (boxSegs.map fileIx).Nodup := by decide +kernel

theorem boxSegs_complete :
    ([false, true].all fun o => (List.range 36).all fun i => (List.range 36).all fun j =>
      wN 7 (o, (i : ℤ), (j : ℤ)) == 0 || (boxSegs.map fileIx).contains (o, (i : ℤ), (j : ℤ)))
      = true := by
  decide +kernel

/-! ## 4.  Codes, and the support of `μ_k` -/

lemma cellT_range (k : ℕ) (i : ℤ) : 0 ≤ cellT k i ∧ cellT k i ≤ 15 := by
  unfold cellT; split_ifs <;> omega

lemma lineT_range (k : ℕ) (j : ℤ) : 0 ≤ lineT k j ∧ lineT k j ≤ 15 := by
  unfold lineT; split_ifs <;> omega

lemma tabW_out_left (l : ℤ) (hl : 0 ≤ l ∧ l ≤ 15) : tabW 15 l = 0 := by
  have h : ∀ n < 16, famTab.getD (16 * 15 + n) 0 = 0 := by decide
  exact h l.toNat (by omega)

lemma tabW_out_right (c : ℤ) (hc : 0 ≤ c ∧ c ≤ 15) : tabW c 15 = 0 := by
  have h : ∀ n < 16, famTab.getD (16 * n + 15) 0 = 0 := by decide
  exact h c.toNat (by omega)

lemma mem_idx {k : ℕ} {x : ℤ} : x ∈ idx k ↔ 0 ≤ x ∧ x ≤ 5 * (k : ℤ) := by
  simp only [idx, mem_map, mem_range, Function.Embedding.coeFn_mk]
  constructor
  · rintro ⟨n, hn, rfl⟩; omega
  · rintro ⟨h0, h1⟩; exact ⟨x.toNat, by omega, by omega⟩

lemma mem_grid {k : ℕ} {s : SegIx} :
    s ∈ grid k ↔ (0 ≤ s.2.1 ∧ s.2.1 ≤ 5 * (k : ℤ)) ∧ (0 ≤ s.2.2 ∧ s.2.2 ≤ 5 * (k : ℤ)) := by
  simp only [grid, mem_product, mem_univ, true_and, mem_idx]

lemma cellT_out {k : ℕ} {i : ℤ} (h : ¬ (0 ≤ i ∧ i ≤ 5 * (k : ℤ))) : cellT k i = 15 := by
  unfold cellT; split_ifs <;> omega

lemma lineT_out {k : ℕ} {j : ℤ} (h : ¬ (0 ≤ j ∧ j ≤ 5 * (k : ℤ))) : lineT k j = 15 := by
  unfold lineT; split_ifs <;> omega

/-- The masses vanish off the grid. -/
lemma wN_eq_zero {k : ℕ} {s : SegIx} (hs : s ∉ grid k) : wN k s = 0 := by
  rw [mem_grid, not_and_or] at hs
  obtain ⟨o, i, j⟩ := s
  cases o <;> simp only [wN, Bool.false_eq_true, if_false, if_true] <;> rcases hs with h | h
  · rw [cellT_out h]; exact tabW_out_left _ (lineT_range k j)
  · rw [lineT_out h]; exact tabW_out_right _ (cellT_range k i)
  · rw [lineT_out h]; exact tabW_out_right _ (cellT_range k j)
  · rw [cellT_out h]; exact tabW_out_left _ (lineT_range k i)

lemma mem_grid_of_wN {k : ℕ} {s : SegIx} (h : wN k s ≠ 0) : s ∈ grid k := by
  by_contra hs; exact h (wN_eq_zero hs)

/-! ## 5.  `famCover 7` is the box file -/

/-- A checked file segment is the unit segment `fileIx e`, with the family's mass. -/
lemma seg_of_ok (e : ℕ × ℕ × ℕ × ℕ × ℕ) (h : segOK e = true) :
    segMeasure ((e.1 : ℝ) / 5, (e.2.1 : ℝ) / 5) ((e.2.2.1 : ℝ) / 5, (e.2.2.2.1 : ℝ) / 5)
        = segMeasure (segA (fileIx e)) (segB (fileIx e)) ∧
      0 < e.2.2.2.2 ∧ wN 7 (fileIx e) = e.2.2.2.2 := by
  obtain ⟨a, b, c, d, w⟩ := e
  simp only [segOK, Bool.and_eq_true, Bool.or_eq_true, beq_iff_eq, decide_eq_true_eq] at h
  obtain ⟨hgeo, hw0, hw⟩ := h
  refine ⟨?_, hw0, hw⟩
  rcases hgeo with ⟨rfl, rfl | rfl⟩ | ⟨rfl, rfl | rfl⟩
  · simp [fileIx, segA, segB]
  · rw [segMeasure_comm]; simp [fileIx, segA, segB]
  · simp [fileIx, segA, segB]
  · rw [segMeasure_comm]; simp [fileIx, segA, segB]


lemma convPoly_box : convPoly 5 boxPolyVerts = lebSq 7 := by
  have hz : boxPolyVerts.zip (boxPolyVerts.rotate 1) =
      [((9, 9), (26, 9)), ((26, 9), (26, 26)), ((26, 26), (9, 26)), ((9, 26), (9, 9))] := by
    decide
  ext p
  simp only [convPoly, hz, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
    implies_true, and_true, Set.mem_ofPred_eq, lebSq, Set.mem_prod, Set.mem_Icc]
  norm_num
  constructor
  · rintro ⟨h1, h2, h3, h4⟩; refine ⟨⟨?_, ?_⟩, ?_, ?_⟩ <;> nlinarith
  · rintro ⟨⟨h1, h2⟩, h3, h4⟩; refine ⟨?_, ?_, ?_, ?_⟩ <;> nlinarith

/-- The file segment with index `j`. -/
lemma boxSeg_ok (j : Fin boxSegs.length) : segOK (boxSegs.get j) = true :=
  List.all_eq_true.mp boxSegs_ok _ (List.get_mem _ _)

lemma fileIx_inj {j₁ j₂ : Fin boxSegs.length}
    (h : fileIx (boxSegs.get j₁) = fileIx (boxSegs.get j₂)) : j₁ = j₂ := by
  have h' : (boxSegs.map fileIx)[j₁.1]'(by simp) = (boxSegs.map fileIx)[j₂.1]'(by simp) := by
    simpa using h
  exact Fin.ext ((List.Nodup.getElem_inj_iff boxSegs_nodup).mp h')

lemma boxSegs_complete' (s : SegIx) (hs : s ∈ grid 7) :
    wN 7 s = 0 ∨ ∃ j : Fin boxSegs.length, fileIx (boxSegs.get j) = s := by
  obtain ⟨o, i, j⟩ := s
  rw [mem_grid] at hs
  simp only at hs
  have h := boxSegs_complete
  simp only [List.all_eq_true, List.mem_cons, List.mem_range, Bool.or_eq_true, beq_iff_eq,
    List.contains_iff_mem] at h
  have hi : ((i.toNat : ℕ) : ℤ) = i := by omega
  have hj : ((j.toNat : ℕ) : ℤ) = j := by omega
  have := h o (by cases o <;> simp) i.toNat (by omega) j.toNat (by omega)
  rw [hi, hj] at this
  rcases this with h0 | hm
  · exact Or.inl h0
  · right
    obtain ⟨e, he, hfe⟩ := List.mem_map.mp hm
    obtain ⟨j', hj'⟩ := List.mem_iff_get.mp he
    exact ⟨j', by rw [hj', hfe]⟩

/-- **The box file's measure is `μ₇` of the family.** -/
theorem box7Cover_measure : box7Cover.measure = (famCover 7).measure := by
  unfold MixedCover.measure
  refine congrArg₂ (· + ·) (congrArg₂ (· + ·) ?_ ?_) ?_
  · rw [show box7Cover.pts = ∅ from rfl, show (famCover 7).pts = ∅ from rfl, sum_empty, sum_empty]
  · -- the segments
    set F : SegIx → Measure (ℝ × ℝ) := fun s =>
      ENNReal.ofReal ((wN 7 s : ℝ) / 1000000000000) • segMeasure (segA s) (segB s) with hF
    set φ : Fin boxSegs.length → SegIx := fun j => fileIx (boxSegs.get j) with hφ
    have hterm : ∀ j ∈ (univ : Finset (Fin boxSegs.length)),
        ENNReal.ofReal (box7Cover.sw j) • segMeasure (box7Cover.sa j) (box7Cover.sb j)
          = F (φ j) := by
      intro j _
      obtain ⟨hseg, _, hw⟩ := seg_of_ok _ (boxSeg_ok j)
      simp only [box7Cover, hF, hφ]
      rw [hseg, hw]
    have hL : ∑ j ∈ (univ : Finset (Fin boxSegs.length)),
        ENNReal.ofReal (box7Cover.sw j) • segMeasure (box7Cover.sa j) (box7Cover.sb j)
          = ∑ s ∈ univ.image φ, F s := by
      rw [Finset.sum_congr rfl hterm, Finset.sum_image]
      intro j₁ _ j₂ _ h; exact fileIx_inj h
    change _ = ∑ s ∈ grid 7, F s
    rw [show box7Cover.segs = univ from rfl, hL]
    refine Finset.sum_subset ?_ ?_
    · intro s hs
      obtain ⟨j, _, rfl⟩ := mem_image.mp hs
      obtain ⟨_, hw0, hw⟩ := seg_of_ok _ (boxSeg_ok j)
      exact mem_grid_of_wN (by rw [hw]; omega)
    · intro s hs hns
      rcases boxSegs_complete' s hs with h0 | ⟨j, hj⟩
      · simp [hF, h0]
      · exact absurd (mem_image.mpr ⟨j, mem_univ _, hj⟩) hns
  · -- the polygon
    refine Finset.sum_congr rfl fun u _ => ?_
    simp only [box7Cover, famCover, convPoly_box, boxPolyW]
    norm_num

/-! ## 6.  Localisation: an integer shift per axis -/

/-- An integer shift `n` taking the axis range `[x₀, x₁]` of a square in `[0,k]` into `[0,7]`
without changing what `μ_k` looks like there: keep it (near the wall `0`), move the far wall `k`
to `7`, or move a range inside the open band zone `(2, k − 2)` into `(2, 5)`. -/
def Good (k : ℕ) (n : ℤ) (x₀ x₁ : ℝ) : Prop :=
  (n = 0 ∧ x₁ < 5 ∧ x₁ < (k : ℝ) - 2) ∨ (n = (k : ℤ) - 7 ∧ 2 < x₀ ∧ (k : ℝ) - 5 < x₀) ∨
    (2 < x₀ ∧ x₁ < (k : ℝ) - 2 ∧ 2 < x₀ - n ∧ x₁ - n < 5)

lemma exists_good {k : ℕ} (hk : 6 ≤ k) {x₀ x₁ : ℝ} (hw : x₁ - x₀ < 2) :
    ∃ n : ℤ, Good k n x₀ x₁ := by
  have hk' : (6 : ℝ) ≤ k := by exact_mod_cast hk
  by_cases hA : x₁ < 5 ∧ x₁ < (k : ℝ) - 2
  · exact ⟨0, Or.inl ⟨rfl, hA⟩⟩
  by_cases hB : 2 < x₀ ∧ (k : ℝ) - 5 < x₀
  · exact ⟨(k : ℤ) - 7, Or.inr (Or.inl ⟨rfl, hB⟩)⟩
  refine ⟨⌈x₀⌉ - 3, Or.inr (Or.inr ?_)⟩
  have hc1 := Int.le_ceil x₀
  have hc2 := Int.ceil_lt_add_one x₀
  push_cast
  rw [not_and_or, not_lt, not_lt] at hA
  rw [not_and_or, not_lt, not_lt] at hB
  have h2 : 2 < x₀ ∧ x₁ < (k : ℝ) - 2 := by
    rcases hA with hA | hA <;> rcases hB with hB | hB <;> constructor <;> linarith
  exact ⟨h2.1, h2.2, by linarith, by linarith⟩

lemma good_cell {k : ℕ} {n : ℤ} {x₀ x₁ : ℝ} (hg : Good k n x₀ x₁) (h0 : 0 ≤ x₀)
    (h1 : x₁ ≤ k) {i : ℤ} (hi1 : (i : ℝ) ≤ 5 * x₁) (hi0 : 5 * x₀ ≤ i + 1) :
    cellT k i = cellT 7 (i - 5 * n) := by
  rcases hg with ⟨rfl, ha, hb⟩ | ⟨rfl, ha, hb⟩ | ⟨ha, hb, hc, hd⟩
  · have e1 : i < 25 := by
      have : ((i : ℤ) : ℝ) < ((25 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : i < 5 * (k : ℤ) - 10 := by
      have : ((i : ℤ) : ℝ) < ((5 * (k : ℤ) - 10 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : -1 ≤ i := by
      have : ((-1 : ℤ) : ℝ) ≤ ((i : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold cellT; split_ifs <;> omega
  · have e1 : 9 < i := by
      have : ((9 : ℤ) : ℝ) < ((i : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : 5 * (k : ℤ) - 26 < i := by
      have : ((5 * (k : ℤ) - 26 : ℤ) : ℝ) < ((i : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : i ≤ 5 * (k : ℤ) := by
      have : ((i : ℤ) : ℝ) ≤ ((5 * (k : ℤ) : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold cellT; split_ifs <;> omega
  · have e1 : 9 < i := by
      have : ((9 : ℤ) : ℝ) < ((i : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : i < 5 * (k : ℤ) - 10 := by
      have : ((i : ℤ) : ℝ) < ((5 * (k : ℤ) - 10 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : 9 < i - 5 * n := by
      have : ((9 : ℤ) : ℝ) < ((i - 5 * n : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e4 : i - 5 * n < 25 := by
      have : ((i - 5 * n : ℤ) : ℝ) < ((25 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold cellT; split_ifs <;> omega

lemma good_line {k : ℕ} {n : ℤ} {x₀ x₁ : ℝ} (hg : Good k n x₀ x₁) (h0 : 0 ≤ x₀)
    (h1 : x₁ ≤ k) {j : ℤ} (hj0 : 5 * x₀ ≤ j) (hj1 : (j : ℝ) ≤ 5 * x₁) :
    lineT k j = lineT 7 (j - 5 * n) := by
  rcases hg with ⟨rfl, ha, hb⟩ | ⟨rfl, ha, hb⟩ | ⟨ha, hb, hc, hd⟩
  · have e1 : j < 25 := by
      have : ((j : ℤ) : ℝ) < ((25 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : j < 5 * (k : ℤ) - 10 := by
      have : ((j : ℤ) : ℝ) < ((5 * (k : ℤ) - 10 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : 0 ≤ j := by
      have : ((0 : ℤ) : ℝ) ≤ ((j : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold lineT; split_ifs <;> omega
  · have e1 : 10 < j := by
      have : ((10 : ℤ) : ℝ) < ((j : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : 5 * (k : ℤ) - 25 < j := by
      have : ((5 * (k : ℤ) - 25 : ℤ) : ℝ) < ((j : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : j ≤ 5 * (k : ℤ) := by
      have : ((j : ℤ) : ℝ) ≤ ((5 * (k : ℤ) : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold lineT; split_ifs <;> omega
  · have e1 : 10 < j := by
      have : ((10 : ℤ) : ℝ) < ((j : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e2 : j < 5 * (k : ℤ) - 10 := by
      have : ((j : ℤ) : ℝ) < ((5 * (k : ℤ) - 10 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e3 : 10 < j - 5 * n := by
      have : ((10 : ℤ) : ℝ) < ((j - 5 * n : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    have e4 : j - 5 * n < 25 := by
      have : ((j - 5 * n : ℤ) : ℝ) < ((25 : ℤ) : ℝ) := by push_cast; linarith
      exact_mod_cast this
    unfold lineT; split_ifs <;> omega

lemma good_leb {k : ℕ} {n : ℤ} {x₀ x₁ : ℝ} (hg : Good k n x₀ x₁) {x : ℝ} (hx0 : x₀ ≤ x)
    (hx1 : x ≤ x₁) :
    (9 / 5 ≤ x ∧ x ≤ (k : ℝ) - 9 / 5) ↔ (9 / 5 ≤ x - n ∧ x - n ≤ ((7 : ℕ) : ℝ) - 9 / 5) := by
  push_cast
  rcases hg with ⟨rfl, ha, hb⟩ | ⟨rfl, ha, hb⟩ | ⟨ha, hb, hc, hd⟩ <;> push_cast <;>
    constructor <;> rintro ⟨h1, h2⟩ <;> constructor <;> linarith

lemma good_box {k : ℕ} {n : ℤ} {x₀ x₁ : ℝ} (hg : Good k n x₀ x₁) (h0 : 0 ≤ x₀)
    (h1 : x₁ ≤ k) :
    0 ≤ x₀ - n ∧ x₁ - n ≤ 7 := by
  rcases hg with ⟨rfl, ha, hb⟩ | ⟨rfl, ha, hb⟩ | ⟨ha, hb, hc, hd⟩ <;> push_cast <;>
    constructor <;> linarith

lemma wid_lt_two (θ : ℝ) : wid θ < 2 := by
  have h := Real.cos_sq_add_sin_sq θ
  rw [← sq_abs (Real.cos θ), ← sq_abs (Real.sin θ)] at h
  have h1 := abs_nonneg (Real.cos θ)
  have h2 := abs_nonneg (Real.sin θ)
  unfold wid
  nlinarith [sq_nonneg (|Real.cos θ| - |Real.sin θ|)]

/-! ## 7.  Translation -/

lemma mem_sq_sub (c v p : ℝ × ℝ) (θ : ℝ) : p ∈ sq (c - v) θ 1 ↔ p + v ∈ sq c θ 1 := by
  have : coord (c - v) θ p = coord c θ (p + v) := by
    simp only [coord, Prod.fst_sub, Prod.snd_sub, Prod.fst_add, Prod.snd_add]
    ext <;> ring_nf
  simp only [sq, Set.mem_ofPred_eq, this]

/-- The index shift by `(-5 nx, -5 ny)`. -/
def shiftIx (nx ny : ℤ) (s : SegIx) : SegIx := (s.1, s.2.1 - 5 * nx, s.2.2 - 5 * ny)

lemma segPt_shift (nx ny : ℤ) (s : SegIx) (t : ℝ) :
    segPt (segA (shiftIx nx ny s)) (segB (shiftIx nx ny s)) t + ((nx : ℝ), (ny : ℝ))
      = segPt (segA s) (segB s) t := by
  obtain ⟨o, i, j⟩ := s
  cases o <;> simp only [shiftIx, segA, segB, segPt, Bool.false_eq_true, if_false, if_true,
    Prod.mk_add_mk] <;> push_cast <;> ext <;> ring

lemma segFrac_shift (nx ny : ℤ) (s : SegIx) (c : ℝ × ℝ) (θ : ℝ) :
    segFrac (segA (shiftIx nx ny s)) (segB (shiftIx nx ny s))
        (sq (c - ((nx : ℝ), (ny : ℝ))) θ 1) = segFrac (segA s) (segB s) (sq c θ 1) := by
  unfold segFrac
  congr 3
  ext t
  simp only [Set.mem_preimage, mem_sq_sub, segPt_shift]

/-- A segment with a positive fraction in `S` meets `S`. -/
lemma exists_of_segFrac_ne {a b : ℝ × ℝ} {S : Set (ℝ × ℝ)} (h : segFrac a b S ≠ 0) :
    ∃ t ∈ Set.Icc (0 : ℝ) 1, segPt a b t ∈ S := by
  by_contra hn
  simp only [not_exists, not_and] at hn
  apply h
  have : segPt a b ⁻¹' S ∩ Set.Icc (0 : ℝ) 1 = ∅ := by
    ext t; simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_empty_iff_false, iff_false]
    exact fun ⟨h1, h2⟩ => hn t h2 h1
  simp [segFrac, this]

/-- The segment part of the mass. -/
noncomputable def segTerm (k : ℕ) (S : Set (ℝ × ℝ)) (s : SegIx) : ℝ :=
  (wN k s : ℝ) / 1000000000000 * segFrac (segA s) (segB s) S

/-- Re-indexing the segment sums by a shift that matches the terms. -/
lemma sum_segTerm_shift {k : ℕ} (S S' : Set (ℝ × ℝ)) (nx ny : ℤ)
    (hterm : ∀ s, segTerm k S s = segTerm 7 S' (shiftIx nx ny s)) :
    ∑ s ∈ grid k, segTerm k S s = ∑ s ∈ grid 7, segTerm 7 S' s := by
  set τ := shiftIx nx ny with hτ
  set τ' := shiftIx (-nx) (-ny) with hτ'
  have h1 : ∀ s, τ' (τ s) = s := fun s => by
    obtain ⟨o, i, j⟩ := s; simp only [hτ, hτ', shiftIx]; ext <;> simp
  have h2 : ∀ s, τ (τ' s) = s := fun s => by
    obtain ⟨o, i, j⟩ := s; simp only [hτ, hτ', shiftIx]; ext <;> simp
  have hinj : Set.InjOn τ (grid k : Set SegIx) := fun a _ b _ h => by
    rw [← h1 a, h, h1 b]
  rw [Finset.sum_congr rfl fun s _ => hterm s, ← Finset.sum_image hinj]
  have hz7 : ∀ s, s ∉ grid 7 → segTerm 7 S' s = 0 := fun s hs => by
    simp [segTerm, wN_eq_zero hs]
  have hzk : ∀ s ∈ grid 7, s ∉ (grid k).image τ → segTerm 7 S' s = 0 := fun s _ hs => by
    have hn : τ' s ∉ grid k := fun hm => hs (mem_image.mpr ⟨τ' s, hm, h2 s⟩)
    rw [← h2 s, ← hterm]
    simp [segTerm, wN_eq_zero hn]
  have e1 : ∑ s ∈ (grid k).image τ, segTerm 7 S' s
      = ∑ s ∈ (grid k).image τ ∪ grid 7, segTerm 7 S' s :=
    Finset.sum_subset Finset.subset_union_left
      (fun s hs hns => hzk s ((mem_union.mp hs).resolve_left hns) hns)
  have e2 : ∑ s ∈ grid 7, segTerm 7 S' s
      = ∑ s ∈ (grid k).image τ ∪ grid 7, segTerm 7 S' s :=
    Finset.sum_subset Finset.subset_union_right (fun s _ hns => hz7 s hns)
  rw [e1, e2]

lemma volume_lebSq {k : ℕ} (hk : 4 ≤ k) :
    volume (lebSq k) = ENNReal.ofReal (((k : ℝ) - 18 / 5) ^ 2) := by
  have hk' : (4 : ℝ) ≤ k := by exact_mod_cast hk
  rw [lebSq, Measure.volume_eq_prod, Measure.prod_prod, Real.volume_Icc,
    ← ENNReal.ofReal_mul (by linarith)]
  congr 1; ring

lemma polyTerm {k : ℕ} (hk : 4 ≤ k) (S : Set (ℝ × ℝ)) :
    ((k : ℝ) - 18 / 5) ^ 2 * areaFrac (lebSq k) S = (volume (S ∩ lebSq k)).toReal := by
  have hk' : (4 : ℝ) ≤ k := by exact_mod_cast hk
  have hpos : 0 < ((k : ℝ) - 18 / 5) ^ 2 := by nlinarith
  rw [areaFrac, volume_lebSq hk, ENNReal.toReal_mul, ENNReal.toReal_inv,
    ENNReal.toReal_ofReal hpos.le, ← mul_assoc, mul_inv_cancel₀ hpos.ne', one_mul]

/-- **Localisation.**  For `k ≥ 6`, the mass of any closed unit square in `[0,k]²` under `μ_k` is
the mass under `μ₇` of an integer translate of it that lies in `[0,7]²`. -/
theorem mass_shift {k : ℕ} (hk : 6 ≤ k) (c : ℝ × ℝ) (θ : ℝ) (hS : sq c θ 1 ⊆ box k) :
    ∃ v : ℝ × ℝ, sq (c - v) θ 1 ⊆ box 7 ∧
      (famCover k).mass (sq c θ 1) = (famCover 7).mass (sq (c - v) θ 1) := by
  obtain ⟨ha1, ha2, ha3, ha4⟩ := (sq_subset_box_iff k c θ).mp hS
  have hw := wid_lt_two θ
  obtain ⟨nx, hgx⟩ := exists_good hk (x₀ := c.1 - wid θ / 2) (x₁ := c.1 + wid θ / 2)
    (by linarith)
  obtain ⟨ny, hgy⟩ := exists_good hk (x₀ := c.2 - wid θ / 2) (x₁ := c.2 + wid θ / 2)
    (by linarith)
  have hx0 : 0 ≤ c.1 - wid θ / 2 := by linarith
  have hx1 : c.1 + wid θ / 2 ≤ k := by linarith
  have hy0 : 0 ≤ c.2 - wid θ / 2 := by linarith
  have hy1 : c.2 + wid θ / 2 ≤ k := by linarith
  set v : ℝ × ℝ := ((nx : ℝ), (ny : ℝ)) with hv
  refine ⟨v, ?_, ?_⟩
  · obtain ⟨b1, b2⟩ := good_box hgx hx0 hx1
    obtain ⟨b3, b4⟩ := good_box hgy hy0 hy1
    refine (sq_subset_box_iff 7 (c - v) θ).mpr ⟨?_, ?_, ?_, ?_⟩ <;>
      simp only [hv, Prod.fst_sub, Prod.snd_sub] <;> linarith
  -- the bounding box of the square
  have hbox : ∀ p ∈ sq c θ 1, (c.1 - wid θ / 2 ≤ p.1 ∧ p.1 ≤ c.1 + wid θ / 2) ∧
      (c.2 - wid θ / 2 ≤ p.2 ∧ p.2 ≤ c.2 + wid θ / 2) := fun p hp => by
    obtain ⟨h1, h2⟩ := abs_sub_le_wid hp
    rw [abs_le] at h1 h2
    exact ⟨⟨by linarith, by linarith⟩, by linarith, by linarith⟩
  unfold MixedCover.mass
  refine congrArg₂ (· + ·) (congrArg₂ (· + ·) ?_ ?_) ?_
  · have h : ∀ (T : Finset Empty) (f : Empty → ℝ), ∑ e ∈ T, f e = 0 := fun T f => by
      simp [Finset.eq_empty_of_isEmpty T]
    rw [h, h]
  · -- the segments
    change ∑ s ∈ grid k, segTerm k (sq c θ 1) s = ∑ s ∈ grid 7, segTerm 7 (sq (c - v) θ 1) s
    refine sum_segTerm_shift _ _ nx ny fun s => ?_
    simp only [segTerm]
    rw [segFrac_shift]
    by_cases h0 : segFrac (segA s) (segB s) (sq c θ 1) = 0
    · rw [h0]; simp
    obtain ⟨t, ⟨t0, t1⟩, ht⟩ := exists_of_segFrac_ne h0
    obtain ⟨⟨p1, p2⟩, p3, p4⟩ := hbox _ ht
    obtain ⟨o, i, j⟩ := s
    congr 3
    cases o
    · simp only [segPt, segA, segB, Bool.false_eq_true, if_false] at p1 p2 p3 p4
      simp only [wN, shiftIx, Bool.false_eq_true, if_false]
      rw [good_cell hgx hx0 hx1 (i := i) (by nlinarith) (by nlinarith),
        good_line hgy hy0 hy1 (j := j) (by nlinarith) (by nlinarith)]
    · simp only [segPt, segA, segB, if_true] at p1 p2 p3 p4
      simp only [wN, shiftIx, if_true]
      rw [good_cell hgy hy0 hy1 (i := j) (by nlinarith) (by nlinarith),
        good_line hgx hx0 hx1 (j := i) (by nlinarith) (by nlinarith)]
  · -- the Lebesgue square
    simp only [famCover, Finset.sum_const, Finset.card_univ, Fintype.card_unit, one_smul]
    rw [polyTerm (by omega), polyTerm (by norm_num)]
    congr 1
    have hset : sq (c - v) θ 1 ∩ lebSq 7 = (fun p => p + v) ⁻¹' (sq c θ 1 ∩ lebSq k) := by
      ext p
      simp only [Set.mem_inter_iff, Set.mem_preimage, mem_sq_sub]
      refine and_congr_right fun hp => ?_
      obtain ⟨⟨p1, p2⟩, p3, p4⟩ := hbox _ hp
      simp only [Prod.fst_add, Prod.snd_add, hv] at p1 p2 p3 p4
      simp only [lebSq, Set.mem_prod, Set.mem_Icc, Prod.fst_add, Prod.snd_add, hv]
      rw [good_leb hgx p1 p2, good_leb hgy p3 p4]
      simp only [add_sub_cancel_right]
    rw [hset, measure_preimage_add_right]

/-! ## 8.  Accounting -/

lemma sum_range_mod (m : ℕ) (G : ℕ → ℕ) :
    ∑ x ∈ range (5 * m), G (x % 5) = m * ∑ p ∈ range 5, G p := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [show 5 * (m + 1) = 5 * m + 5 by ring, sum_range_add, ih, add_mul, one_mul]
    congr 1
    refine sum_congr rfl fun y hy => ?_
    rw [mem_range] at hy
    congr 1; omega

/-- Cells of `[0,k]` by code: each edge offset twice, each phase `k − 4` times, `15` once. -/
lemma sum_cellT (m : ℕ) (F : ℤ → ℕ) :
    ∑ i ∈ idx (m + 4), F (cellT (m + 4) i)
      = 2 * ∑ a ∈ range 10, F a + m * ∑ p ∈ range 5, F (10 + (p : ℤ)) + F 15 := by
  rw [idx, sum_map, show 5 * (m + 4) + 1 = 10 + (5 * m + (10 + 1)) by ring, sum_range_add,
    sum_range_add, sum_range_succ (n := 10)]
  simp only [Function.Embedding.coeFn_mk]
  have h1 : ∑ x ∈ range 10, F (cellT (m + 4) (x : ℤ)) = ∑ a ∈ range 10, F a :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; congr 1; unfold cellT; split_ifs <;> omega
  have h2 : ∑ x ∈ range (5 * m), F (cellT (m + 4) ((10 + x : ℕ) : ℤ))
      = ∑ x ∈ range (5 * m), (fun p : ℕ => F (10 + (p : ℤ))) (x % 5) :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; simp only; congr 1; unfold cellT; split_ifs <;> omega
  have h3 : ∑ x ∈ range 10, F (cellT (m + 4) ((10 + (5 * m + x) : ℕ) : ℤ))
      = ∑ x ∈ range 10, (fun a : ℕ => F a) (10 - 1 - x) :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; simp only; congr 1; unfold cellT; split_ifs <;> omega
  have h4 : cellT (m + 4) ((10 + (5 * m + 10) : ℕ) : ℤ) = 15 := by
    unfold cellT; split_ifs <;> omega
  rw [h1, h2, h3, h4, sum_range_mod m (fun p : ℕ => F (10 + (p : ℤ))),
    sum_range_reflect (fun a : ℕ => F a) 10]
  ring

/-- Lines of `[0,k]` by code: each edge offset twice, phase 0 `k − 3` times, the other phases
`k − 4` times. -/
lemma sum_lineT (m : ℕ) (F : ℤ → ℕ) :
    ∑ j ∈ idx (m + 4), F (lineT (m + 4) j)
      = 2 * ∑ b ∈ range 10, F b + (m + 1) * F 10 + m * ∑ q ∈ range 4, F (11 + (q : ℤ)) := by
  rw [idx, sum_map, show 5 * (m + 4) + 1 = 10 + ((5 * m + 1) + 10) by ring, sum_range_add,
    sum_range_add, sum_range_succ (n := 5 * m)]
  simp only [Function.Embedding.coeFn_mk]
  have h1 : ∑ x ∈ range 10, F (lineT (m + 4) (x : ℤ)) = ∑ a ∈ range 10, F a :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; congr 1; unfold lineT; split_ifs <;> omega
  have h2 : ∑ x ∈ range (5 * m), F (lineT (m + 4) ((10 + x : ℕ) : ℤ))
      = ∑ x ∈ range (5 * m), (fun p : ℕ => F (10 + (p : ℤ))) (x % 5) :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; simp only; congr 1; unfold lineT; split_ifs <;> omega
  have h3 : ∑ x ∈ range 10, F (lineT (m + 4) ((10 + (5 * m + 1 + x) : ℕ) : ℤ))
      = ∑ x ∈ range 10, (fun a : ℕ => F a) (10 - 1 - x) :=
    sum_congr rfl fun x hx => by
      rw [mem_range] at hx; simp only; congr 1; unfold lineT; split_ifs <;> omega
  have h4 : lineT (m + 4) ((10 + 5 * m : ℕ) : ℤ) = 10 := by
    unfold lineT; split_ifs <;> omega
  rw [h1, h2, h3, h4, sum_range_mod m (fun p : ℕ => F (10 + (p : ℤ))),
    sum_range_reflect (fun a : ℕ => F a) 10]
  simp only [sum_range_succ, sum_range_zero]
  push_cast
  ring

theorem seg_total (m : ℕ) :
    ∑ s ∈ grid (m + 4), wN (m + 4) s = 7200000000000 * m + 12451029548888 := by
  have hA : ∑ a ∈ range 10, ∑ b ∈ range 10, tabW a b = 1115633136217 := by decide +kernel
  have hB : ∑ a ∈ range 10, tabW a 10 = 881491114788 := by decide +kernel
  have hC : ∑ a ∈ range 10, ∑ q ∈ range 4, tabW a (11 + q) = 362602284640 := by decide +kernel
  have hE : ∑ p ∈ range 5, ∑ b ∈ range 10, tabW (10 + p) b = 555906600572 := by decide +kernel
  have hM : ∀ p ∈ range 5, tabW (10 + p) 10 = 0 ∧ ∑ q ∈ range 4, tabW (10 + p) (11 + q) = 0 := by
    decide +kernel
  have hO : ∑ b ∈ range 10, tabW 15 b = 0 ∧ tabW 15 10 = 0 ∧
      ∑ q ∈ range 4, tabW 15 (11 + q) = 0 := by
    decide +kernel
  -- the horizontal half
  have hH : ∀ G : ℤ → ℤ → ℕ, (∀ c l, G c l = tabW c l) →
      ∑ i ∈ idx (m + 4), ∑ j ∈ idx (m + 4), G (cellT (m + 4) i) (lineT (m + 4) j)
        = 3600000000000 * m + 6225514774444 := by
    intro G hG
    simp only [hG]
    rw [sum_congr rfl fun i _ => sum_lineT m (tabW (cellT (m + 4) i))]
    rw [sum_cellT m (fun c => 2 * ∑ b ∈ range 10, tabW c b + (m + 1) * tabW c 10 +
      m * ∑ q ∈ range 4, tabW c (11 + (q : ℤ)))]
    simp only [sum_add_distrib, ← mul_sum]
    rw [sum_comm (s := range 5) (t := range 10)] at hE
    have hM1 : ∑ p ∈ range 5, tabW (10 + (p : ℤ)) 10 = 0 :=
      sum_eq_zero fun p hp => (hM p hp).1
    have hM2 : ∑ p ∈ range 5, ∑ q ∈ range 4, tabW (10 + (p : ℤ)) (11 + (q : ℤ)) = 0 :=
      sum_eq_zero fun p hp => (hM p hp).2
    rw [sum_comm (s := range 5) (t := range 10)]
    rw [hA, hB, hC, hE, hM1, hM2, hO.1, hO.2.1, hO.2.2]
    ring
  rw [grid, sum_product, Fintype.sum_bool]
  simp only [sum_product, wN, if_true, Bool.false_eq_true, if_false]
  rw [sum_comm (s := idx (m + 4)) (t := idx (m + 4))
    (f := fun i j => tabW (cellT (m + 4) j) (lineT (m + 4) i))]
  rw [hH _ fun _ _ => rfl]
  ring

/-! ## 9.  The end theorem -/

lemma famCover_nonneg (k : ℕ) : (famCover k).Nonneg :=
  ⟨fun e => e.elim, fun _ _ => by simp only [famCover]; positivity,
    fun _ _ => by simp only [famCover]; positivity⟩

/-- **Accounting**: `μ_k([0,k]²) ≤ total = k² − 4D`, `D = 423621306389/500000000000`. -/
theorem famCover_total (m : ℕ) :
    (famCover (m + 4)).total = (((m + 4 : ℕ) : ℝ)) ^ 2 - 4 * (423621306389 / 500000000000) := by
  have hs : ∑ s ∈ grid (m + 4), (wN (m + 4) s : ℝ) / 1000000000000
      = (7200000000000 * (m : ℝ) + 12451029548888) / 1000000000000 := by
    rw [← sum_div, ← Nat.cast_sum, seg_total]; push_cast; ring
  have he : ∀ f : Empty → ℝ, ∑ e ∈ (∅ : Finset Empty), f e = 0 := fun f => sum_empty
  simp only [MixedCover.total, famCover, he, hs, sum_const, card_univ, Fintype.card_unit,
    one_smul]
  push_cast
  ring

theorem measure_box_lt {k : ℕ} (hk : 6 ≤ k) :
    (famCover k).measure (box k) < ((k ^ 2 - 3 : ℕ) : ℝ≥0∞) := by
  obtain ⟨m, rfl⟩ : ∃ m, k = m + 4 := ⟨k - 4, by omega⟩
  have hk3 : 3 ≤ (m + 4) ^ 2 := by nlinarith
  have hm0 : (0 : ℝ) ≤ m := Nat.cast_nonneg m
  calc (famCover (m + 4)).measure (box ((m + 4 : ℕ) : ℝ))
      ≤ (famCover (m + 4)).measure Set.univ := measure_mono (Set.subset_univ _)
    _ ≤ ENNReal.ofReal (famCover (m + 4)).total := (famCover (m + 4)).measure_univ_le
        (famCover_nonneg _)
    _ < ENNReal.ofReal (((m + 4) ^ 2 - 3 : ℕ) : ℝ) := by
        rw [ENNReal.ofReal_lt_ofReal_iff (by rw [Nat.cast_sub hk3]; push_cast; nlinarith),
          famCover_total, Nat.cast_sub hk3]
        push_cast; norm_num
    _ = (((m + 4) ^ 2 - 3 : ℕ) : ℝ≥0∞) := ENNReal.ofReal_natCast _

/-- **The reduction**: `Valid7` gives every closed unit square in `[0,k]²` mass `≥ 1` under
`μ_k`, for every `k ≥ 6`. -/
theorem valid_of_valid7 (h : Valid7) {k : ℕ} (hk : 6 ≤ k) (c : ℝ × ℝ) (θ : ℝ)
    (hS : sq c θ 1 ⊆ box k) : 1 ≤ (famCover k).measure (sq c θ 1) := by
  obtain ⟨v, hv7, hm⟩ := mass_shift hk c θ hS
  have h7 := h _ _ hv7
  rw [box7Cover_measure, MixedCover.measure_apply _ (famCover_nonneg 7) (measurableSet_sq _ _ _)]
    at h7
  rw [MixedCover.measure_apply _ (famCover_nonneg k) (measurableSet_sq _ _ _), hm]
  exact h7

/-- **`s(k² − 3) = k` for all `k ≥ 6`, from `Valid7`** (the statement suggested by Bentz, arXiv:1606.03746, and
implied by Friedman's survey Conjecture 1 with `s(6) = 3`; `k ≤ 7` were known). -/
theorem bentz_of_valid7 (h : Valid7) : ∀ k : ℕ, 6 ≤ k → minSide (k ^ 2 - 3) = k := by
  intro k hk
  have hnot : ∀ s : ℝ, s < k → ¬ Packs (k ^ 2 - 3) s := fun s hs =>
    not_packs_of_measure k (famCover k).measure (valid_of_valid7 h hk) (k ^ 2 - 3)
      (measure_box_lt hk) hs
  have hp : Packs (k ^ 2 - 3) k := packs_grid k (k ^ 2 - 3) (by rw [pow_two]; exact Nat.sub_le _ _)
  have hl : IsLeast {s | Packs (k ^ 2 - 3) s} k :=
    ⟨hp, fun _ hs => not_lt.mp fun hlt => hnot _ hlt hs⟩
  exact hl.csInf_eq

end Bentz
end SquarePacking
