import Sqpack.ValidSplit7
import Sqpack.LebMass7Data

/-!
# Smoke test: every LEB and CAP leaf of the `k² − 3` run, in the kernel

`LebMass7Data.lean` (generated by `lean/scripts/gen_lebmass_data.py`) lists the 689 LEB and 374 CAP
leaves of run V3 of `qx2_zm.py` on `L4_k02_box7.txt` (boxes after `clip_bin`, as recorded in
`search/qx2_data/cert/runV3_6294052a_leaves.jsonl.gz`).  Here the kernel runs `LebMass.lebOK` /
`LebMass.capOK` on all of them, against the packed weights of the box file (`box7Packed`, tied to the
file by `box7_grid`), and Lemmas U and K turn that into `CovT` of each leaf box for `μ₇` itself.

`notes/lean-leb-mass.md`.
-/

open MeasureTheory

namespace SquarePacking
namespace Bentz

open ValidSplit LebMass

/-- The LEB test passes on every LEB leaf (Lebesgue square `[9/5, 26/5]²`). -/
theorem leb7_ok : lebLeaves7.all (lebOK ((9 : ℕ) / 5) ((7 : ℕ) - (9 : ℕ) / 5)) = true := by
  decide +kernel

/-- The CAP test passes on every CAP leaf. -/
theorem cap7_ok : capLeaves7.all (capOK 7 9 1000000000000 (wP box7Packed (5 * 7))) = true := by
  decide +kernel

/-- **Lemma U on run V3's LEB leaves**: each box certifies `μ₇(Q) ≥ 1` for its poses. -/
theorem leb7_cov : ∀ B ∈ lebLeaves7, B.Cov 7 box7Cover.measure := by
  intro B hB
  rw [PBox.Cov, box7_grid]
  exact leb_sound_grid (K := 7) (A := 9) (by norm_num) (List.all_eq_true.mp leb7_ok B hB)

/-- **Lemma K on run V3's CAP leaves**: each box certifies `μ₇(Q) ≥ 1` for its poses. -/
theorem cap7_cov : ∀ B ∈ capLeaves7, B.Cov 7 box7Cover.measure := by
  intro B hB
  have h := cap_sound (K := 7) (A := 9) (den := 1000000000000) (by norm_num) (by norm_num)
    (List.all_eq_true.mp cap7_ok B hB)
  rw [PBox.Cov, box7_grid]
  simpa only [Nat.cast_ofNat, PBox.Cov] using h

end Bentz
end SquarePacking
