import Sqpack.S11.Cov

/-!
# `s(11) ≥ 3040/797 = 3.8143036…`, kernel-checked

The certificate `certificates/s11_lower_3.8143.txt`: 680 points in `[0, 3040/797]²` with
weights `w/10⁷` of total `10.8146708 < 11`, such that every closed unit square inside the
container captures weight `≥ 1`.  Same generic verifier and the same one-call proof as
`S12Lower.lean`; only the data (`Sqpack/S11/*`, generated by `lean/scripts/gen_boxtree.py`)
differ.  See `lean/LADDER.md`.
-/

namespace SquarePacking

open BoxTree S11

/-- **`s(11) ≥ 3040/797 = 3.8143036…`**. -/
theorem s11_ge_3040_797 : (3040 / 797 : ℝ) ≤ minSide 11 := by
  have h := le_minSide 3985 4096 15200 73400320 30408704 10000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 11 4
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

end SquarePacking
