import Sqpack.S12H.Cov

/-!
# `s(12) ≥ 15680/3951 = 3.968616…`, kernel-checked (the headline bound)

The certificate `certificates/s12_lower_3.9686.txt`: 1736 points in `[0, 15680/3951]²` with
weights `w/10⁷` of total `11.9738036 < 12`, such that every closed unit square inside the
container captures weight `≥ 1`.  Same generic verifier (`BoxTree`) and the same one-call proof as
`S12WLower.lean`; only the data (`Sqpack/S12H/*`, generated by `lean/scripts/gen_boxtree.py`,
gitignored: `lean/scripts/gen_data.sh S12H`) differ.  The point set is D4-invariant (`pts_d4`).

Opt-in (not imported by `Sqpack.lean`): build with
`lean/scripts/build_parts.sh S12H Sqpack.S12HLower 1 14-15`, not a plain `lake build`
(one part at a time: the heaviest part file peaks at ~31 GB).
See `lean/LADDER.md`.
-/

namespace SquarePacking

open BoxTree S12H

/-- **`s(12) ≥ 15680/3951 = 3.968616…`**, with no hypothesis. -/
theorem s12_ge_15680_3951 : (15680 / 3951 : ℝ) ≤ minSide 12 := by
  have h := le_minSide 3951 4096 15680 73400320 30408704 10000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 12 4
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

end SquarePacking
