import Sqpack.S12U.Cov

/-!
# `s(12) ≥ 35/9`, kernel-checked (pilot rung of the Lean lower-bound ladder)

The certificate `certificates/s12_uniform_7of81_3.888.txt`: 81 points in `[0, 35/9]²` such that
every closed unit square inside the container, at every angle, contains at least 7 of them
(weights `1/7`, total `81/7 < 12`).  The box tree `Sqpack/S12U/*` (generated by
`lean/scripts/gen_boxtree.py`) is checked by the generic verifier `BoxTree.check` in the kernel
(`decide +kernel`, no `native_decide`); `BoxTree.le_minSide` turns the covered root box, the
D4 symmetry of the points and the total weight into the bound.  See `lean/LADDER.md`.
-/

namespace SquarePacking

open BoxTree S12U

/-- **`s(12) ≥ 35/9 = 3.8888…`**: twelve unit squares do not fit in any square of side
`< 35/9`. -/
theorem s12_ge_35_9 : (35 / 9 : ℝ) ≤ minSide 12 := by
  have h := le_minSide 7920 4096 30800 73400320 30408704 7 pts (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 12 4 (by rw [pts_wsum]; norm_num)
    (by norm_num)
  norm_num at h ⊢
  exact h

end SquarePacking
