import Sqpack.S12W.Cov

/-!
# `s(12) ≥ 3920/997`, kernel-checked (a weighted certificate on the same verifier)

The certificate `certificates/s12_lower_3.931795_sparse.txt`: 224 points in `[0, 3920/997]²`
with weights `w/10⁷` of total `11.9834372 < 12`, such that every closed unit square inside the
container captures weight `≥ 1`.  Same generic verifier and the same one-call proof as
`S12Lower.lean`; only the data (`Sqpack/S12W/*`, generated by `lean/scripts/gen_boxtree.py`)
differ.  See `lean/LADDER.md`.
-/

namespace SquarePacking

open BoxTree S12W

/-- **`s(12) ≥ 3920/997 = 3.931795…`**. -/
theorem s12_ge_3920_997 : (3920 / 997 : ℝ) ≤ minSide 12 := by
  have h := le_minSide 1994 4096 7840 73400320 30408704 10000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 12 4
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

end SquarePacking
