import Sqpack.S13.Cov
import Sqpack.Attain

/-!
# `s(13) = 4`, kernel-checked (the first zero-margin rung of the Lean ladder)

The certificate `certificates/rung2/s13_closed_cover_4.txt` (`notes/s13-casefree.md`): 3,621
points of `[0,4]²` with weights `w/10⁹` of total `12.955972155 < 13`, such that every **closed**
unit square inside `[0,4]²` captures weight `≥ 1`.  At side `4` the bound is sharp (the 4×4
tiling), so no monotone witness tree can prove it (`search/RUNG2.md` §2); the tree here uses the
zero-margin leaves of `ZMTree.lean` (`ADM` with wall bounds, `clip_bin`, `EMPTY`, and the
disjunctive `CHAIN`, one chain or a product of two).  The data (`Sqpack/S13/*`) is generated by
`lean/scripts/gen_zmtree.py`; nothing about it is trusted — every chunk is `decide +kernel` of
`ZMTree.check`, proved sound once (`ZMTree.sound`).  See `lean/LADDER.md`.

Opt-in (not imported by `Sqpack.lean`): `lake build Sqpack.S13Lower`.
-/

namespace SquarePacking

open BoxTree S13

/-- **`s(13) ≥ 4`**: 13 unit squares do not fit in a square of side `< 4`. -/
theorem s13_ge_4 : (4 : ℝ) ≤ minSide 13 := by
  have h := le_minSide 1000 4096 4000 4294967296 2147483648 1000000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 13 4
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

/-- **`s(13) = 4`**: with the 4×4 grid (`packs_grid`), `4` is the least side. -/
theorem s13_eq_4 : minSide 13 = 4 := by
  have h1 := s13_ge_4
  have hp : Packs 13 4 := by
    have h := packs_grid 4 13 (by norm_num)
    simpa using h
  have hb : BddBelow {s | Packs 13 s} := by
    by_contra hnb
    rw [minSide, Real.sInf_of_not_bddBelow hnb] at h1
    norm_num at h1
  exact le_antisymm (csInf_le hb hp) h1

/-- The minimum is attained: `4` is the least side for 13 unit squares (`isLeast_minSide`). -/
theorem s13_isLeast : IsLeast {s | Packs 13 s} 4 :=
  (minSide_eq_iff_isLeast (by norm_num)).mp s13_eq_4

end SquarePacking
