import Sqpack.T1.Cov

/-!
# `s(16) ≥ 4` from the grid-line cover T1: the full toy run of the mixed verifier (opt-in)

The cover `T1` (`lean/toys/T1.txt`, `search/zm_mixed_test.py grid_cover(rho = 5/8)`, `ZM_MIXED.md`
§4.3): the six interior grid lines of `[0,4]²` at density `5/8`, 240 segments of length `1/10`, total
`15 < 16`.  Its minimum over closed unit squares is `2 · 0.8284 · 5/8 = 1.0355` (diamonds at `45°`),
and every tile germ has `2 · 5/8 = 1.25` one-sided — so the tree needs Lemma T (the germ pairs,
T-groups) and, to stay small, Lemma L (L-blocks).  The bound itself is trivial (area); the point is
the verifier: 9,451 `Z` leaves (8,256 with an L-block, 1,742 with T-groups), generated by
`lean/scripts/gen_zmmtree.py`, data gitignored:

    python3 lean/scripts/gen_zmmtree.py lean/toys/T1.txt --n 16 --depth 24 --nproc 3 \
      --name T1 --outdir lean/Sqpack/T1 --chunk-cost 2000 --parts 6
    lean/scripts/build_parts.sh T1 Sqpack.S16Lower 3 12-14
-/

namespace SquarePacking

open ZMTreeM

/-- **`s(16) ≥ 4`** from a pure-segment mixed cover (toy). -/
theorem s16_ge_4 : (4 : ℝ) ≤ minSide 16 := by
  have h := le_minSide_mixed 1000 4096 4000 4294967296 2147483648 1000000 T1.pts T1.segs
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) T1.pts_nodup T1.pts_d4 T1.segs_d4
    T1.cov_root 16 4 T1.wsum_lt (by norm_num)
  have e : ((4000 : ℕ) : ℝ) / ((1000 : ℕ) : ℝ) = 4 := by norm_num
  rw [e] at h
  exact h

end SquarePacking
