import Sqpack.S32
import Sqpack.S32Z.Cov

/-!
# `s(32) = 6`, kernel-checked with no hypothesis (the zero-margin rung of the Lean ladder)

The certificate `certificates/s32/s32_closed_cover_6.txt`: 13,085 points of `[0,6]²` with
weights `w/10¹¹` of total `31.713505354 < 32`, such that every **closed** unit square inside
`[0,6]²` captures weight `≥ 1`.  `S32.lean` proved `s(32) = 6` from the one computational
hypothesis `S32CheckerCover` (what `search/zeromargin.py`'s D4 run certifies); here that hypothesis
is a theorem, `s32_checkerCover`, from the zero-margin box tree `Sqpack/S32Z/*` (generated by
`lean/scripts/gen_zmtree.py`; nothing about it is trusted — every chunk is `decide +kernel` of
`ZMTree.check`, proved sound once, `ZMTree.sound`).  See `lean/LADDER.md`.

* `s32_ge_6` — directly by the generic `BoxTree.le_minSide` (as for `s13_ge_4`);
* `s32_checkerCover` — the hypothesis of `S32.lean`, discharged; the transcription
  `S32Data.tree` of `S32.lean` is the same list as the generator's `ptsL` (`s32_tree_toList`, kernel);
* `s32_eq_6` — `minSide 32 = 6`, via `S32.lean`'s `s32_eq_six_of_checker`.

Opt-in (not imported by `Sqpack.lean`; the data is gitignored): `lean/scripts/gen_data.sh S32Z`,
then `lake build Sqpack.S32Lower`.
-/

namespace SquarePacking

open BoxTree S32Z
open scoped Classical

/-- **`s(32) ≥ 6`**: 32 unit squares do not fit in a square of side `< 6`. -/
theorem s32_ge_6 : (6 : ℝ) ≤ minSide 32 := by
  have h := le_minSide 1000 4096 6000 4294967296 2147483648 100000000000 pts (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) pts_nodup pts_d4 cov_root 32 6
    (by rw [pts_wsum]; norm_num) (by norm_num)
  norm_num at h ⊢
  exact h

-- the kernel's list comparison recurses once per entry (13,085)
set_option maxRecDepth 100000 in
/-- `S32.lean`'s transcription of the certificate is the generator's point list. -/
theorem s32_tree_toList : S32Data.tree.toList = ptsL := by decide +kernel

/-- The zero-margin box tree's `Cov` gives the checker statement of `S32.lean`. -/
theorem S32CheckerCover.of_cov
    (h : Cov 1000 4096 6000 4294967296 100000000000 S32Data.tree.toList
      0 12288000 0 12288000 0 2147483648) :
    S32CheckerCover := by
  intro c u h1 h2 hu hsub
  have hc := h c u (by norm_num; exact h1.1) (by norm_num; exact h1.2)
    (by norm_num; exact h2.1) (by norm_num; exact h2.2) (by norm_num; exact hu.1)
    (by norm_num; exact hu.2) (by norm_num; exact hsub)
  have e1 : (S32Data.pt : ℕ × ℕ × ℕ → ℝ × ℝ) = ptR 1000 := by
    funext e; simp [S32Data.pt, ptR]
  rw [S32Data.entries, e1]
  have : ∑ e ∈ S32Data.tree.toList.toFinset.filter
        (fun e => ptR 1000 e ∈ sq c (2 * Real.arctan u) 1), S32Data.wt e
      = (∑ e ∈ S32Data.tree.toList.toFinset.filter
        (fun e => ptR 1000 e ∈ sq c (2 * Real.arctan u) 1), (e.2.2 : ℝ)) / 100000000000 := by
    rw [Finset.sum_div]; rfl
  rw [this, le_div_iff₀ (by norm_num)]
  have : ((100000000000 : ℕ) : ℝ) = 100000000000 := by norm_num
  rw [this] at hc
  linarith

/-- **The hypothesis of `S32.lean`, proved**: every closed unit square in `[0,6]²` with centre in
`[0,3]²` and angle `2 arctan u`, `u ∈ [0, 1/2]`, captures weight `≥ 1` of the cover. -/
theorem s32_checkerCover : S32CheckerCover :=
  S32CheckerCover.of_cov (s32_tree_toList ▸ cov_rootL)

/-- **`s(32) = 6`**, with no hypothesis. -/
theorem s32_eq_6 : minSide 32 = 6 :=
  s32_eq_six_of_checker s32_checkerCover

end SquarePacking
