import Sqpack.M2.Cov
import Sqpack.Attain

/-!
# `s(3) ≥ 2` from a mixed cover: the toy end-to-end run of the mixed verifier

The cover (`M2`, generated by `lean/scripts/gen_zmmtree.py` from `search/zm_mixed_test.py`'s
`grid_cover(m=2, rho=5/8)`): the two interior grid lines `x = 1` and `y = 1` of `[0,2]²`, carrying mass
`5/8` per unit length uniformly, cut into 40 segments of length `1/10`, total `5/2 < 3`.  Every closed
unit square in `[0,2]²` captures mass `≥ 1` (the minimum, `2 · 0.8284 · 5/8 = 1.0355`, is a diamond
at `45°` crossing both lines), so three unit squares do not fit in a square of side `< 2`.

This exercises the whole mixed pipeline: `ZMTreeM.soundM` (S-block leaves, `CovM`, `clip_bin`, `E`),
`CovM.split*`, and `le_minSide_mixed` (`MixedCover.measure`, D4 reduction for measures,
`not_packs_of_measure`).  (`s(3) = 2` is classical; the point is the verifier, not the bound.)
-/

namespace SquarePacking

open ZMTreeM

/-- **`s(3) ≥ 2`**, from a pure-segment mixed cover, by the mixed zero-margin verifier. -/
theorem s3_ge_2 : (2 : ℝ) ≤ minSide 3 := by
  have h := le_minSide_mixed 1000 4096 2000 4294967296 2147483648 1000000 M2.pts M2.segs
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) M2.pts_nodup M2.pts_d4 M2.segs_d4
    M2.cov_root 3 2 M2.wsum_lt (by norm_num)
  have e : ((2000 : ℕ) : ℝ) / ((1000 : ℕ) : ℝ) = 2 := by norm_num
  rw [e] at h
  exact h

/-- **`s(3) = 2`**: with the 2×2 grid (`packs_grid`). -/
theorem s3_eq_2 : minSide 3 = 2 :=
  le_antisymm (minSide_le (by norm_num) (by simpa using packs_grid 2 3 (by norm_num))) s3_ge_2

/-- The minimum is attained: `2` is the least side for 3 unit squares. -/
theorem s3_isLeast : IsLeast {s | Packs 3 s} 2 := (minSide_eq_iff_isLeast (by norm_num)).mp s3_eq_2

end SquarePacking
