#!/usr/bin/env python3
"""Transcribe the s(32) cover into Lean: lean/Sqpack/S32Data.lean.

Usage (from s12/):  python3 lean/scripts/gen_s32_data.py [certificates/s32/s32_closed_cover_6.txt]

The certificate format (header `m 1`, `D`, `W`, `n`, then `x y w` integer lines; the point is
(x/D, y/D), the weight w/W) is transcribed entry by entry: every line becomes one node
`(x, y, w)` of a binary search tree keyed on (x, y), so that the Lean kernel can look entries up
in O(log n) (`Sqpack/Cover.lean`).  Nothing is aggregated, rounded or reordered other than the
sort by key; the script refuses a file with a repeated point (then the tree would need
aggregation) and checks the header against the constants Sqpack/S32.lean hard-codes.
`--check` regenerates in memory and compares with the committed file.
"""
import hashlib
import sys

EXPECT = {"m": 6, "D": 1000, "W": 100000000000}
CHUNK = 256  # subtrees of at most this many entries become their own `def`


def read_cert(path):
    raw = open(path, "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    lines = [l.split() for l in raw.decode().splitlines() if l.strip()]
    m, _one = map(int, lines[0])
    D = int(lines[1][0])
    W = int(lines[2][0])
    n = int(lines[3][0])
    pts = [tuple(map(int, l)) for l in lines[4:]]
    assert (m, D, W) == (EXPECT["m"], EXPECT["D"], EXPECT["W"]), (m, D, W)
    assert len(pts) == n, (len(pts), n)
    assert all(len(p) == 3 and min(p) >= 0 for p in pts)
    keys = [(x, y) for x, y, _ in pts]
    assert len(set(keys)) == n, "repeated point: aggregate first"
    return sha, m, D, W, sorted(pts)


def emit(pts):
    defs = []

    def build(lo, hi, top):
        if lo >= hi:
            return ".leaf"
        if not top and hi - lo <= CHUNK:
            name = f"t{len(defs)}"
            defs.append(None)
            idx = len(defs) - 1
            body = build_inline(lo, hi)
            defs[idx] = f"def {name} : PTree :=\n  {body}\n"
            return name
        mid = (lo + hi) // 2
        x, y, w = pts[mid]
        return f"(.node {build(lo, mid, False)} {x} {y} {w} {build(mid + 1, hi, False)})"

    def build_inline(lo, hi):
        if lo >= hi:
            return ".leaf"
        mid = (lo + hi) // 2
        x, y, w = pts[mid]
        return f"(.node {build_inline(lo, mid)} {x} {y} {w} {build_inline(mid + 1, hi)})"

    root = build(0, len(pts), True)
    return defs, root


def render(path):
    sha, m, D, W, pts = read_cert(path)
    defs, root = emit(pts)
    total = sum(w for _, _, w in pts)
    out = [
        "import Sqpack.Cover",
        "",
        "/-!",
        "# The `s(32)` cover, as data (generated; do not edit)",
        "",
        f"Generated by `lean/scripts/gen_s32_data.py` from `runs/s32-close_candidate.txt`,",
        f"sha256 `{sha}`.",
        f"{len(pts)} entries `(x, y, w)`: the point `(x/{D}, y/{D})` with weight `w/{W}`, one node per",
        f"certificate line, in a search tree on `(x, y)`.  Total weight `{total}/{W}`.",
        "-/",
        "",
        "set_option linter.style.longLine false",
        "",
        "namespace SquarePacking.S32Data",
        "",
        "open PTree",
        "",
    ]
    for d in defs:
        out.append(d)
    out.append("/-- The whole cover. -/")
    out.append(f"def tree : PTree :=\n  {root}\n")
    out.append("end SquarePacking.S32Data")
    return "\n".join(out) + "\n", sha, len(pts), total


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    path = args[0] if args else "certificates/s32/s32_closed_cover_6.txt"
    text, sha, n, total = render(path)
    target = "lean/Sqpack/S32Data.lean"
    if "--check" in sys.argv:
        ok = open(target).read() == text
        print(f"{target} {'matches' if ok else 'DIFFERS FROM'} {path} (sha256 {sha})")
        sys.exit(0 if ok else 1)
    open(target, "w").write(text)
    print(f"wrote {target}: {n} entries, total {total}, sha256 {sha}")


if __name__ == "__main__":
    main()
