#!/usr/bin/env python3
"""Transcribe the s(21) mixed cover into Lean: lean/Sqpack/S21Data.lean.

Usage (from s12/):  python3 lean/scripts/gen_s21_data.py [certificates/s21/s21_mixed_cover_5.txt] [--check]

Mixed format v1 (certificates/s21/FORMAT.md): `mixed 1`, `s_num s_den`, `D`, `W`, `np` point lines
`X Y w`, `ns` segment lines `X0 Y0 X1 Y1 w`, `npg` polygon lines (`#` comments to end of line).
Points become nodes `(X, Y, w)` of a `PTree` keyed on (X, Y) (Sqpack/Cover.lean); segments become
nodes `(X0, Y0, X1, Y1, w)` of an `STree` (Sqpack/SegTree.lean) keyed on (X0, Y0, X1, Y1), with the two
endpoints put in lexicographic order (the measure does not depend on the orientation: Lean
`segMeasure_comm`).  Nothing is aggregated, rounded or reordered other than that and the sort by key.
The script refuses repeated points, repeated segments, zero-length segments and polygons (the Lean
side hard-codes npg = 0), and checks the header against the constants Sqpack/S21.lean hard-codes.
`--check` regenerates in memory and compares with the committed file.
"""
import hashlib
import sys

EXPECT = {"s": (5, 1), "D": 1000, "W": 100000000000}
CHUNK = 256  # subtrees of at most this many entries become their own `def`


def read_cover(path):
    raw = open(path, "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    toks = []
    for line in raw.decode().splitlines():
        line = line.split("#", 1)[0]
        toks.extend(line.split())
    assert toks[:2] == ["mixed", "1"], toks[:2]
    it = iter(int(t) for t in toks[2:])
    s = (next(it), next(it))
    D, W = next(it), next(it)
    assert (s, D, W) == (EXPECT["s"], EXPECT["D"], EXPECT["W"]), (s, D, W)
    np_ = next(it)
    pts = [(next(it), next(it), next(it)) for _ in range(np_)]
    ns = next(it)
    segs = [tuple(next(it) for _ in range(5)) for _ in range(ns)]
    npg = next(it)
    assert npg == 0, "polygons are not transcribed (S21.lean assumes none)"
    assert next(it, None) is None, "trailing data"
    assert all(min(p) >= 0 for p in pts) and all(min(q) >= 0 for q in segs)
    assert len({(x, y) for x, y, _ in pts}) == np_, "repeated point: aggregate first"
    nsegs = []
    for x0, y0, x1, y1, w in segs:
        assert (x0, y0) != (x1, y1), "zero-length segment"
        if (x1, y1) < (x0, y0):
            x0, y0, x1, y1 = x1, y1, x0, y0
        nsegs.append((x0, y0, x1, y1, w))
    assert len({q[:4] for q in nsegs}) == ns, "repeated segment"
    return sha, D, W, sorted(pts), sorted(nsegs)


def emit(items, prefix, fmt):
    defs = []

    def build(lo, hi, top):
        if lo >= hi:
            return ".leaf"
        if not top and hi - lo <= CHUNK:
            name = f"{prefix}{len(defs)}"
            defs.append(None)
            idx = len(defs) - 1
            defs[idx] = (name, build_inline(lo, hi))
            return name
        mid = (lo + hi) // 2
        return f"(.node {build(lo, mid, False)} {fmt(items[mid])} {build(mid + 1, hi, False)})"

    def build_inline(lo, hi):
        if lo >= hi:
            return ".leaf"
        mid = (lo + hi) // 2
        return f"(.node {build_inline(lo, mid)} {fmt(items[mid])} {build_inline(mid + 1, hi)})"

    root = build(0, len(items), True)
    return defs, root


def render(path):
    sha, D, W, pts, segs = read_cover(path)
    pdefs, proot = emit(pts, "p", lambda e: f"{e[0]} {e[1]} {e[2]}")
    sdefs, sroot = emit(segs, "s", lambda e: f"({e[0]}, {e[1]}, {e[2]}, {e[3]}, {e[4]})")
    ptot = sum(e[2] for e in pts)
    stot = sum(e[4] for e in segs)
    out = [
        "import Sqpack.SegTree",
        "",
        "/-!",
        "# The `s(21)` mixed cover, as data (generated; do not edit)",
        "",
        f"Generated by `lean/scripts/gen_s21_data.py` from `{path}`,",
        f"sha256 `{sha}`.",
        f"{len(pts)} point entries `(X, Y, w)`: the point `(X/{D}, Y/{D})` with mass `w/{W}`, in a search",
        "tree on `(X, Y)`; point mass total " + f"`{ptot}/{W}`.",
        f"{len(segs)} segment entries `(X0, Y0, X1, Y1, w)`: mass `w/{W}` uniformly on the segment",
        f"`(X0/{D}, Y0/{D})`–`(X1/{D}, Y1/{D})`, endpoints in lexicographic order, in a search tree on",
        f"`(X0, Y0, X1, Y1)`; segment mass total `{stot}/{W}`.  No polygons.",
        f"Total `{ptot + stot}/{W}`.",
        "-/",
        "",
        "set_option linter.style.longLine false",
        "",
        "namespace SquarePacking.S21Data",
        "",
    ]
    for name, body in pdefs:
        out.append(f"def {name} : PTree :=\n  {body}\n")
    for name, body in sdefs:
        out.append(f"def {name} : STree :=\n  {body}\n")
    out.append("/-- The point entries. -/")
    out.append(f"def ptree : PTree :=\n  {proot}\n")
    out.append("/-- The segment entries. -/")
    out.append(f"def stree : STree :=\n  {sroot}\n")
    out.append("end SquarePacking.S21Data")
    return "\n".join(out) + "\n", sha, len(pts), len(segs), ptot, stot


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    path = args[0] if args else "certificates/s21/s21_mixed_cover_5.txt"
    text, sha, npt, nsg, ptot, stot = render(path)
    target = "lean/Sqpack/S21Data.lean"
    if "--check" in sys.argv:
        ok = open(target).read() == text
        print(f"{target} {'matches' if ok else 'DIFFERS FROM'} {path} (sha256 {sha})")
        sys.exit(0 if ok else 1)
    open(target, "w").write(text)
    print(f"wrote {target}: {npt} points (total {ptot}), {nsg} segments (total {stot}), "
          f"total {ptot + stot}, sha256 {sha}")


if __name__ == "__main__":
    main()
