#!/usr/bin/env python3
"""gen_bentz_data.py -- write lean/Sqpack/BentzData.lean (task lean-bentz-reduction).

Inputs (exact rationals, read-only; sha256 recorded in the output):
  search/qx2_data/L4_k02_box7.txt    the box cover k = 7 (FORMAT.md v1): the literal list of its 800 segments and
                                     its one polygon, in file order -- this is what `Bentz.Valid7` is about;
  search/qx2_data/L4_k02_family.txt  the fixed-profile family (R = w = 2, pitch 1/5): the 16 x 16 table `famTab`
                                     from which `Bentz.famCover k` builds mu_k for every k.
Nothing here is trusted by Lean: `Bentz.lean` proves (kernel evaluation) that `famCover 7` is the box file's
cover, and proves the accounting and the reduction for all k.

Table: codes 0..9 = offset (in 1/5 units) of a cell / line from the nearest wall (edge zone, x < 2 or x > k - 2),
10 + p = phase p (in 1/5 units) of a cell / line in the band zone [2, k - 2], 15 = outside [0, k].
famTab[16 c + l] = mass (units 10^-12) of the horizontal unit segment whose x-cell has code c and y-line code l
(vertical segments: the diagonal image, x-line code l, y-cell code c).
  corner module:  H y x0 x1 m  ->  (c, l) = (5 x0, 5 y);   V x y0 y1 m -> (5 y0, 5 x)  (the same entry, nu is
                  diagonal-symmetric; checked);
  profile:        h y p0 p1 m  ->  (10 + 5 p0, 5 y);        v p y0 y1 m -> (5 y0, 10 + 5 p).

usage: python3 lean/scripts/gen_bentz_data.py [--search ../search] [--out lean/Sqpack/BentzData.lean]
(run from s12/; deterministic)
"""
import argparse, hashlib, os
from fractions import Fraction as F

W = 10 ** 12


def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def read_box(path):
    tok = []
    for ln in open(path):
        tok += ln.split('#', 1)[0].split()
    it = iter(tok)
    assert next(it) == 'mixed' and next(it) == '1'
    sn, sd, D, Wd = (int(next(it)) for _ in range(4))
    assert (sn, sd, D, Wd) == (7, 1, 5, W), (sn, sd, D, Wd)
    npt = int(next(it)); assert npt == 0, 'points present'
    ns = int(next(it))
    segs = [tuple(int(next(it)) for _ in range(5)) for _ in range(ns)]
    npg = int(next(it)); assert npg == 1
    kk = int(next(it)); pw = int(next(it))
    verts = [(int(next(it)), int(next(it))) for _ in range(kk)]
    rest = list(it); assert not rest, rest
    return segs, verts, pw


def read_family(path):
    tab = {}

    def put(c, l, m):
        assert 0 <= c < 15 and 0 <= l < 15, (c, l)
        assert (c, l) not in tab or tab[(c, l)] == m, ('conflict', c, l)
        tab[(c, l)] = m

    for ln in open(path):
        if ln.startswith('#'):
            continue
        t = ln.split()
        if not t:
            continue
        v = [F(x) for x in t[1:]]
        m = v[-1] * W
        assert m.denominator == 1 and m > 0
        m = int(m)
        if t[0] == 'H':
            y, x0, x1 = v[:3]; assert x1 - x0 == F(1, 5) and 0 <= x0 and x1 <= 2 and 0 < y < 2
            put(int(5 * x0), int(5 * y), m)
        elif t[0] == 'V':
            x, y0, y1 = v[:3]; assert y1 - y0 == F(1, 5) and 0 <= y0 and y1 <= 2 and 0 < x < 2
            put(int(5 * y0), int(5 * x), m)
        elif t[0] == 'h':
            y, p0, p1 = v[:3]; assert p1 - p0 == F(1, 5) and 0 <= p0 and p1 <= 1 and 0 < y < 2
            put(10 + int(5 * p0), int(5 * y), m)
        elif t[0] == 'v':
            p, y0, y1 = v[:3]; assert y1 - y0 == F(1, 5) and 0 <= p < 1 and 0 <= y0 and y1 <= 2
            put(int(5 * y0), 10 + int(5 * p), m)
        else:
            raise ValueError(ln)
    return tab


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--search', default='search')
    ap.add_argument('--out', default='lean/Sqpack/BentzData.lean')
    A = ap.parse_args()
    boxp = os.path.join(A.search, 'qx2_data/L4_k02_box7.txt')
    famp = os.path.join(A.search, 'qx2_data/L4_k02_family.txt')
    segs, verts, pw = read_box(boxp)
    tab = read_family(famp)
    flat = [tab.get((c, l), 0) for c in range(16) for l in range(16)]
    out = []
    out.append('/-!\n# Data for `Bentz.lean` (generated by `lean/scripts/gen_bentz_data.py`; do not edit)\n')
    out.append(f'* `search/qx2_data/L4_k02_box7.txt`   sha256 `{sha(boxp)}`')
    out.append(f'* `search/qx2_data/L4_k02_family.txt` sha256 `{sha(famp)}`\n')
    out.append('`boxSegs`, `boxPolyVerts`, `boxPolyW` are the box file verbatim (header `mixed 1`, side `7/1`, '
               'coordinate\ndenominator `5`, mass denominator `10¹²`, no points, '
               f'{len(segs)} segments `(X0, Y0, X1, Y1, w)` in file order, one polygon).\n'
               '`famTab` is the family file as a 16 × 16 table (see the script).\n-/\n')
    out.append('namespace SquarePacking.Bentz\n')
    out.append(f'/-- The {len(segs)} segments `(X0, Y0, X1, Y1, w)` of `L4_k02_box7.txt`, in file order. -/')
    out.append('def boxSegs : List (Nat × Nat × Nat × Nat × Nat) := [')
    body = [f'  ({a}, {b}, {c}, {d}, {w})' for (a, b, c, d, w) in segs]
    out.append(',\n'.join(body) + ']\n')
    out.append('/-- The polygon of `L4_k02_box7.txt`: its vertices `(X, Y)` (counter-clockwise), and its mass `w`. -/')
    out.append('def boxPolyVerts : List (Nat × Nat) := [' + ', '.join(f'({x}, {y})' for x, y in verts) + ']\n')
    out.append(f'def boxPolyW : Nat := {pw}\n')
    out.append('/-- The family `L4_k02_family.txt` as a table: `famTab[16 c + l]` (units `10⁻¹²`). -/')
    out.append('def famTab : List Nat := [')
    rows = []
    for c in range(16):
        rows.append('  ' + ', '.join(str(x) for x in flat[16 * c:16 * c + 16]))
    out.append(',\n'.join(rows) + ']\n')
    out.append('end SquarePacking.Bentz')
    open(A.out, 'w').write('\n'.join(out) + '\n')
    print(f'wrote {A.out}: {len(segs)} segments, {len(tab)} nonzero table entries')


if __name__ == '__main__':
    main()
