#!/usr/bin/env python3
"""gen_validsplit_data.py -- write lean/Sqpack/ValidSplitData.lean (task lean-valid-split).

For each box file (FORMAT.md v1, unit segments of the 1/5-grid, one polygon) it packs the segment weights into one
natural number, 48 bits per unit segment (o, i, j) of the grid {0..n}^2, n = 5K (o = 0: horizontal (i/5, j/5)-
((i+1)/5, j/5); o = 1: vertical (i/5, j/5)-(i/5, (j+1)/5)), field index (o (n+1) + i) (n+1) + j.  Entries of the
file on the same unit segment (the k^2 - 4 file lists 16 segments twice, one entry per family layer) are added.

  box7Packed  search/qx2_data/L4_k02_box7.txt   (Bentz.Valid7)
  box9Packed  search/qx2_data/K4_k008_box9.txt  (Bentz4.Valid9)

Nothing here is trusted by Lean: `ValidSplit7.lean` / `ValidSplit9.lean` check by kernel evaluation (`fitOK`) that
the packed table equals the family weights `Bentz.wN 7` / `ValidSplit.famW fam4 9` on the whole grid, and those are
the box files' measures (`box7Cover_measure`, `box9Cover_measure`).

Before writing, it runs a Python mirror of the Lean checks: `fitOK` is not mirrored (it needs the family code
tables), but `symOKP` and `axisOKP` are, exactly as stated in `ValidSplit.lean` (Lemma Z over every cell of
lower-left corners [0, K-1]^2, every corner, exact integers), and it prints the minimum corner mass and the number
of exactly tight corners.

usage: python3 lean/scripts/gen_validsplit_data.py [--search search] [--out lean/Sqpack/ValidSplitData.lean]
(run from s12/; deterministic)
"""
import argparse, hashlib, os, sys
from fractions import Fraction as F

BITS = 48
sys.set_int_max_str_digits(0)
BOXES = [('box7Packed', 'qx2_data/L4_k02_box7.txt', 7, 9), ('box9Packed', 'qx2_data/K4_k008_box9.txt', 9, 14)]


def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def read_box(path, K):
    tok = []
    for ln in open(path):
        tok += ln.split('#', 1)[0].split()
    it = iter(tok)
    assert next(it) == 'mixed' and next(it) == '1'
    sn, sd, D, Wd = (int(next(it)) for _ in range(4))
    assert (sn, sd, D) == (K, 1, 5), (sn, sd, D)
    npt = int(next(it)); assert npt == 0, 'points present'
    ns = int(next(it))
    segs = [tuple(int(next(it)) for _ in range(5)) for _ in range(ns)]
    npg = int(next(it)); assert npg == 1
    kk = int(next(it)); pw = int(next(it))
    verts = [(int(next(it)), int(next(it))) for _ in range(kk)]
    rest = list(it); assert not rest, rest
    return segs, verts, pw, Wd


def table(segs, n):
    T = {}
    for X0, Y0, X1, Y1, w in segs:
        if Y0 == Y1 and abs(X1 - X0) == 1:
            key = (0, min(X0, X1), Y0)
        elif X0 == X1 and abs(Y1 - Y0) == 1:
            key = (1, X0, min(Y0, Y1))
        else:
            raise ValueError(('not a unit grid segment', X0, Y0, X1, Y1))
        assert all(0 <= v <= n for v in key[1:]), key
        assert w > 0
        T[key] = T.get(key, 0) + w
    assert max(T.values()) < 2 ** BITS
    return T


def unpack(T, o, i, j):
    return T.get((o, i, j), 0)


def check_sym(T, n):
    for i in range(n):
        for j in range(n + 1):
            assert unpack(T, 0, n - 1 - i, j) == unpack(T, 0, i, j), ('reflX h', i, j)
            assert unpack(T, 1, j, i) == unpack(T, 0, i, j), ('swap', i, j)
    for i in range(n + 1):
        for j in range(n):
            assert unpack(T, 1, n - i, j) == unpack(T, 1, i, j), ('reflX v', i, j)


def lov(K, A, m):
    return max(0, min(5 * K - A, m + 5) - max(A, m))


def check_axis(T, K, A, Wd):
    n = 5 * K
    best, tight, cnt = None, 0, 0
    for p in range(5 * K - 5):
        for q in range(5 * K - 5):
            for a in (0, 1):
                for b in (0, 1):
                    s = sum(unpack(T, 0, p + a + x, q + 1 + y) for x in range(5) for y in range(5)) + \
                        sum(unpack(T, 1, p + 1 + x, q + b + y) for x in range(5) for y in range(5))
                    m = F(s, Wd) + F(lov(K, A, p + a) * lov(K, A, q + b), 25)
                    cnt += 1
                    tight += (m == 1)
                    if best is None or m < best[0]:
                        best = (m, (p, q, a, b))
    return best, tight, cnt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--search', default='search')
    ap.add_argument('--out', default='lean/Sqpack/ValidSplitData.lean')
    a = ap.parse_args()
    out = ['/-!',
           '# Packed weight tables of the box files (generated by `lean/scripts/gen_validsplit_data.py`; do not edit)',
           '',
           'One natural number per box file: 48 bits per unit segment `(o, i, j)` of the grid `{0, …, 5K}²`, field index',
           '`(o·(5K+1) + i)·(5K+1) + j` (`ValidSplit.unpackN`); entries on the same unit segment added.  Tied to the',
           "families' weights by the kernel (`fitOK` in `ValidSplit7.lean`, `ValidSplit9.lean`).", '']
    defs = []
    for name, rel, K, A in BOXES:
        path = os.path.join(a.search, rel)
        segs, verts, pw, Wd = read_box(path, K)
        n = 5 * K
        T = table(segs, n)
        check_sym(T, n)
        best, tight, cnt = check_axis(T, K, A, Wd)
        print(f'{name}: {rel} ({len(segs)} entries, {len(T)} unit segments, den {Wd}); symmetric; '
              f'Lemma Z: {cnt} corner limits, min {best[0]} at {best[1]}, {tight} exactly tight')
        assert best[0] >= 1
        P = 0
        for (o, i, j), w in T.items():
            P |= w << (BITS * ((o * (n + 1) + i) * (n + 1) + j))
        out.append(f'* `{name}`: `search/{rel}` sha256 `{sha(path)}` ({len(T)} unit segments, K = {K})')
        defs.append((name, P))
    out += ['-/', '', 'namespace SquarePacking.ValidSplit', '']
    for name, P in defs:
        out += [f'/-- The packed weights (see the module docstring). -/', f'def {name} : Nat :=', f'  {P}', '']
    out += ['end SquarePacking.ValidSplit', '']
    open(a.out, 'w').write('\n'.join(out))
    print('wrote', a.out)


if __name__ == '__main__':
    main()
