#!/usr/bin/env python3
"""Write lean/Sqpack/LebMass7Data.lean: the LEB and CAP leaves of the k^2 - 3 box run V3, as rational boxes.

Input: search/qx2_data/cert/runV3_6294052a_leaves.jsonl.gz (every leaf of run V3, box after clip_bin, kind) and
search/qx2_data/L4_k02_box7.txt (for the Python mirror of LebMass.capOK only; the Lean side reads the packed
weights of ValidSplitData.lean).  The mirror runs LebMass.lebOK / capOK exactly (Fractions) and reports the
leaves it rejects; those are not emitted (expected: none).

Run from s12/:  python3 lean/scripts/gen_lebmass_data.py   (deterministic, a few seconds)
"""
import gzip, hashlib, json, math, sys
from fractions import Fraction as F

LEAVES = 'search/qx2_data/cert/runV3_6294052a_leaves.jsonl.gz'
BOXF = 'search/qx2_data/L4_k02_box7.txt'
OUT = 'lean/Sqpack/LebMass7Data.lean'
K, A, DEN = 7, 9, 10 ** 12


def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def weights():
    """unit grid segments (o, i, j) -> summed mass (units 1/DEN): o = False horizontal (i,j)-((i+1),j)."""
    lines = [l.split('#')[0].strip() for l in open(BOXF)]
    lines = [l for l in lines if l]
    assert lines[0] == 'mixed 1' and lines[1] == '7 1' and lines[2] == '5' and int(lines[3]) == DEN
    npts, nseg = int(lines[4]), int(lines[5])
    assert npts == 0
    W = {}
    for l in lines[6:6 + nseg]:
        x0, y0, x1, y1, w = map(int, l.split())
        if y0 == y1:
            assert abs(x1 - x0) == 1
            key = (False, min(x0, x1), y0)
        else:
            assert x0 == x1 and abs(y1 - y0) == 1
            key = (True, x0, min(y0, y1))
        W[key] = W.get(key, 0) + w
    return W


def whi(u1):
    return (1 - u1 * u1 + 2 * u1) / (1 + u1 * u1) if u1 * u1 + 2 * u1 <= 1 else F(14143, 10000)


def cs(u): return (1 - u * u - 2 * u) / (1 + u * u)
def tq(u): return 2 * u / (1 - u * u)
def ct(u): return (1 - u * u) / (2 * u)


def leb_ok(B, a, b):
    x0, x1, y0, y1, u0, u1 = B
    h = whi(u1) / 2
    return a + h <= x0 and a + h <= y0 and x1 + h <= b and y1 + h <= b


def cap_ok(B, W):
    x0, x1, y0, y1, u0, u1 = B
    a = F(A, 5); h = whi(u1) / 2
    tang = u0 > 0 and u1 < 1
    if not (x1 + h <= K - a and y1 + h <= K - a): return False

    def line(d, lo, hi, wl):
        i0 = max(0, math.floor(5 * lo)); i1 = min(5 * K, max(0, math.ceil(5 * hi)))
        return all(d * DEN <= 5 * wl(i) for i in range(i0, i1))

    dy = a - y0 + h
    if not dy <= 0:
        if not a <= y0: return False
        lo, hi = x0 - h, x1 + h
        if tang:
            lo = max(lo, x0 - cs(u0) / 2 - tq(u1) * dy); hi = min(hi, x1 - cs(u1) / 2 + ct(u0) * dy)
        if not line(dy, lo, hi, lambda i: W.get((False, i, A), 0)): return False
    dx = a - x0 + h
    if not dx <= 0:
        if not a <= x0: return False
        lo, hi = y0 - h, y1 + h
        if tang:
            lo = max(lo, y0 + cs(u1) / 2 - ct(u0) * dx); hi = min(hi, y1 + cs(u0) / 2 + tq(u1) * dx)
        if not line(dx, lo, hi, lambda j: W.get((True, A, j), 0)): return False
    return True


def lit(q):
    q = F(q)
    return str(q.numerator) if q.denominator == 1 else f'{q.numerator}/{q.denominator}'


def main():
    W = weights()
    leb, cap = [], []
    with gzip.open(LEAVES, 'rt') as f:
        for line in f:
            d = json.loads(line)
            for box, kind in d.get('leaves', []):
                if kind in ('LEB', 'CAP'):
                    (leb if kind == 'LEB' else cap).append(tuple(F(v) for v in box))
    bad_leb = [B for B in leb if not leb_ok(B, F(A, 5), K - F(A, 5))]
    bad_cap = [B for B in cap if not cap_ok(B, W)]
    print(f'LEB {len(leb)} (mirror rejects {len(bad_leb)}), CAP {len(cap)} (mirror rejects {len(bad_cap)})')
    for B in bad_leb + bad_cap: print('  rejected', [str(v) for v in B])
    leb = [B for B in leb if B not in bad_leb]
    cap = [B for B in cap if B not in bad_cap]
    # CAP leaves that Lemma U alone would also certify, for the record
    print(f'CAP leaves also passing lebOK: {sum(leb_ok(B, F(A, 5), K - F(A, 5)) for B in cap)}')

    def emit(name, L, doc):
        out = [f'/-- {doc} -/', f'def {name} : List LebMass.PBox := [']
        for k, B in enumerate(L):
            out.append('  ⟨' + ', '.join(lit(v) for v in B) + '⟩' + (',' if k + 1 < len(L) else ''))
        out.append(']')
        return '\n'.join(out)

    src = f"""import Sqpack.LebMass

/-!
# Generated by `lean/scripts/gen_lebmass_data.py` -- do not edit

The LEB and CAP leaves of run V3 of `qx2_zm.py` on the `k² − 3` box file (boxes after `clip_bin`, as
recorded): `{LEAVES}` sha256 `{sha(LEAVES)}`; mirror input `{BOXF}` sha256 `{sha(BOXF)}`.
{len(leb)} LEB leaves, {len(cap)} CAP leaves.
-/

namespace SquarePacking
namespace Bentz

{emit('lebLeaves7', leb, 'The LEB (Lemma U) leaves of run V3.')}

{emit('capLeaves7', cap, 'The CAP (Lemma K) leaves of run V3.')}

end Bentz
end SquarePacking
"""
    open(OUT, 'w').write(src)
    print('wrote', OUT)


if __name__ == '__main__':
    main()
