"""The stage's citations and version, from the files they come from to what a cut records.

The builder admits `bound-citations.json` whole or stops, and builds without it where it is
absent; the version it draws is the edition `sqpack.release` pins, never read from git; the
capture records both as the page states them. What the page draws from them is measured in
Chromium by `check_animate_view` and `check_layout`; the plan the facts view draws from is
`tests/citations.test.ts`.
"""

from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

from sqpack.release import DATA_REVISION, PUBLICATION_EDITION
from workbench_tools import capture_video, delivery
from workbench_tools.build_candidate import (
    CITATIONS,
    N_MAX,
    checked_version,
    latin_face_covers,
    load_citations,
    page_version,
    same_decimal,
    stage_spelling,
)
from workbench_tools.check_animate_view import citation_steps, cited_lines

FIXTURE = Path(__file__).parent / "fixtures" / "bound-citations.json"


def _document() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _write(tmp_path: Path, document: dict[str, Any]) -> Path:
    path = tmp_path / "bound-citations.json"
    path.write_text(json.dumps(document), encoding="utf-8")
    return path


def _facts(**drawn: tuple[str | None, str]) -> dict[str, dict[str, Any]]:
    """Facts for every n whose bound line draws the fixture's own values, with `drawn`'s instead
    where it names an n: `n17=(lower, side)`."""
    facts: dict[str, dict[str, Any]] = {}
    for entry in _document()["citations"]["entries"]:
        lower, upper = entry["lower"], entry["upper"]
        low = None if lower is None else lower["value"]
        facts[str(entry["n"])] = {
            "lower": low,
            "side": upper["value"] if upper is not None else (low or "1"),
        }
    for key, (lower, side) in drawn.items():
        facts[key.removeprefix("n")] = {"lower": lower, "side": side}
    return facts


# ----------------------------------------------------------------------------- the file


def test_an_absent_file_builds_a_page_with_nothing_to_cite(tmp_path: Path) -> None:
    assert load_citations(tmp_path / "absent.json") == {"sha256": None, "entries": {}}


def test_the_file_is_carried_by_digest_with_only_the_n_that_cite_something() -> None:
    loaded = load_citations(FIXTURE)
    assert loaded["sha256"] == hashlib.sha256(FIXTURE.read_bytes()).hexdigest()
    entries = loaded["entries"]
    # 1 cites neither bound and is left out; 19 cites its upper bound alone, 16 its lower.
    assert "1" not in entries
    assert entries["19"]["lower"] is None
    assert entries["16"]["upper"] is None
    assert entries["17"]["upper"] == {
        "text": "Bidwell 1998, Squares in Squares",
        "corrects": None,
        "note": "(reported)",
        "basis": "external",
        "assurance": "reported",
    }
    # The reference is the register's own, and what this project has to say about the bound
    # is its note, never folded into the reference.
    assert entries["17"]["lower"]["text"] == "Guzhou0806 & Mira 2026, GitHub"
    assert entries["17"]["lower"]["note"] == "(confirmed T-032)"
    # Only what the stage draws reaches the page: no source key, results or value.
    assert set(entries["11"]["lower"]) == {"text", "corrects", "note", "basis", "assurance"}
    # With the frontier case record the n's bounds are held in, drawn once on the head's line.
    assert entries["17"]["record"] == "n-017"


def test_every_cited_value_is_the_number_the_bound_line_draws() -> None:
    # The fixture's values are the composite's, so it passes against facts that draw them.
    load_citations(FIXTURE, _facts(n17=("4.613046", "4.67553")))
    # The register keeps every digit it has; the stage rounds, and the two have to agree to
    # the stage's own precision.
    with pytest.raises(ValueError, match=r"n = 17 cites 4\.67553\S+ for its upper bound"):
        load_citations(FIXTURE, _facts(n17=("4.613046", "4.8")))
    with pytest.raises(ValueError, match=r"n = 17 cites 4\.613046\S* for its lower bound"):
        load_citations(FIXTURE, _facts(n17=("4.5", "4.67553")))
    # At a proved n the lower bound is the value itself, which the line draws as the side.
    with pytest.raises(ValueError, match=r"n = 5 cites 2\.707106\S+ for its lower bound"):
        load_citations(FIXTURE, _facts(n5=(None, "2.9")))


@pytest.mark.parametrize(
    ("change", "reason"),
    [
        (lambda d: d["softschema"].update(contract="other/v1"), "not a packing.squares"),
        (lambda d: d["citations"].update(generated_by="by hand"), "generated by 'by hand'"),
        (lambda d: d["citations"].update(generated_by=None), "generated by None"),
        (lambda d: d["citations"]["entries"].pop(40), "not one per n = 1..324"),
        (lambda d: d["citations"]["entries"].reverse(), "not one per n = 1..324"),
        # The reference and its note share the column's one line, so they are measured as
        # one: 60 characters of reference under a 10-character note is 71 and refused.
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(text="x" * 67),
            "78 characters",
        ),
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(text="x" * 60),
            "71 characters",
        ),
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(note="reported"),
            "not one parenthesis",
        ),
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(text=" padded"),
            "one trimmed",
        ),
        # Outside the embedded faces with no Latin-1 letter to fold to: a Polish Ł. A
        # Hungarian double acute, as in Erdős, is folded as the page loads, not refused.
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(text="Łukasiewicz 1975"),
            "faces",
        ),
        (lambda d: d["citations"]["entries"][16]["upper"].update(basis="folk"), "basis 'folk'"),
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(assurance="certain"),
            "assurance 'certain'",
        ),
        (lambda d: d["citations"]["entries"][10]["lower"].update(result="T26"), "T-NNN"),
        (
            lambda d: d["citations"]["entries"][16]["upper"].update(value=4.67553),
            "not a string",
        ),
        (lambda d: d["citations"]["entries"][16].update(upper="Bidwell"), "an object or null"),
        # Each n names its own frontier case record, and the record has to be there.
        (
            lambda d: d["citations"]["entries"][16].update(record="n-018"),
            "names the record 'n-018'",
        ),
        (
            lambda d: d["citations"]["entries"][16].update(record="n-17"),
            "names the record 'n-17'",
        ),
        (lambda d: d["citations"]["entries"][16].pop("record"), "names the record None"),
    ],
)
def test_a_file_that_breaks_the_contract_stops_the_build(
    tmp_path: Path, change: Any, reason: str
) -> None:
    document = copy.deepcopy(_document())
    change(document)
    with pytest.raises((TypeError, ValueError), match=reason):
        load_citations(_write(tmp_path, document))


def test_the_faces_and_the_decimals_are_compared_as_the_stage_draws_them() -> None:
    assert latin_face_covers("Göbel & Hämäläinen, Markót — 1979")
    assert not latin_face_covers("Erdős")
    assert same_decimal("4.822876", "4.822876")
    # The stage rounds the register's value; one unit in the shorter's last place is the same.
    assert same_decimal("4.8228757", "4.822876")
    assert same_decimal("2.707106", "2.707107")
    assert not same_decimal("4.66", "4.68")
    # A value that is not a plain decimal is not compared.
    assert same_decimal("2 + sqrt(2)/2", "2.707107")


# ----------------------------------------------------------------------------- the version


def test_the_stage_draws_the_pinned_edition_and_never_asks_git() -> None:
    # The edition the explainer and the atlas print, pinned in `sqpack.release`, so a shallow
    # checkout -- the deploy's -- builds the same page as a full one.
    assert page_version() == PUBLICATION_EDITION
    assert page_version().endswith(f"-{DATA_REVISION[:6]}")


def test_a_version_is_held_to_the_shape_the_page_admits() -> None:
    assert checked_version("v0.4.1-f5e113") == "v0.4.1-f5e113"
    # `PUBLICATION_EDITION` puts the edition's status ahead of the stamp while it has one.
    assert checked_version("draft v0.4.1-f5e113") == "draft v0.4.1-f5e113"
    for wrong in (
        "0.4.1-f5e113",
        "v0.4.1",
        "v0.4.1-HEAD",
        "v0.4.1-f5e113 ",
        "a  v0.4.1-f5e113",
    ):
        with pytest.raises(ValueError, match="not a version"):
            checked_version(wrong)


# ----------------------------------------------------------------------------- the capture


def _page(citations: dict[str, Any] | None, version: str = "v0.4.1-f5e113") -> str:
    data = {"schema": "squares.workbench.corpus/v1", "version": version, "citations": citations}
    block = json.dumps(data).replace("</", "<\\/")
    return f'<html><script id="atlas-data" type="application/json">{block}</script></html>'


def test_the_capture_reads_the_edition_the_page_states() -> None:
    digest = "c" * 64
    edition = capture_video.page_edition(_page({"sha256": digest, "entries": {}}))
    assert edition == capture_video.PageEdition(
        version="v0.4.1-f5e113", citations_sha256=digest
    )
    plain = capture_video.page_edition(_page({"sha256": None, "entries": {}}))
    assert plain.citations_sha256 is None
    with pytest.raises(SystemExit, match="no shared version"):
        capture_video.page_edition(_page(None, version=None))  # type: ignore[arg-type]
    with pytest.raises(SystemExit, match="2 data blocks"):
        capture_video.page_edition(_page(None) * 2)


def test_a_cut_asks_for_citations_only_from_a_page_that_carries_them() -> None:
    cited = capture_video.PageEdition(version="v0.4.1-f5e113", citations_sha256="c" * 64)
    plain = capture_video.PageEdition(version="v0.4.1-f5e113", citations_sha256=None)
    assert capture_video.citation_commands(citations=True, edition=cited) == [
        ["setCitations", True]
    ]
    # The plain cut says so explicitly, after the baseline, rather than trusting it.
    assert capture_video.citation_commands(citations=False, edition=plain) == [
        ["setCitations", False]
    ]
    with pytest.raises(SystemExit, match="built without a citation file"):
        capture_video.citation_commands(citations=True, edition=plain)


def test_the_mp4_carries_the_version_beside_the_page_digest(tmp_path: Path) -> None:
    arguments = delivery.encode_arguments(
        delivery.PROFILES["archive"],
        "ffmpeg",
        tmp_path / "frames",
        60,
        tmp_path / "out.mp4",
        page_sha256="ab" * 32,
        title="n = 1 to 100",
        comment="transitions are not packings.",
        version="v0.4.1-f5e113",
    )
    [comment] = [value for value in arguments if value.startswith("comment=")]
    assert comment == (
        "comment=transitions are not packings. version v0.4.1-f5e113, page sha256 " + "ab" * 32
    )
    assert delivery.metadata_comment("ab", "s.") == "s. page sha256 ab"


# ----------------------------------------------------------------------------- the checks


def test_the_handover_is_sampled_where_the_section_changes_in_each_way() -> None:
    entries = {str(entry["n"]): entry for entry in _document()["citations"]["entries"]}
    wainwright = ("Wainwright 1979, Squares in Squares", None, None)
    assert cited_lines(entries["19"]) == {"upper": wainwright}
    assert cited_lines(entries["1"]) == {}
    # The historical fixture keeps both notes; the renderer must preserve its admitted
    # vocabulary. Current-data confirmation is qualified by the citation producer.
    assert cited_lines(entries["29"])["upper"] == (
        "Schadt & Ellsworth, Squares in Squares",
        None,
        "(reported; confirmed T-009)",
    )
    # 4 is the first n cited at all; 5 gains an upper line, and 18 changes a reference.
    assert citation_steps(entries, N_MAX) == (4, 5, 18)


@pytest.mark.parametrize(("n", "earlier_result"), [(29, "T-009"), (123, "T-098")])
def test_the_current_handover_does_not_label_an_earlier_ceiling_as_confirmation(
    n: int,
    earlier_result: str,
) -> None:
    document = json.loads(CITATIONS.read_text(encoding="utf-8"))
    entry = next(row for row in document["citations"]["entries"] if row["n"] == n)
    assert earlier_result not in entry["upper"]["confirmed_by"]
    if n == 123:
        assert entry["upper"]["results"] == ["T-125"]
        assert entry["upper"]["assurance"] == "verified"
        assert entry["upper"]["confirmed_by"] == ["T-125"]
        assert cited_lines(entry)["upper"][2] == "(confirmed T-125)"
    else:
        assert earlier_result in entry["upper"]["results"]
        assert entry["upper"]["assurance"] == "reported"
        assert entry["upper"]["confirmed_by"] == []
        assert cited_lines(entry)["upper"][2] == "(reported)"


def test_a_lower_bound_names_the_published_work_it_corrects(tmp_path: Path) -> None:
    """A lower bound standing in for a published result found unsound carries
    `corrects Nagamochi 2005` on its line, measured with the reference and the note; an
    upper bound never does, and the tag names outside work, never this register's own."""
    entries = load_citations(CITATIONS)["entries"]
    assert entries["150"]["lower"]["corrects"] == "corrects Nagamochi 2005"
    assert entries["150"]["upper"]["corrects"] is None
    document = json.loads(CITATIONS.read_text(encoding="utf-8"))
    rows = {row["n"]: row for row in document["citations"]["entries"]}
    assert cited_lines(rows[150])["lower"][1] == "corrects Nagamochi 2005"

    def refused(change: dict[str, Any], match: str) -> None:
        broken = json.loads(json.dumps(document))
        target = next(row for row in broken["citations"]["entries"] if row["n"] == 150)
        for bound, value in change.items():
            target[bound] = {**target[bound], **value}
        path = tmp_path / "citations.json"
        path.write_text(json.dumps(broken), encoding="utf-8")
        with pytest.raises((ValueError, TypeError), match=match):
            load_citations(path)

    refused({"upper": {"corrects": rows[150]["lower"]["corrects"]}}, "only a lower bound")
    refused(
        {"lower": {"corrects": {**rows[150]["lower"]["corrects"], "result": "Nagamochi"}}},
        "T-NNN",
    )


def test_the_stage_spelling_folds_only_what_the_faces_cannot_draw() -> None:
    # Karakuş's cedilla is outside the stage's latin faces; Latin-1 accents, dashes and
    # quotation marks are not folded.
    assert stage_spelling("Karakuş 2026, arXiv:2609.37410") == "Karakus 2026, arXiv:2609.37410"
    dash = "\N{EN DASH}"
    assert stage_spelling(f"Erdős and Göbel {dash} “1979”") == f"Erdos and Göbel {dash} “1979”"
    assert stage_spelling("Kearney, Shiu 2002") == "Kearney, Shiu 2002"


def test_the_fold_is_made_as_the_page_loads_not_in_the_file() -> None:
    # Review A3 on jlevy/squares#305: the file keeps Karakuş's spelling for the case pages;
    # the page carries the folded line, and the animate check expects the folded line.
    document = json.loads(CITATIONS.read_text(encoding="utf-8"))
    row = next(row for row in document["citations"]["entries"] if row["n"] == 150)
    assert row["lower"]["text"].startswith("Karakuş 2026")
    assert load_citations(CITATIONS)["entries"]["150"]["lower"]["text"].startswith(
        "Karakus 2026"
    )
    assert cited_lines(row)["lower"][0].startswith("Karakus 2026")


@pytest.mark.parametrize(
    ("known", "legacy_style", "expected"),
    [(True, "muted", True), (False, "solid", False), (None, "muted", True), (True, None, True)],
)
def test_facts_display_one_dark_r_from_the_selected_packing_assessment(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    known: bool | None,
    legacy_style: str | None,
    expected: bool,
) -> None:
    from workbench_tools import build_candidate  # noqa: PLC0415

    entry = json.loads(build_candidate.COMPOSITE.read_text())["figure"]["entries"][0]
    entry["badges"] = [badge for badge in entry["badges"] if badge["glyph"] != "R"]
    if legacy_style is not None:
        entry["badges"].append(
            {"glyph": "R", "style": legacy_style, "meaning": "legacy rigidity assurance"}
        )
    if known is None:
        entry["rigidity"].pop("known_rigid", None)
    else:
        entry["rigidity"]["known_rigid"] = known
    record = {"figure": {"entries": [entry]}}
    path = tmp_path / "composite.json"
    path.write_text(json.dumps(record))
    monkeypatch.setattr(build_candidate, "COMPOSITE", path)
    monkeypatch.setattr(build_candidate, "katex_html", lambda tex: ["<math/>" for _ in tex])
    facts = build_candidate.load_facts({1: {"source": {"kind": "exact-grid"}}})
    rigid = [badge for badge in facts["1"]["badges"] if badge["glyph"] == "R"]
    assert rigid == (
        [{"glyph": "R", "style": "solid", "meaning": "known rigid"}] if expected else []
    )
    assert json.loads(path.read_text()) == record
