#!/usr/bin/env python3
"""Starter view generator and invariant checker for an experiment-loop campaign.

Copy into the campaign directory and adapt. It is deliberately small (PyYAML and
jsonschema only) so it can be read in full before being trusted.

What it does:
  * loads the artifact types: series/, explorations/, hypotheses/, and the
    experiments inside each series
  * validates every artifact against the schema it declares -- a `status: enforced`
    artifact that nothing validates is the exact failure this method exists to prevent
  * runs the whole-set invariants that per-artifact schema validation cannot see:
    duplicate ids, dangling hypothesis references, orphan experiments, stale claims,
    the cross-field verdict rules a soft schema cannot carry, the two-way
    reconciliation between ideas.md and the registry, and dead relative links
  * derives each hypothesis's status from the experiments referencing it -- status is
    never a stored field
  * renders ledger.md, which is a generated view and must never be hand-edited

Usage:
    packing-ledger render    # regenerate ledger.md
    packing-ledger check     # fail if ledger.md is stale or an invariant breaks
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from jsonschema import Draft202012Validator
from strif import atomic_output_file

from sqpack.assurance import check_experiment_semantics
from sqpack.project import ProjectLayoutError, configured_project_root, require_project_root
from sqpack.yamlio import safe_load

PROJECT_ROOT = configured_project_root()
ROOT = PROJECT_ROOT / "campaign"
LEDGER = ROOT / "ledger.md"
IDEAS = ROOT / "ideas.md"
DEFECTS = PROJECT_ROOT / "defects.yaml"
SESSION_SCHEMA = ROOT / "schemas/agent-session.schema.yaml"
AGENDA_SCHEMA = ROOT / "schemas/agenda.schema.yaml"
REQUIRED_LOGBOOK_SECTIONS = (
    "Context",
    "Outcome",
    "Run Rollup",
    "Phase History",
    "Results",
    "What Worked",
    "What Did Not Work",
    "Pipeline Changes",
    "Defects Affecting This Run",
    "Validation",
    "Claim Boundary and Next Action",
)
REQUIRED_LOGBOOK_RESULT_SECTIONS = (
    "New Scientific Results From This Run",
    "Prior Retained Results Used or Rechecked",
)
DOC_FOOTER = [
    "<!-- This document follows common-doc-guidelines.md.",
    "See github.com/jlevy/practical-prose and review guidelines before editing.",
    "-->",
]
BANNER = (
    "<!-- GENERATED by `packing-ledger render`. Do not edit by hand; edit the artifacts. -->"
)

# Terminal decisions, in the order the ledger reports them. Failures lead, because a
# ledger that leads with its wins is a ledger nobody checks the queue against.
DECISION_ORDER = [
    "rejected",
    "exhausted",
    "abandoned",
    "unresolved",
    "blocked",
    "accepted",
    "baseline",
    "superseded",
    "in-progress",
]

_SCHEMAS: dict[Path, tuple[dict, Draft202012Validator]] = {}


def validator_for(path: Path, front: dict, envelope: str) -> Draft202012Validator | None:
    """The validator an artifact declares for itself, compiled once and cached.

    An artifact saying `status: enforced` while nothing loads its schema is the
    tacit-validation failure this whole method exists to prevent, so this does not
    degrade gracefully: a declared schema that cannot be loaded is a hard error.
    """
    meta = front.get("softschema") or {}
    if meta.get("status") != "enforced":
        return None
    rel = meta.get("schema")
    if not rel:
        raise SystemExit(f"{path}: status is enforced but no schema is declared")
    schema_path = (path.parent / rel).resolve()
    if schema_path not in _SCHEMAS:
        if not schema_path.exists():
            raise SystemExit(f"{path}: declared schema not found: {rel}")
        schema = safe_load(schema_path.read_text())
        _SCHEMAS[schema_path] = (schema, Draft202012Validator(schema))
    schema, validator = _SCHEMAS[schema_path]
    declared_envelope = meta.get("envelope")
    if declared_envelope != envelope:
        raise SystemExit(
            f"{path}: softschema.envelope is {declared_envelope!r}, expected {envelope!r}"
        )
    declared_contract = meta.get("contract")
    schema_contract = schema.get("$id")
    if declared_contract != schema_contract:
        raise SystemExit(
            f"{path}: softschema.contract is {declared_contract!r}, "
            f"but schema $id is {schema_contract!r}"
        )
    return validator


def load(directory: Path, envelope: str, pattern: str = "*.md") -> list[dict]:
    """Read every softschema artifact matching a glob, validating as it goes."""
    out = []
    if not directory.exists():
        return out
    for path in sorted(directory.glob(pattern)):
        text = path.read_text()
        if not text.startswith("---\n"):
            raise SystemExit(f"{path}: no frontmatter")
        front = safe_load(text.split("---\n", 2)[1])
        payload = front.get(envelope)
        if payload is None:
            raise SystemExit(f"{path}: no '{envelope}' envelope in frontmatter")
        validator = validator_for(path, front, envelope)
        if validator is not None:
            for err in sorted(validator.iter_errors(payload), key=lambda e: list(e.path)):
                where = "/".join(str(x) for x in err.path) or "(root)"
                raise SystemExit(f"{path.name}: schema violation at {where}: {err.message}")
        payload["_path"] = path
        out.append(payload)
    return out


def workflow_order() -> list[str]:
    """Canonical workflow order, owned by the agent-session contract."""
    schema = safe_load(SESSION_SCHEMA.read_text())
    workflows = (schema.get("$defs") or {}).get("workflow", {}).get("enum")
    if not isinstance(workflows, list) or not workflows:
        raise SystemExit(f"{SESSION_SCHEMA}: no canonical $defs.workflow enum")
    return workflows


def offset_timestamp(value: object) -> dt.datetime | None:
    """Parse an ISO timestamp only when it names an absolute instant."""
    if not isinstance(value, str):
        return None
    try:
        parsed = dt.datetime.fromisoformat(value)
    except ValueError:
        return None
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        return None
    return parsed


def board_ids() -> tuple[set[str], set[str]] | None:
    """(H-ids named on the board, H-ids the board declares reserved).

    A reserved id is one held for a claim that exists somewhere upstream -- another
    campaign's register, a paper, a review -- but has not been codified here yet.
    Naming it on the board is how the two numberings stay aligned and how nobody
    reuses it; it is not a dangling reference. Declare them with a line like:

        <!-- reserved-ids: H-003 H-004 H-013 -->
    """
    if not IDEAS.exists():
        return None
    text = IDEAS.read_text()
    reserved = set()
    for line in re.findall(r"<!--\s*reserved-ids:([^>]*?)-->", text):
        reserved |= set(re.findall(r"\bH-[0-9]{3}\b", line))
    return set(re.findall(r"\bH-[0-9]{3}\b", text)), reserved


def naming(
    series,
    explorations,
    hypotheses,
    experiments,
    sessions,
    *,
    agendas,
    logbook_entries,
) -> list[str]:
    """Ids in filenames agree with ids in frontmatter, and slugs are kebab-case."""
    problems = []
    for items in (
        series,
        explorations,
        hypotheses,
        experiments,
        sessions,
        agendas,
        logbook_entries,
    ):
        for item in items:
            path = item["_path"]
            # A series is named by its directory; everything else by its own filename.
            stem = path.parent.name if path.name == "README.md" else path.stem
            claimed = item["id"]
            if not stem.startswith(claimed + "-"):
                problems.append(f"{stem}: name does not start with its id {claimed!r}")
                continue
            slug = stem[len(claimed) + 1 :]
            if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", slug):
                problems.append(f"{stem}: slug {slug!r} is not kebab-case")
    return problems


def _counts(values) -> dict[str, int]:
    """Return only observed values, matching the sparse count objects in the schema."""
    return {str(key): count for key, count in Counter(values).items() if count}


def check_logbook_entries(logbook_entries, sessions, experiments) -> list[str]:
    """Reconcile reader-facing run summaries with their authoritative records."""
    problems = []
    sessions_by_id = {session["id"]: session for session in sessions}
    experiments_by_id = {experiment["id"]: experiment for experiment in experiments}
    defect_ids = {
        defect["id"] for defect in safe_load(DEFECTS.read_text(encoding="utf-8"))["defects"]
    }
    summaries_by_session: dict[str, list[str]] = defaultdict(list)

    for entry in logbook_entries:
        name = entry["_path"].name
        source_ids = entry["source_sessions"]
        for session_id in source_ids:
            summaries_by_session[session_id].append(entry["id"])
        unknown_sessions = sorted(set(source_ids) - sessions_by_id.keys())
        if unknown_sessions:
            problems.append(f"{name}: unknown source sessions {unknown_sessions}")
            continue
        source_sessions = [sessions_by_id[session_id] for session_id in source_ids]
        active_sessions = [
            session["id"]
            for session in source_sessions
            if session.get("status") == "in_progress"
        ]
        if active_sessions:
            problems.append(f"{name}: source sessions are still active {active_sessions}")
        source_beads = {session.get("primary_bead") for session in source_sessions}
        if source_beads != {entry["primary_bead"]}:
            problems.append(
                f"{name}: primary_bead is {entry['primary_bead']!r}, "
                f"but source sessions use {sorted(source_beads)}"
            )

        phases = [
            phase for session in source_sessions for phase in session.get("workflow_phases", [])
        ]
        delegations = [
            delegation
            for session in source_sessions
            for delegation in session.get("delegations", [])
        ]
        rollup = entry["rollup"]
        expected = {
            "session_count": len(source_sessions),
            "phase_count": len(phases),
            "workflow_counts": _counts(phase.get("workflow") for phase in phases),
            "phase_status_counts": _counts(phase.get("status") for phase in phases),
            "focus_counts": _counts(phase.get("focus") for phase in phases),
            "clock_role_counts": _counts(phase.get("clock_role") for phase in phases),
            "delegation_count": len(delegations),
            "delegation_status_counts": _counts(
                delegation.get("status") for delegation in delegations
            ),
        }
        for field, value in expected.items():
            if rollup.get(field) != value:
                problems.append(
                    f"{name}: rollup.{field} is {rollup.get(field)!r}, expected {value!r}"
                )

        timebox = entry["timebox"]
        planned_minutes = timebox["cycle_minutes"] * timebox["planned_cycle_slots"]
        if abs(planned_minutes - timebox["target_wall_minutes"]) > 1e-9:
            problems.append(
                f"{name}: planned cycle slots total {planned_minutes:g} minutes, "
                f"not target_wall_minutes {timebox['target_wall_minutes']:g}"
            )

        declared_decisions = []
        seen_new_round_results = set()
        for result in entry["new_round_results"]:
            experiment_id = result["id"]
            if experiment_id in seen_new_round_results:
                problems.append(f"{name}: repeats new round result {experiment_id}")
                continue
            seen_new_round_results.add(experiment_id)
            declared_decisions.append(result["decision"])
            experiment = experiments_by_id.get(experiment_id)
            if experiment is None:
                problems.append(f"{name}: references unknown experiment {experiment_id}")
                continue
            actual_decision = (experiment.get("verdict") or {}).get("decision")
            if result["decision"] != actual_decision:
                problems.append(
                    f"{name}: {experiment_id} decision is {result['decision']!r}, "
                    f"expected {actual_decision!r}"
                )
        decision_counts = _counts(declared_decisions)
        if rollup["new_round_decision_counts"] != decision_counts:
            problems.append(
                f"{name}: rollup.new_round_decision_counts is "
                f"{rollup['new_round_decision_counts']!r}, expected {decision_counts!r}"
            )

        seen_prior_results = set()
        for result in entry["prior_retained_results"]:
            experiment_id = result["id"]
            if experiment_id in seen_prior_results:
                problems.append(f"{name}: repeats prior result {experiment_id}")
                continue
            seen_prior_results.add(experiment_id)
            if experiment_id in seen_new_round_results:
                problems.append(
                    f"{name}: {experiment_id} is both a new round result and a prior result"
                )
            if experiment_id not in experiments_by_id:
                problems.append(f"{name}: references unknown prior result {experiment_id}")
            if result["use"] == "rechecked" and not result.get("recheck_evidence"):
                problems.append(
                    f"{name}: rechecked prior result {experiment_id} has no recheck_evidence"
                )

        defects = entry["defects"]
        new_defects = set(defects["opened_in_run"])
        relevant_defects = set(defects["preexisting_relevant"])
        overlap = sorted(new_defects & relevant_defects)
        if overlap:
            problems.append(f"{name}: defect ids are both new and relevant {overlap}")
        unknown_defects = sorted((new_defects | relevant_defects) - defect_ids)
        if unknown_defects:
            problems.append(f"{name}: references unknown defects {unknown_defects}")

        change_names = [change["name"] for change in entry["pipeline_changes"]]
        duplicate_changes = sorted(
            name for name, count in Counter(change_names).items() if count > 1
        )
        if duplicate_changes:
            problems.append(f"{name}: duplicate pipeline changes {duplicate_changes}")
        for change in entry["pipeline_changes"]:
            for relative_path in change["paths"]:
                if not (PROJECT_ROOT.parent / relative_path).exists():
                    problems.append(
                        f"{name}: pipeline change {change['name']} references missing "
                        f"path {relative_path}"
                    )

        body = entry["_path"].read_text(encoding="utf-8").split("---\n", 2)[2]
        for section in REQUIRED_LOGBOOK_SECTIONS:
            if body.count(f"## {section}\n") != 1:
                problems.append(f"{name}: needs exactly one '## {section}' section")
        for section in REQUIRED_LOGBOOK_RESULT_SECTIONS:
            if body.count(f"### {section}\n") != 1:
                problems.append(f"{name}: needs exactly one '### {section}' subsection")

    for session_id, entry_ids in sorted(summaries_by_session.items()):
        if len(entry_ids) > 1:
            problems.append(f"{session_id}: summarized by multiple logbook entries {entry_ids}")
    return problems


def dead_links() -> list[str]:
    """Relative Markdown links in the campaign that point at nothing.

    Renaming an artifact leaves prose pointing at the old path, and neither schema
    validation nor the id checks can see it -- a link is not an id. Found the
    expensive way: a series rename left four dead links in a commit that passed
    every other check.
    """
    problems = []
    for path in sorted(ROOT.rglob("*.md")):
        for target in re.findall(r"\]\(([^)#][^)]*)\)", path.read_text()):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            resolved = (path.parent / target.split("#")[0]).resolve()
            if not resolved.exists():
                problems.append(f"{path.relative_to(ROOT)}: dead link -> {target}")
    return problems


def check(
    series,
    explorations,
    hypotheses,
    experiments,
    sessions,
    *,
    agendas,
    now: dt.datetime,
    logbook_entries=None,
) -> list[str]:
    """Whole-set invariants. Per-artifact validation cannot see any of these."""
    logbook_entries = logbook_entries or []
    problems = []

    for label, items in (
        ("series", series),
        ("exploration", explorations),
        ("hypothesis", hypotheses),
        ("experiment", experiments),
        ("session", sessions),
        ("agenda", agendas),
        ("logbook entry", logbook_entries),
    ):
        seen = defaultdict(list)
        for item in items:
            seen[item["id"]].append(item["_path"].name)
        for artifact_id, paths in seen.items():
            if len(paths) > 1:
                problems.append(f"duplicate {label} id {artifact_id}: {', '.join(paths)}")

    # Every round names a series that exists, and only one series is open.
    series_ids = {s["id"] for s in series}
    for experiment in experiments:
        if experiment.get("series") not in series_ids:
            problems.append(
                f"{experiment['_path'].name}: unknown series {experiment.get('series')}"
            )
    open_series = [s["id"] for s in series if s.get("status") == "open"]
    if len(open_series) > 1:
        problems.append(f"more than one open series: {', '.join(open_series)}")

    known = {h["id"] for h in hypotheses}
    for experiment in experiments:
        referenced = experiment.get("hypotheses") or []
        if not referenced:
            problems.append(f"{experiment['_path'].name}: references no hypothesis")
        for hypothesis_id in referenced:
            if hypothesis_id not in known:
                problems.append(
                    f"{experiment['_path'].name}: references unknown {hypothesis_id}"
                )

    for agenda in agendas:
        name = agenda["_path"].name
        items = agenda["items"]
        item_ids = [item["id"] for item in items]
        duplicate_items = {item_id for item_id in item_ids if item_ids.count(item_id) > 1}
        if duplicate_items:
            problems.append(f"{name}: duplicate item ids: {sorted(duplicate_items)}")
        known_items = set(item_ids)
        state_by_id = {item["id"]: item["state"] for item in items}
        for item in items:
            item_id = item["id"]
            unknown_hypotheses = set(item.get("hypotheses") or []) - known
            if unknown_hypotheses:
                problems.append(
                    f"{name}: {item_id} references unknown hypotheses "
                    f"{sorted(unknown_hypotheses)}"
                )
            dependencies = set(item["depends_on"])
            unknown_dependencies = dependencies - known_items
            if unknown_dependencies:
                problems.append(
                    f"{name}: {item_id} depends on unknown items {sorted(unknown_dependencies)}"
                )
            if item_id in dependencies:
                problems.append(f"{name}: {item_id} depends on itself")
            if item["state"] == "ready":
                incomplete = sorted(
                    dependency
                    for dependency in dependencies
                    if state_by_id.get(dependency) != "complete"
                )
                if incomplete:
                    problems.append(
                        f"{name}: {item_id} is ready with incomplete dependencies {incomplete}"
                    )
            if item["state"] == "complete" and not item.get("artifacts"):
                problems.append(f"{name}: {item_id} is complete without retained artifacts")

    # One bead may back several commitments -- that is how a lane is carried across
    # agendas, and `think-1s0h` has run from BC-010 to BC-029 to BC-037 that way. Several
    # COMPLETE ones are the useful part, a record of successive bounded attempts. Two
    # READY ones are not: they give a runner asking "what do I pick up?" more than one
    # answer, with nothing to arbitrate. Blocked pairs are left alone because a
    # dependency chain is a legitimate reason for two live commitments on one bead.
    ready_by_bead: dict[str, list[str]] = {}
    for agenda in agendas:
        for item in agenda["items"]:
            if item["state"] == "ready":
                where = f"{item['id']} ({agenda['_path'].name})"
                ready_by_bead.setdefault(item["bead"], []).append(where)
    for bead, places in sorted(ready_by_bead.items()):
        if len(places) > 1:
            problems.append(
                f"{bead}: backs more than one ready commitment: {', '.join(sorted(places))}"
            )

    # The agenda schema duplicates the session schema's workflow list rather than
    # referencing it, because a cross-file `$ref` does not resolve for these loaders.
    # A duplicated enum that nothing compares is how a list quietly grows two versions.
    session_workflows = set(
        safe_load(SESSION_SCHEMA.read_text(encoding="utf-8"))["$defs"]["workflow"]["enum"]
    )
    agenda_workflows_node = (
        safe_load(AGENDA_SCHEMA.read_text(encoding="utf-8"))["properties"]["items"]["items"][
            "properties"
        ]
        .get("workflows", {})
        .get("items", {})
    )
    agenda_workflows = set(agenda_workflows_node.get("enum") or ())
    if agenda_workflows and agenda_workflows != session_workflows:
        problems.append(
            "agenda.schema.yaml: its duplicated workflow enum has drifted from "
            f"agent-session.schema.yaml: {sorted(agenda_workflows ^ session_workflows)}"
        )

    # A phase may now name the commitment it serves. Where it does, the link is checked
    # rather than left as prose a regex has to recover.
    known_commitments = {item["id"] for agenda in agendas for item in agenda["items"]}
    for session in sessions:
        name = session["_path"].name
        for number, phase in enumerate(session.get("workflow_phases") or [], start=1):
            commitment = phase.get("commitment")
            if commitment and commitment not in known_commitments:
                problems.append(
                    f"{name}: phase {number} serves unknown commitment {commitment}"
                )

    reports = {x["id"] for x in explorations}
    for hypothesis in hypotheses:
        for report_id in hypothesis.get("derived_from") or []:
            if report_id not in reports:
                problems.append(f"{hypothesis['_path'].name}: derived_from unknown {report_id}")

    # The board is hand-written, so it is reconciled rather than regenerated. Both
    # directions matter: a board ahead of the registry points at nothing, and a
    # hypothesis missing from the board is invisible to the next agent that arrives.
    board = board_ids()
    if board is None:
        problems.append("no ideas.md: the campaign has no orientation page")
    else:
        on_board, reserved = board
        for hypothesis_id in sorted(on_board - known - reserved):
            problems.append(f"ideas.md: names {hypothesis_id}, which is not in the registry")
        for hypothesis_id in sorted(known - on_board):
            problems.append(f"ideas.md: does not mention {hypothesis_id}")
        # A reservation that has been fulfilled is stale and must be retired, or the
        # board keeps claiming an id is unwritten after it has been written.
        for hypothesis_id in sorted(reserved & known):
            problems.append(
                f"ideas.md: {hypothesis_id} is declared reserved but is now in the registry"
            )
        # Reserved ids are exempt from the dangling-reference check, which means a
        # LINK to one would otherwise pass silently -- the board would assert a
        # reserved id is registered. Exempt from existence, not from being linked.
        linked = set(re.findall(r"\[(H-[0-9]{3})\]\(", IDEAS.read_text()))
        for hypothesis_id in sorted(linked & reserved):
            problems.append(
                f"ideas.md: {hypothesis_id} is reserved, so it must not be a link target"
            )

    # Cross-field verdict rules. These would be `allOf` conditionals in the schema,
    # except that softschema 0.6.2 refuses any allOf object composition under
    # `status: enforced` -- see the note in experiment.schema.yaml. They live here.
    for experiment in experiments:
        name = experiment["_path"].name
        problems.extend(
            f"{name}: {problem}" for problem in check_experiment_semantics(experiment)
        )
        verdict = experiment.get("verdict") or {}
        decision = verdict.get("decision")
        instance = experiment.get("instance") or {}
        role = instance.get("role")
        point = instance.get("point")
        if role in {"positive_control", "negative_control"}:
            if isinstance(point, bool) or not isinstance(point, int):
                problems.append(f"{name}: control role {role} has invalid instance point")
                continue
            frontier_path = ROOT.parent / "frontier" / f"n-{point:03d}.md"
            proved = False
            if frontier_path.exists():
                text = frontier_path.read_text()
                if text.startswith("---\n"):
                    packing = safe_load(text.split("---\n", 2)[1]).get("packing") or {}
                    proved = packing.get("status") == "proved"
            if not proved:
                problems.append(
                    f"{name}: control role {role} requires a proved instance; "
                    f"frontier n={point} is open or missing"
                )
        if decision == "abandoned":
            for field in ("budget_spent", "best_reached", "reopen_when"):
                if not verdict.get(field):
                    problems.append(f"{name}: abandoned without {field}")
        if decision == "exhausted" and not verdict.get("reopen_when"):
            problems.append(f"{name}: exhausted without reopen_when")
        if decision == "superseded" and not verdict.get("superseded_by"):
            problems.append(f"{name}: superseded without superseded_by")

        # A round declares one instance. If its results cite a standing best from a
        # DIFFERENT cell, it measured a sweep and recorded a cell, so the ledger reports
        # swept cells as unfilled and the next runner re-runs them. Made twice before it
        # was checked (defects D-010, D-017).
        point = str(point or "")
        declared = set(experiment.get("known_defects") or [])
        for result in [] if declared & {"D-010", "D-017"} else experiment.get("results") or []:
            source = result.get("standing_best_source") or ""
            for cited in re.findall(r"\bn-0*(\d+)", source):
                if cited.lstrip("0") != point:
                    problems.append(
                        f"{name}: declares instance n={point} but a result cites "
                        f"n={cited.lstrip('0')}; a sweep must be one round per cell"
                    )

        # Effort is required on every terminal round. A record that cannot say what a
        # round cost, or why it stopped, can neither price the next one nor be resumed.
        if decision != "in-progress":
            if not experiment.get("results"):
                problems.append(f"{name}: terminal round without results")
            effort = experiment.get("effort") or {}
            if not effort:
                problems.append(f"{name}: terminal round without an effort block")
            else:
                if "wall_seconds" not in effort:
                    problems.append(f"{name}: terminal round without effort.wall_seconds")
                stopped = effort.get("stopped_by")
                if stopped == "timebox" and not effort.get("timebox"):
                    problems.append(f"{name}: stopped_by timebox but no timebox was declared")
                # Stopping on the clock leaves the question open, so the round must say
                # where a successor picks it up, or the spent budget is lost.
                if stopped == "timebox" and not verdict.get("resume_from"):
                    problems.append(f"{name}: stopped on the clock without verdict.resume_from")
                if stopped == "criterion" and decision == "abandoned":
                    problems.append(
                        f"{name}: abandoned, but stopped_by says the criterion decided it"
                    )
        if decision != "in-progress":
            if experiment.get("lease"):
                problems.append(f"{name}: carries a lease but is not in-progress")
            continue
        expires = (experiment.get("lease") or {}).get("expires")
        if not expires:
            problems.append(f"{name}: in-progress without a lease")
        # Leases may be written with or without a timezone; `now` here is naive UTC.
        # Interpret a naive lease as UTC and convert an aware lease before dropping its
        # timezone. Merely removing an offset changes the instant and can expire a live
        # west-of-UTC lease several hours early.
        else:
            parsed_expiry = dt.datetime.fromisoformat(expires)
            if parsed_expiry.tzinfo is not None:
                parsed_expiry = parsed_expiry.astimezone(dt.UTC).replace(tzinfo=None)
            if parsed_expiry < now:
                problems.append(f"{name}: STALE CLAIM, lease expired {expires}")

    for session in sessions:
        name = session["_path"].name
        status = session.get("status")
        reason = session.get("stop_reason")
        if status == "in_progress" and reason is not None:
            problems.append(f"{name}: in-progress session has stop_reason")
        if status in {"completed", "stopped"} and not reason:
            problems.append(f"{name}: terminal session has no stop_reason")

        session_started = offset_timestamp(session.get("started_at"))
        session_deadline = offset_timestamp(session.get("deadline_at"))
        if status == "in_progress":
            if session_started is None:
                problems.append(f"{name}: in-progress session needs an offset-aware started_at")
            if session_deadline is None:
                problems.append(
                    f"{name}: in-progress session needs an offset-aware deadline_at"
                )
        if session.get("started_at") is not None and session_started is None:
            problems.append(f"{name}: started_at is not an offset-aware ISO timestamp")
        if session.get("deadline_at") is not None and session_deadline is None:
            problems.append(f"{name}: deadline_at is not an offset-aware ISO timestamp")
        if session_started is not None and session_deadline is not None:
            if session_deadline <= session_started:
                problems.append(f"{name}: deadline_at is not after started_at")
            elif (session_deadline - session_started).total_seconds() > (
                session.get("budget", {}).get("wall_minutes", 0) * 60
            ):
                problems.append(f"{name}: deadline_at exceeds budget.wall_minutes")
        clocked = session_started is not None and session_deadline is not None
        current = now if now.tzinfo is not None else now.replace(tzinfo=dt.UTC)
        if (
            status == "in_progress"
            and clocked
            and session_deadline is not None
            and session_deadline <= current
        ):
            problems.append(f"{name}: in-progress session deadline_at has passed")

        phases = session.get("workflow_phases") or []
        if not phases:
            problems.append(f"{name}: session has no workflow phase history")
        else:
            if phases[0].get("entered_by") != "session_start":
                problems.append(
                    f"{name}: first workflow phase was not entered at session_start"
                )
            if phases[0].get("switch_reason") is not None:
                problems.append(f"{name}: first workflow phase has a switch_reason")
            for index, phase in enumerate(phases):
                number = index + 1
                phase_status = phase.get("status")
                phase_reason = phase.get("stop_reason")
                recording = phase.get("recording")
                clock_role = phase.get("clock_role")
                if clocked and recording != "contemporaneous":
                    problems.append(
                        f"{name}: clocked workflow phase {number} must be contemporaneous"
                    )
                if index and phase.get("entered_by") == "session_start":
                    problems.append(f"{name}: workflow phase {number} reuses session_start")
                if index and not phase.get("switch_reason"):
                    problems.append(f"{name}: workflow phase {number} has no switch_reason")
                if index and all(
                    phase.get(field) == phases[index - 1].get(field)
                    for field in ("workflow", "focus", "objective")
                ):
                    problems.append(
                        f"{name}: workflow phase {number} changes neither workflow, "
                        "focus, nor objective"
                    )
                if recording == "retrospective" and phase_status == "in_progress":
                    problems.append(
                        f"{name}: active workflow phase {number} is not "
                        "contemporaneously recorded"
                    )
                if recording == "contemporaneous":
                    if clocked and clock_role is None:
                        problems.append(
                            f"{name}: clocked contemporaneous workflow phase {number} "
                            "has no clock_role"
                        )
                    for field in (
                        "budget_minutes",
                        "started_at",
                        "deadline_at",
                        "expected_output",
                        "validation_command",
                        "kill_condition",
                        "fallback",
                    ):
                        value = phase.get(field)
                        if value is None or (isinstance(value, str) and not value.strip()):
                            problems.append(
                                f"{name}: contemporaneous workflow phase {number} "
                                f"has no {field}"
                            )
                    started = offset_timestamp(phase.get("started_at"))
                    deadline = offset_timestamp(phase.get("deadline_at"))
                    if phase.get("started_at") is not None and started is None:
                        problems.append(
                            f"{name}: workflow phase {number} started_at is not an "
                            "offset-aware ISO timestamp"
                        )
                    if phase.get("deadline_at") is not None and deadline is None:
                        problems.append(
                            f"{name}: workflow phase {number} deadline_at is not an "
                            "offset-aware ISO timestamp"
                        )
                    if started is not None and deadline is not None and deadline <= started:
                        problems.append(
                            f"{name}: workflow phase {number} deadline_at is not "
                            "after started_at"
                        )
                    if (
                        phase_status == "in_progress"
                        and deadline is not None
                        and deadline <= current
                    ):
                        problems.append(
                            f"{name}: in-progress workflow phase {number} deadline_at "
                            "has passed"
                        )
                    phase_budget = phase.get("budget_minutes")
                    if (
                        started is not None
                        and deadline is not None
                        and phase_budget is not None
                        and (deadline - started).total_seconds() > phase_budget * 60
                    ):
                        problems.append(
                            f"{name}: contemporaneous workflow phase {number} "
                            "deadline_at exceeds budget_minutes"
                        )
                    if (
                        session_started is not None
                        and started is not None
                        and started < session_started
                    ):
                        problems.append(
                            f"{name}: contemporaneous workflow phase {number} "
                            "starts before the session"
                        )
                    if (
                        session_deadline is not None
                        and deadline is not None
                        and deadline > session_deadline
                    ):
                        problems.append(
                            f"{name}: contemporaneous workflow phase {number} "
                            "deadline_at exceeds session deadline"
                        )
                    reserve_start = (
                        session_deadline
                        - dt.timedelta(
                            minutes=session.get("budget", {}).get("finalization_minutes", 0)
                        )
                        if session_deadline is not None
                        else None
                    )
                    if (
                        clock_role == "work"
                        and reserve_start is not None
                        and deadline is not None
                        and deadline > reserve_start
                    ):
                        problems.append(
                            f"{name}: workflow phase {number} work deadline enters "
                            "finalization reserve"
                        )
                    if clock_role == "finalization":
                        if index != len(phases) - 1:
                            problems.append(
                                f"{name}: finalization workflow phase {number} must be final"
                            )
                        if (
                            reserve_start is not None
                            and started is not None
                            and started < reserve_start
                        ):
                            problems.append(
                                f"{name}: finalization workflow phase {number} starts "
                                "before reserve"
                            )
                if phase_status == "in_progress" and phase_reason is not None:
                    problems.append(
                        f"{name}: in-progress workflow phase {number} has stop_reason"
                    )
                if phase_status in {"completed", "stopped"}:
                    if not phase_reason:
                        problems.append(
                            f"{name}: terminal workflow phase {number} has no stop_reason"
                        )
                    if not phase.get("outcome"):
                        problems.append(
                            f"{name}: terminal workflow phase {number} has no outcome"
                        )
                    if not phase.get("evidence"):
                        problems.append(
                            f"{name}: terminal workflow phase {number} has no evidence"
                        )
                if phase_status == "in_progress" and index != len(phases) - 1:
                    problems.append(f"{name}: only the final workflow phase may be in_progress")
            if phases[-1].get("status") != status:
                problems.append(f"{name}: session status does not match final workflow phase")
            if status in {"completed", "stopped"} and session.get("progress", {}).get(
                "after"
            ) in (None, ""):
                problems.append(f"{name}: terminal session needs nonempty progress.after")
            contemporaneous = [
                phase for phase in phases if phase.get("recording") == "contemporaneous"
            ]
            max_cycles = session.get("budget", {}).get("max_cycles")
            if max_cycles is not None and len(contemporaneous) > max_cycles:
                problems.append(
                    f"{name}: contemporaneous workflow phases exceed budget.max_cycles"
                )
        for delegation in session.get("delegations") or []:
            delegation_status = delegation.get("status")
            delegation_recording = delegation.get("recording")
            if clocked and delegation_recording is None:
                problems.append(f"{name}: clocked delegation has no recording")
            if (
                delegation_status in {"queued", "in_progress"}
                and delegation_recording != "contemporaneous"
            ):
                problems.append(f"{name}: active delegation must be contemporaneous")
            elapsed = delegation.get("elapsed_seconds")
            quality = delegation.get("elapsed_quality")
            if quality is None and elapsed is not None:
                problems.append(f"{name}: delegation elapsed value has no quality")
            elif quality is not None and (quality == "unavailable") != (elapsed is None):
                problems.append(f"{name}: delegation elapsed value and quality disagree")
            if delegation_status in {"queued", "in_progress"}:
                for field in (
                    "phase",
                    "budget_minutes",
                    "expected_output",
                    "validation_command",
                    "kill_condition",
                    "fallback",
                    "write_scope",
                    "excluded_commands",
                ):
                    value = delegation.get(field)
                    if value is None or (isinstance(value, (str, list)) and not value):
                        problems.append(
                            f"{name}: {delegation_status} delegation has no {field}"
                        )
                validation_command = delegation.get("validation_command") or ""
                if "uv run" in validation_command and "--frozen" not in validation_command:
                    problems.append(
                        f"{name}: {delegation_status} delegation has an unfrozen uv command"
                    )
                phase_number = delegation.get("phase")
                if isinstance(phase_number, int) and not 1 <= phase_number <= len(phases):
                    problems.append(
                        f"{name}: {delegation_status} delegation references unknown "
                        f"workflow phase {phase_number}"
                    )
            delegation_started = offset_timestamp(delegation.get("started_at"))
            delegation_deadline = offset_timestamp(delegation.get("deadline_at"))
            if delegation_status == "in_progress" and (
                delegation_started is None or delegation_deadline is None
            ):
                problems.append(
                    f"{name}: in-progress delegation needs offset-aware started_at "
                    "and deadline_at"
                )
            if (
                delegation_status == "in_progress"
                and delegation_deadline is not None
                and delegation_deadline <= current
            ):
                problems.append(f"{name}: in-progress delegation deadline_at has passed")
            if delegation.get("started_at") is not None and delegation_started is None:
                problems.append(f"{name}: delegation started_at is not offset-aware")
            if delegation.get("deadline_at") is not None and delegation_deadline is None:
                problems.append(f"{name}: delegation deadline_at is not offset-aware")
            if delegation_started is not None and delegation_deadline is not None:
                if delegation_deadline <= delegation_started:
                    problems.append(f"{name}: delegation deadline_at is not after started_at")
                delegation_budget = delegation.get("budget_minutes")
                if (
                    delegation_budget is not None
                    and (delegation_deadline - delegation_started).total_seconds()
                    > delegation_budget * 60
                ):
                    problems.append(f"{name}: delegation deadline_at exceeds budget_minutes")
                if session_deadline is not None and delegation_deadline > session_deadline:
                    problems.append(f"{name}: delegation deadline_at exceeds session deadline")
                phase_number = delegation.get("phase")
                if isinstance(phase_number, int) and 1 <= phase_number <= len(phases):
                    phase_deadline = offset_timestamp(
                        phases[phase_number - 1].get("deadline_at")
                    )
                    if phase_deadline is not None and delegation_deadline > phase_deadline:
                        problems.append(
                            f"{name}: delegation deadline_at exceeds workflow phase "
                            f"{phase_number} deadline"
                        )
            if delegation_status in {"completed", "blocked", "canceled"} and (
                delegation_recording == "contemporaneous" or clocked
            ):
                for field in (
                    "phase",
                    "outcome",
                    "evidence",
                    "files",
                    "checks",
                    "uncertainty",
                    "elapsed_quality",
                ):
                    value = delegation.get(field)
                    missing = value is None or (
                        field not in {"files", "checks"}
                        and isinstance(value, (str, list))
                        and not value
                    )
                    if missing:
                        problems.append(f"{name}: terminal delegation has no {field}")
                phase_number = delegation.get("phase")
                if isinstance(phase_number, int) and not 1 <= phase_number <= len(phases):
                    problems.append(
                        f"{name}: terminal delegation references unknown workflow "
                        f"phase {phase_number}"
                    )

    problems += check_logbook_entries(logbook_entries, sessions, experiments)
    problems += naming(
        series,
        explorations,
        hypotheses,
        experiments,
        sessions,
        agendas=agendas,
        logbook_entries=logbook_entries,
    )
    problems += dead_links()

    return problems


def status_of(hypothesis: dict, rounds: list[dict]) -> str:
    """Derived, never stored. Precedence matters: a later accept outranks a reject."""
    if hypothesis.get("kind") == "open_question":
        return "open question"
    if not rounds:
        if not hypothesis.get("instrument_ready", True) or not hypothesis.get("instrument"):
            return "blocked"
        return "open"
    decisions = {r.get("verdict", {}).get("decision") for r in rounds}
    # `rejected` outranks `accepted` on purpose. A claim stated over a sweep is
    # universally quantified, so one failing cell refutes it however many cells pass --
    # and taking the optimistic reading would let a registry report a refuted claim as
    # confirmed. A claim that is genuinely per-cell belongs in the registry as separate
    # hypotheses, which is the honest way to say so.
    for decision in ("rejected", "exhausted", "accepted", "abandoned", "blocked", "unresolved"):
        if decision in decisions:
            return {"accepted": "confirmed", "rejected": "refuted"}.get(decision, decision)
    if decisions == {"in-progress"}:
        return "running"
    return "measured"


def sweep_coverage(hypothesis: dict, rounds: list[dict]) -> str:
    """Which declared sweep cells are filled. Empty cells are queue items."""
    sweep = hypothesis.get("sweep")
    if not sweep:
        return ""
    done = {
        str((r.get("instance") or {}).get("point"))
        for r in rounds
        if r.get("verdict", {}).get("decision") != "in-progress"
    }
    cells = [f"{p}{'*' if str(p) in done else ''}" for p in sweep["points"]]
    return f"{sweep['axis']}: {' '.join(cells)}"


def effort_of(rounds: list[dict]) -> tuple[float, float]:
    """Cumulative (agent_minutes, wall_seconds) over a set of rounds."""
    minutes = sum((r.get("effort") or {}).get("agent_minutes") or 0 for r in rounds)
    seconds = sum((r.get("effort") or {}).get("wall_seconds") or 0 for r in rounds)
    return minutes, seconds


def spent(rounds: list[dict]) -> str:
    """How much has gone into a claim so far, in the two units that decide what next."""
    minutes, seconds = effort_of(rounds)
    if not minutes and not seconds:
        return ""
    parts = []
    if minutes:
        parts.append(f"{minutes:g}m agent")
    if seconds:
        parts.append(f"{seconds / 60:.1f}m wall" if seconds >= 60 else f"{seconds:.0f}s wall")
    return " + ".join(parts)


def render(
    series,
    explorations,
    hypotheses,
    experiments,
    sessions,
    *,
    agendas,
    logbook_entries=None,
) -> str:
    logbook_entries = logbook_entries or []
    by_hypothesis = defaultdict(list)
    for experiment in experiments:
        for hypothesis_id in experiment.get("hypotheses") or []:
            by_hypothesis[hypothesis_id].append(experiment)

    lines = [BANNER, "", "# Experiment ledger", ""]

    if logbook_entries:
        lines += [
            "## Research loop logbook",
            "",
            (
                "Each entry summarizes one user-level research window. Cycle slots are "
                "wall-clock units; phases are recorded changes of purpose or focus."
            ),
            "",
            (
                "| run | date | status | cycle slots | sessions | phases | workflows "
                "| new-round verdicts | prior retained results | next action |"
            ),
            "| --- | --- | --- | ---: | ---: | ---: | --- | --- | ---: | --- |",
        ]
        for entry in sorted(logbook_entries, key=lambda item: item["id"]):
            path = entry["_path"].relative_to(ROOT).as_posix()
            timebox = entry["timebox"]
            rollup = entry["rollup"]
            workflows = ", ".join(
                f"`{workflow}` {count}" for workflow, count in rollup["workflow_counts"].items()
            )
            decisions = ", ".join(
                f"{decision} {count}"
                for decision, count in rollup["new_round_decision_counts"].items()
            )
            next_action = entry["next_action"].replace("\n", " ").strip()
            lines.append(
                f"| [{entry['id']}]({path}) | {entry['date']} | {entry['status']} "
                f"| {timebox['planned_cycle_slots']} x {timebox['cycle_minutes']:g}m "
                f"| {rollup['session_count']} | {rollup['phase_count']} | {workflows} "
                f"| {decisions} | {len(entry['prior_retained_results'])} | {next_action} |"
            )
        lines.append("")

    if sessions:
        lines += [
            "## Agent sessions",
            "",
            (
                "| id | status | recording | entry | current | count "
                "| primary bead | next action |"
            ),
            "| --- | --- | --- | --- | --- | ---: | --- | --- |",
        ]
        for session in sorted(sessions, key=lambda s: s["id"]):
            path = session["_path"].relative_to(ROOT).as_posix()
            next_action = session["next_action"].replace("\n", " ").strip()
            phases = session["workflow_phases"]
            recordings = {phase["recording"] for phase in phases}
            recording = next(iter(recordings)) if len(recordings) == 1 else "mixed"
            entry = phases[0]
            current = phases[-1]
            lines.append(
                f"| [{session['id']}]({path}) | {session['status']} "
                f"| {recording} | `{entry['workflow']}` ({entry['focus']}) "
                f"| `{current['workflow']}` ({current['focus']}) | {len(phases)} "
                f"| {session['primary_bead']} | {next_action} |"
            )
        declared_entries = Counter(
            session["workflow_phases"][0]["workflow"]
            for session in sessions
            if session["workflow_phases"][0]["recording"] == "contemporaneous"
        )
        retrospective_entries = Counter(
            session["workflow_phases"][0]["workflow"]
            for session in sessions
            if session["workflow_phases"][0]["recording"] == "retrospective"
        )
        declared_phases = Counter(
            phase["workflow"]
            for session in sessions
            for phase in session["workflow_phases"]
            if phase["recording"] == "contemporaneous"
        )
        retrospective_phases = Counter(
            phase["workflow"]
            for session in sessions
            for phase in session["workflow_phases"]
            if phase["recording"] == "retrospective"
        )
        lines += [
            "",
            "### Workflow summary",
            "",
            (
                "Declared counts are contemporaneous contracts; retrospective counts are "
                "reconstructed history. Entries use each session's first phase."
            ),
            "",
            (
                "| workflow | declared entries | retrospective entries "
                "| declared phases | retrospective phases |"
            ),
            "| --- | ---: | ---: | ---: | ---: |",
        ]
        for workflow in workflow_order():
            if any(
                counts[workflow]
                for counts in (
                    declared_entries,
                    retrospective_entries,
                    declared_phases,
                    retrospective_phases,
                )
            ):
                lines.append(
                    f"| `{workflow}` | {declared_entries[workflow]} "
                    f"| {retrospective_entries[workflow]} | {declared_phases[workflow]} "
                    f"| {retrospective_phases[workflow]} |"
                )
        lines.append("")

    if agendas:
        lines += ["## Experiment agendas", ""]
        for agenda in sorted(agendas, key=lambda a: a["id"]):
            path = agenda["_path"].relative_to(ROOT).as_posix()
            objective = agenda["objective"].replace("\n", " ").strip()
            lines += [
                f"### [{agenda['id']}]({path}) — {agenda['title']}",
                "",
                f"Status: **{agenda['status']}**. {objective}",
                "",
                "| item | purpose | n | state | priority | bead | next evidence |",
                "| --- | --- | --- | --- | ---: | --- | --- |",
            ]
            for item in agenda["items"]:
                instances = ", ".join(str(n) for n in item["instances"])
                evidence = item["next_evidence"].replace("\n", " ").strip()
                lines.append(
                    f"| {item['id']} | {item['purpose']} | {instances} | {item['state']} "
                    f"| {item['priority']} | {item['bead']} | {evidence} |"
                )
            lines.append("")

    lines += [
        "## Series",
        "",
        "| id | status | title | rounds | opened because |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in sorted(series, key=lambda s: s["id"]):
        rounds = sum(1 for e in experiments if e.get("series") == s["id"])
        because = s.get("opened_because", "").replace("\n", " ").strip()
        lines.append(
            f"| {s['id']} | {s['status']} | {s['title']} | {rounds} | {because[:50]} |"
        )
    lines.append("")

    lines += [
        "## Registry",
        "",
        "| id | status | lane | claim | sweep | rounds | spent |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for hypothesis in sorted(hypotheses, key=lambda h: h["id"]):
        rounds = by_hypothesis.get(hypothesis["id"], [])
        claim = hypothesis["claim"].replace("\n", " ").strip()
        lines.append(
            f"| {hypothesis['id']} | {status_of(hypothesis, rounds)} "
            f"| {hypothesis.get('lane', '')} | {claim[:70]} "
            f"| {sweep_coverage(hypothesis, rounds)} | {len(rounds)} "
            f"| {spent(rounds)} |"
        )

    # First, always: what the runner would not decide. The schema has carried
    # `needs_review` since the record was designed and nothing read it, so an unattended
    # runner could set the flag and no view would show it -- the morning human would
    # never learn what was declined. It leads the ledger for the same reason it leads
    # the session report: a queue is trusted because its refusals are visible.
    review = [e for e in experiments if (e.get("verdict") or {}).get("needs_review")]
    if review:
        lines += ["", "## Needs review — held for a human, not decided", ""]
        lines += [
            "| id | hypotheses | decision | why it was not decided |",
            "| --- | --- | --- | --- |",
        ]
        for experiment in sorted(review, key=lambda e: e["id"]):
            verdict = experiment["verdict"]
            lines.append(
                f"| {experiment['id']} "
                f"| {', '.join(experiment.get('hypotheses') or [])} "
                f"| {verdict.get('decision', '')} "
                f"| {verdict['reason'].replace(chr(10), ' ').strip()} |"
            )

    lines += ["", "## Rounds", ""]
    for decision in DECISION_ORDER:
        matching = [e for e in experiments if e.get("verdict", {}).get("decision") == decision]
        if not matching:
            continue
        lines += [f"### {decision} ({len(matching)})", ""]
        lines += [
            "| id | series | instance | operator | hypotheses | reason |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for experiment in sorted(matching, key=lambda e: e["id"]):
            verdict = experiment["verdict"]
            instance = experiment.get("instance") or {}
            lines.append(
                f"| {experiment['id']} | {experiment.get('series', '')} "
                f"| {instance.get('point', '')} "
                f"| {experiment.get('method', {}).get('operator', '')} "
                f"| {', '.join(experiment.get('hypotheses') or [])} "
                f"| {verdict['reason'].replace(chr(10), ' ').strip()} |"
            )
        lines.append("")

    # Work that stopped on the clock rather than on an answer. This is the section a
    # returning agent reads first: every row is a question still open, with the budget
    # already spent on it and the state needed to continue.
    resumable = [
        e
        for e in experiments
        if (e.get("effort") or {}).get("stopped_by") in ("timebox", "dependency")
        or e.get("verdict", {}).get("decision") == "abandoned"
    ]
    if resumable:
        lines += ["## Resumable — stopped on the clock, not on an answer", ""]
        lines += [
            "| id | hypotheses | spent | stopped by | resume from | reopen when |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for experiment in sorted(resumable, key=lambda e: e["id"]):
            verdict = experiment.get("verdict") or {}
            effort = experiment.get("effort") or {}
            lines.append(
                f"| {experiment['id']} "
                f"| {', '.join(experiment.get('hypotheses') or [])} "
                f"| {spent([experiment])} | {effort.get('stopped_by', '')} "
                f"| {(verdict.get('resume_from') or '').replace(chr(10), ' ').strip()[:60]} "
                f"| {(verdict.get('reopen_when') or '').replace(chr(10), ' ').strip()[:60]} |"
            )
        lines.append("")

    total_minutes, total_seconds = effort_of(experiments)
    if total_minutes or total_seconds:
        lines += [
            "## Effort",
            "",
            (
                f"{len(experiments)} rounds, {total_minutes:g} agent-minutes, "
                f"{total_seconds / 60:.1f} wall-minutes."
            ),
            "",
        ]

    unmined = [x for x in explorations if not x.get("proposes")]
    if unmined:
        lines += ["## Exploration reports not yet codified", ""]
        lines += [f"- {x['id']} — {x['title']}" for x in unmined]
        lines.append("")

    lines += DOC_FOOTER
    return "\n".join(lines) + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action",
        choices=("check", "render"),
        help="check invariants and freshness, or atomically rebuild ledger.md",
    )
    return parser


def main(arguments: list[str] | None = None) -> int:
    """Validate campaign records and check or render their generated ledger."""
    options = _parser().parse_args(arguments)
    try:
        require_project_root(PROJECT_ROOT)
    except ProjectLayoutError as error:
        print(f"packing-ledger: error: {error}", file=sys.stderr)
        return 2
    now = dt.datetime.now(dt.UTC).replace(tzinfo=None)
    series = load(ROOT / "series", "series", "*/README.md")
    explorations = load(ROOT / "explorations", "exploration")
    hypotheses = load(ROOT / "hypotheses", "hypothesis")
    experiments = load(ROOT / "series", "experiment", "*/experiments/*.md")
    sessions = load(ROOT / "agent-sessions", "session", "session-*.md")
    agendas = load(ROOT / "agendas", "agenda", "agenda-*.md")
    logbook_entries = load(ROOT / "research-loop-logbook", "logbook_entry", "run-*.md")

    problems = check(
        series,
        explorations,
        hypotheses,
        experiments,
        sessions,
        agendas=agendas,
        now=now,
        logbook_entries=logbook_entries,
    )
    for problem in problems:
        print(f"FAIL {problem}", file=sys.stderr)

    rendered = render(
        series,
        explorations,
        hypotheses,
        experiments,
        sessions,
        agendas=agendas,
        logbook_entries=logbook_entries,
    )
    if options.action == "check":
        current = LEDGER.read_text() if LEDGER.exists() else ""
        if current != rendered:
            print("FAIL ledger.md is stale; run `packing-ledger render`", file=sys.stderr)
            problems.append("stale ledger")
    else:
        with atomic_output_file(LEDGER, make_parents=True) as temporary:
            temporary.write_text(rendered, encoding="utf-8")
        print(f"wrote {LEDGER.relative_to(ROOT)}")

    if problems:
        return 1
    session_label = "session" if len(sessions) == 1 else "sessions"
    print(
        f"OK {len(series)} series, {len(explorations)} reports, "
        f"{len(hypotheses)} hypotheses, {len(experiments)} rounds, "
        f"{len(sessions)} agent {session_label}, {len(agendas)} agendas, "
        f"{len(logbook_entries)} logbook entries"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
