import Sqpack.ZMTreeX

set_option linter.style.longLine false

/-!
# `M2p`: the mixed cover (generated by `lean/scripts/gen_zmmtree.py`; do not edit)

From `M2p.txt`, sha256 `fa0fb386e911eaa926effacf48f07825f6a5f7f7f4c5d3c9fde1af7ddd297d38`:
5 points `(X/1000, Y/1000)` and 40 segments, masses `w/1000000`, container `[0, 2000/1000]²`.
-/

namespace SquarePacking.M2p

open BoxTree ZMTreeM

set_option maxRecDepth 100000 in
def pts : PTree :=
  (.node (.node (.node .leaf 500 500 200000 .leaf) 500 1500 200000 .leaf) 1000 1000 50000 (.node (.node .leaf 1500 500 200000 .leaf) 1500 1500 200000 .leaf))

theorem pts_nodup : pts.toList.Nodup :=
  PTree.nodup_of_chainB _ (by decide +kernel)

theorem pts_d4 : d4Check 2000 pts = true := by decide +kernel

set_option maxRecDepth 100000 in
def segs : STree :=
  (.node (.node (.node (.node (.node (.node .leaf (0, 1000, 100, 1000, 50000) .leaf) (100, 1000, 200, 1000, 50000) .leaf) (200, 1000, 300, 1000, 50000) (.node (.node .leaf (300, 1000, 400, 1000, 50000) .leaf) (400, 1000, 500, 1000, 50000) .leaf)) (500, 1000, 600, 1000, 50000) (.node (.node (.node .leaf (600, 1000, 700, 1000, 50000) .leaf) (700, 1000, 800, 1000, 50000) .leaf) (800, 1000, 900, 1000, 50000) (.node .leaf (900, 1000, 1000, 1000, 50000) .leaf))) (1000, 0, 1000, 100, 50000) (.node (.node (.node (.node .leaf (1000, 100, 1000, 200, 50000) .leaf) (1000, 200, 1000, 300, 50000) .leaf) (1000, 300, 1000, 400, 50000) (.node .leaf (1000, 400, 1000, 500, 50000) .leaf)) (1000, 500, 1000, 600, 50000) (.node (.node (.node .leaf (1000, 600, 1000, 700, 50000) .leaf) (1000, 700, 1000, 800, 50000) .leaf) (1000, 800, 1000, 900, 50000) (.node .leaf (1000, 900, 1000, 1000, 50000) .leaf)))) (1000, 1000, 1000, 1100, 50000) (.node (.node (.node (.node (.node .leaf (1000, 1000, 1100, 1000, 50000) .leaf) (1000, 1100, 1000, 1200, 50000) .leaf) (1000, 1200, 1000, 1300, 50000) (.node .leaf (1000, 1300, 1000, 1400, 50000) .leaf)) (1000, 1400, 1000, 1500, 50000) (.node (.node (.node .leaf (1000, 1500, 1000, 1600, 50000) .leaf) (1000, 1600, 1000, 1700, 50000) .leaf) (1000, 1700, 1000, 1800, 50000) (.node .leaf (1000, 1800, 1000, 1900, 50000) .leaf))) (1000, 1900, 1000, 2000, 50000) (.node (.node (.node (.node .leaf (1100, 1000, 1200, 1000, 50000) .leaf) (1200, 1000, 1300, 1000, 50000) .leaf) (1300, 1000, 1400, 1000, 50000) (.node .leaf (1400, 1000, 1500, 1000, 50000) .leaf)) (1500, 1000, 1600, 1000, 50000) (.node (.node (.node .leaf (1600, 1000, 1700, 1000, 50000) .leaf) (1700, 1000, 1800, 1000, 50000) .leaf) (1800, 1000, 1900, 1000, 50000) (.node .leaf (1900, 1000, 2000, 1000, 50000) .leaf)))))

theorem segs_d4 : segD4Check 2000 segs = true := by decide +kernel

theorem wsum_lt : pts.wsum + segs.wsum < 3 * 1000000 := by decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
def ptsL : List (ℕ × ℕ × ℕ) :=
  [(500, 500, 200000),
   (500, 1500, 200000),
   (1000, 1000, 50000),
   (1500, 500, 200000),
   (1500, 1500, 200000)]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
def segsL : List SegE :=
  [(0, 1000, 100, 1000, 50000),
   (100, 1000, 200, 1000, 50000),
   (200, 1000, 300, 1000, 50000),
   (300, 1000, 400, 1000, 50000),
   (400, 1000, 500, 1000, 50000),
   (500, 1000, 600, 1000, 50000),
   (600, 1000, 700, 1000, 50000),
   (700, 1000, 800, 1000, 50000),
   (800, 1000, 900, 1000, 50000),
   (900, 1000, 1000, 1000, 50000),
   (1000, 0, 1000, 100, 50000),
   (1000, 100, 1000, 200, 50000),
   (1000, 200, 1000, 300, 50000),
   (1000, 300, 1000, 400, 50000),
   (1000, 400, 1000, 500, 50000),
   (1000, 500, 1000, 600, 50000),
   (1000, 600, 1000, 700, 50000),
   (1000, 700, 1000, 800, 50000),
   (1000, 800, 1000, 900, 50000),
   (1000, 900, 1000, 1000, 50000),
   (1000, 1000, 1000, 1100, 50000),
   (1000, 1000, 1100, 1000, 50000),
   (1000, 1100, 1000, 1200, 50000),
   (1000, 1200, 1000, 1300, 50000),
   (1000, 1300, 1000, 1400, 50000),
   (1000, 1400, 1000, 1500, 50000),
   (1000, 1500, 1000, 1600, 50000),
   (1000, 1600, 1000, 1700, 50000),
   (1000, 1700, 1000, 1800, 50000),
   (1000, 1800, 1000, 1900, 50000),
   (1000, 1900, 1000, 2000, 50000),
   (1100, 1000, 1200, 1000, 50000),
   (1200, 1000, 1300, 1000, 50000),
   (1300, 1000, 1400, 1000, 50000),
   (1400, 1000, 1500, 1000, 50000),
   (1500, 1000, 1600, 1000, 50000),
   (1600, 1000, 1700, 1000, 50000),
   (1700, 1000, 1800, 1000, 50000),
   (1800, 1000, 1900, 1000, 50000),
   (1900, 1000, 2000, 1000, 50000)]

set_option maxRecDepth 100000 in
theorem pts_toList : pts.toList = ptsL := by decide +kernel

set_option maxRecDepth 100000 in
theorem segs_toList : segs.toList = segsL := by decide +kernel

theorem ptsL_nodup : ptsL.Nodup := pts_toList ▸ pts_nodup

theorem segsL_nodup : segsL.Nodup := by
  rw [← segs_toList]
  have h := segs_d4
  simp only [segD4Check, Bool.and_eq_true] at h
  exact STree.nodup_of_chainB _ h.1

end SquarePacking.M2p
