# A local stub for the part of gmpy2 the kernel uses: the package ships no type
# information. `mpq` and `mpz` are declared with the arithmetic, comparison and
# conversion protocols `sqpack.hull_kernel` relies on; anything else is deliberately
# absent so that a new use of the library shows up here first. The class names are the
# library's own, lowercase.

from fractions import Fraction
from typing import SupportsIndex, overload

def version() -> str: ...
def mp_version() -> str: ...
def mpfr_version() -> str: ...

class mpz:  # noqa: N801
    def __init__(self, value: mpz | str | float = 0, /) -> None: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __neg__(self) -> mpz: ...
    def __pos__(self) -> mpz: ...
    def __abs__(self) -> mpz: ...
    @overload
    def __add__(self, other: int | mpz) -> mpz: ...
    @overload
    def __add__(self, other: mpq | Fraction) -> mpq: ...
    @overload
    def __radd__(self, other: int | mpz) -> mpz: ...
    @overload
    def __radd__(self, other: mpq | Fraction) -> mpq: ...
    @overload
    def __sub__(self, other: int | mpz) -> mpz: ...
    @overload
    def __sub__(self, other: mpq | Fraction) -> mpq: ...
    @overload
    def __rsub__(self, other: int | mpz) -> mpz: ...
    @overload
    def __rsub__(self, other: mpq | Fraction) -> mpq: ...
    @overload
    def __mul__(self, other: int | mpz) -> mpz: ...
    @overload
    def __mul__(self, other: mpq | Fraction) -> mpq: ...
    @overload
    def __rmul__(self, other: int | mpz) -> mpz: ...
    @overload
    def __rmul__(self, other: mpq | Fraction) -> mpq: ...
    def __floordiv__(self, other: int | mpz) -> mpz: ...
    def __rfloordiv__(self, other: int | mpz) -> mpz: ...
    def __mod__(self, other: int | mpz) -> mpz: ...
    def __rmod__(self, other: int | mpz) -> mpz: ...
    def __pow__(self, other: int | mpz) -> mpz: ...
    def __lt__(self, other: _Rational) -> bool: ...
    def __le__(self, other: _Rational) -> bool: ...
    def __gt__(self, other: _Rational) -> bool: ...
    def __ge__(self, other: _Rational) -> bool: ...
    @property
    def numerator(self) -> mpz: ...
    @property
    def denominator(self) -> mpz: ...

class mpq:  # noqa: N801
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: _Rational | str | float, /) -> None: ...
    @overload
    def __init__(self, numerator: int | mpz, denominator: int | mpz, /) -> None: ...
    @property
    def numerator(self) -> mpz: ...
    @property
    def denominator(self) -> mpz: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __round__(self, ndigits: int | None = None, /) -> mpz: ...
    def __neg__(self) -> mpq: ...
    def __pos__(self) -> mpq: ...
    def __abs__(self) -> mpq: ...
    def __add__(self, other: _Rational) -> mpq: ...
    def __radd__(self, other: _Rational) -> mpq: ...
    def __sub__(self, other: _Rational) -> mpq: ...
    def __rsub__(self, other: _Rational) -> mpq: ...
    def __mul__(self, other: _Rational) -> mpq: ...
    def __rmul__(self, other: _Rational) -> mpq: ...
    def __truediv__(self, other: _Rational) -> mpq: ...
    def __rtruediv__(self, other: _Rational) -> mpq: ...
    def __pow__(self, other: SupportsIndex) -> mpq: ...
    def __lt__(self, other: _Rational) -> bool: ...
    def __le__(self, other: _Rational) -> bool: ...
    def __gt__(self, other: _Rational) -> bool: ...
    def __ge__(self, other: _Rational) -> bool: ...

type _Rational = int | mpz | mpq | Fraction
