#!/usr/bin/env python3
"""Check that every generated Markdown view is exempt from the auto-formatter.

A generated view is rebuilt byte-for-byte by its generator and drift-checked in
`test.sh`. If the Markdown auto-formatter is also allowed to rewrite it, the two
disagree forever: flowmark reflows the file, the generator regenerates the unwrapped
form, and the drift check fails until someone notices and regenerates by hand.

That reasoning was written into `.flowmarkignore` for `campaign/ledger.md` and then
not applied to `defects.md`, which sat reflowable for a day (D-027). The list was
trusted rather than enforced, so this enforces it: a file carrying the generated-by
banner must be named in `.flowmarkignore`.

Usage:
    python3 tools/check_generated_exempt.py
"""

from __future__ import annotations

import pathlib
import sys

PACKING = pathlib.Path(__file__).resolve().parent.parent
REPO = PACKING.parent.parent
BANNER = "GENERATED by"
# The literature archive is excluded wholesale by .flowmarkignore's directory rules,
# and .venv is not ours; neither carries a generated view of this kind.
SKIP_PARTS = {".venv", "resources"}


def listed_paths() -> set[str]:
    """The non-comment entries of .flowmarkignore."""
    text = (REPO / ".flowmarkignore").read_text(encoding="utf-8")
    return {
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }


def main() -> int:
    listed = listed_paths()
    missing = []
    for md in sorted(PACKING.rglob("*.md")):
        rel_to_packing = md.relative_to(PACKING)
        if SKIP_PARTS & set(rel_to_packing.parts):
            continue
        if BANNER not in md.read_text(encoding="utf-8", errors="ignore"):
            continue
        rel = md.relative_to(REPO).as_posix()
        if rel not in listed:
            missing.append(rel)
    if missing:
        print(
            "  generated views not exempt from the Markdown formatter: " + ", ".join(missing),
            file=sys.stderr,
        )
        print("  add them to .flowmarkignore", file=sys.stderr)
        return 1
    print("  every generated view is exempt from the Markdown formatter")
    return 0


if __name__ == "__main__":
    sys.exit(main())
