#!/usr/bin/env python3
"""Render defects.md from defects.yaml. Generated view; never hand-edited.

The tables are chosen to answer one question -- where should effort go to make the
pipeline catch more, sooner? Three cuts do that:

  by detector   which devices are actually earning their keep, so we build more of them
  by layer      where defects arise, which is not always where they are noticed
  unprotected   fixes that left no check behind, which is the list that predicts recurrence

Usage:
    python3 tools/render_defects.py            # regenerate defects.md
    python3 tools/render_defects.py --check     # fail if it is stale
"""

from __future__ import annotations

import pathlib
import sys
from collections import Counter

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "defects.yaml"
OUT = ROOT / "defects.md"
BANNER = "<!-- GENERATED by tools/render_defects.py from defects.yaml. Do not edit by hand. -->"


def tally(rows: list[dict], key: str, order: list[str]) -> list[tuple[str, int]]:
    counts = Counter(r[key] for r in rows)
    return [(k, counts[k]) for k in order if counts[k]] + [
        (k, v) for k, v in sorted(counts.items()) if k not in order
    ]


def render(d: dict) -> str:
    ds = d["defects"]
    out = [BANNER, "", "# Defect log", ""]
    out += [
        f"{len(ds)} defects recorded across the packing toolchain.",
        "One line each here; the narrative lives in the artifact named by every row.",
        "Source of truth is [`defects.yaml`](defects.yaml).",
        "",
    ]

    sound = [x for x in ds if x["class"] == "soundness"]
    flat = [x for x in sound if x.get("direction") == "flattering"]
    open_ = [x for x in ds if x["status"] in ("outstanding", "contained")]
    unprotected = [x for x in ds if x["regression"] == "none" and x["status"] != "outstanding"]
    recurrences = [x for x in ds if x.get("recurrence_of")]

    repeats = ", ".join(f"{d['id']} repeats {d['recurrence_of']}" for d in recurrences)
    plural = "is" if len(open_) == 1 else "are"
    out += [
        "## The short version",
        "",
        (
            f"- **{len(sound)} soundness defects** — the system asserting something "
            f"false about the mathematics. {len(flat)} of them pointed in the "
            "*flattering* direction, which is the dangerous one: the error looks like "
            "success."
        ),
        (
            f"- **{len(unprotected)} fixes left no regression check behind.** That "
            "list is the best predictor of what comes back — and it already has, once "
            f"({repeats or 'none yet'})."
        ),
        (
            f"- **{len(open_)} {plural} still open** (outstanding or contained), every "
            "one carrying a bead."
        ),
        "",
    ]

    out += [
        "## What caught them",
        "",
        "| Detector | Count | What it is |",
        "| --- | ---: | --- |",
    ]
    meaning = {
        "pre_registered_rule": (
            "a rule written down before the measurement, e.g. “beating the record "
            "means you have a bug”"
        ),
        "control_cell": "a cell of the sweep whose answer is known in advance",
        "review": "a human or agent reading the work against a checklist",
        "anomaly": "a result that made no sense, chased down",
        "inspection": "reading the code or the design with intent",
        "drift_check": "a generated view disagreeing with its source",
        "design": "caught while designing, before it reached data",
        "gate": "the automated test suite",
    }
    for name, count in tally(ds, "detected_by", list(meaning)):
        out.append(f"| `{name}` | {count} | {meaning.get(name, '')} |")
    # Derived, not asserted: this claim was true at 23 defects and false at 25, and
    # the same sentence was repeated in three hand-written documents (D-026).
    gate_n = sum(1 for x in ds if x["detected_by"] == "gate")
    sound = [x for x in ds if x["class"] == "soundness"]
    gate_sound = sum(1 for x in sound if x["detected_by"] == "gate")
    if gate_n == 0:
        headline = "**the automated gate caught none of them.**"
    elif gate_sound == 0:
        headline = (
            f"**the automated gate caught {gate_n} of {len(ds)}, and none of the "
            f"{len(sound)} soundness defects.**"
        )
    else:
        headline = (
            f"**the automated gate caught {gate_n} of {len(ds)}, {gate_sound} of them "
            f"soundness.**"
        )
    out += [
        "",
        (
            f"The line worth reading twice: {headline} Gates confirm what you already "
            "thought to check. The rest were found by a device built to be *surprised* "
            "— a control cell, a pre-registered rule, a generated view contradicting "
            "itself — or by someone reading carefully."
        ),
        "",
    ]

    out += ["## Where they arise", "", "| Layer | Count |", "| --- | ---: |"]
    for k, v in tally(
        ds, "layer", ["engine", "quench", "verifier", "record", "tooling", "docs"]
    ):
        out.append(f"| {k} | {v} |")
    out += ["", "## By kind", "", "| Class | Count |", "| --- | ---: |"]
    for k, v in tally(
        ds, "class", ["soundness", "validity", "bookkeeping", "robustness", "performance"]
    ):
        out.append(f"| {k} | {v} |")
    out.append("")

    if unprotected:
        out += [
            "## Fixed, but nothing stops it coming back",
            "",
            "Each of these had its cause removed and no check added.",
            "This is the actionable list.",
            "",
            "| id | title | layer |",
            "| --- | --- | --- |",
        ]
        for x in unprotected:
            out.append(f"| {x['id']} | {x['title']} | {x['layer']} |")
        out.append("")

    if open_:
        out += [
            "## Still open",
            "",
            "| id | status | severity | title | bead |",
            "| --- | --- | --- | --- | --- |",
        ]
        for x in open_:
            out.append(
                f"| {x['id']} | {x['status']} | {x['severity']} "
                f"| {x['title']} | `{x.get('bead', '')}` |"
            )
        out.append("")

    out += [
        "## Every defect",
        "",
        "| id | date | layer | class | dir | caught by | severity | status | title |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for x in ds:
        out.append(
            f"| [{x['id']}]({x['recorded_in']}) | {x['date']} | {x['layer']} | {x['class']} "
            f"| {x.get('direction', '')} | `{x['detected_by']}` "
            f"| {x['severity']} | {x['status']} "
            f"| {x['title']} |"
        )
    out.append("")
    return "\n".join(out)


def main() -> int:
    rendered = render(yaml.safe_load(SRC.read_text(encoding="utf-8")))
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        # Compare content, not typography: the formatter owns wrapping and quote style.
        fold = str.maketrans({"\u2019": "'", "\u201c": '"', "\u201d": '"', "\u2014": "-"})

        def norm(text: str) -> str:
            return " ".join(text.translate(fold).split())

        if norm(current) != norm(rendered):
            print("FAIL defects.md is stale; run tools/render_defects.py", file=sys.stderr)
            return 1
        count = len(yaml.safe_load(SRC.read_text(encoding="utf-8"))["defects"])
        print(f"  defects.md matches defects.yaml ({count} defects)")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
