"""Join the result reports received as GitHub issues to the register, and say what each is owed.

An author who reports a result on an issue is owed three things by the result import
process (`campaign/result-import.md`, stage 7): a reply when the result is imported, one
when it is confirmed or a defect is found, a follow-up whenever the record moves past what
a reply said, and a final comment and close once nothing they asked for is queued. The
register says how far each result is validated. Nothing said which issue asked for which
entry, or what each author had been told, so replies went unposted (issue 170 was never
answered) and stated ids went stale (issue 247 still reads T-058 for T-061).

`campaign/result-requests.yaml` is that join: one entry per issue, the register and
evidence ids each reported result maps to, the beads that track it, and every reply
posted with the state it reported. This tool derives the rest from the record and the
register together and stores none of it:

- each result's state: `confirmed` (every mapped entry at `V3` and `C3` or above),
  `refuted`, `defect recorded`, `open` while validation runs, or `queued` for import;
- **reply due**, when the derived state has moved past the last reply that spoke of a
  result: a new id, a moved rung, a renumbered id, a defect, or a statement the record
  marks out of date;
- **closeable**, when every result is confirmed or refuted (a reported defect: recorded)
  and nothing the author asked for is queued.

Modes, from ``packing/`` with the project interpreter::

    .venv/bin/python3 -m devtools.check_requests            # the gate: ids and schema
    .venv/bin/python3 -m devtools.check_requests --report   # a table per issue
    .venv/bin/python3 -m devtools.check_requests --backlog  # entries below V3 or C3
    .venv/bin/python3 -m devtools.check_requests --draft 282
    .venv/bin/python3 -m devtools.check_requests --github   # live issues, read-only

The default mode reads two files and the register and touches no clock, network or
history, so its verdict is a function of the tree. Only the ids and the schema can fail
it: a reply that is due is the owner's next move, not a broken record. ``--draft``
refuses unless ``HEAD`` is on ``origin/main``, because a `T-NNN` is provisional until it
merges and a reply links only to `main`. ``--github`` reads the live issues through
``gh api`` and writes nothing anywhere.
"""

from __future__ import annotations

import argparse
import itertools
import json
import re
import subprocess
import sys
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from jsonschema_rs import Draft202012Validator

from devtools import result_status
from sqpack.yamlio import load_yaml, safe_load

ROOT = Path(__file__).resolve().parent.parent
REPO = ROOT.parent
RECORD = ROOT / "campaign" / "result-requests.yaml"
SCHEMA = ROOT / "campaign" / "schemas" / "result-requests.schema.yaml"
RESULTS = ROOT / "frontier" / "results.yaml"
EVIDENCE = ROOT / "frontier" / "evidence.yaml"
#: The verifier programs evidence entries name in `verifiers`, when that file exists.
VERIFIERS = ROOT / "frontier" / "verifiers.yaml"
#: The repository-relative paths the draft and the on-main column read at `origin/main`.
RESULTS_PATH = "packing/frontier/RESULTS.md"
STATUS_PATH = "packing/frontier/STATUS.md"

#: The footer every reply an agent drafts ends with, and the one that marks a comment by
#: someone other than the owner as this project's reply.
FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_"
FOOTER_LINE = FOOTER.rsplit("\n", 1)[-1]

#: The rung from which a result counts as confirmed for the purpose of answering its
#: author: checkable and machine-replayed (`V3`, `C3`). Below it the result is still being
#: validated, whatever its status word says.
CONFIRMED_RANK = 3
#: Evidence origins that count as confirmation (epistemics.md, Confirmation).
CONFIRMING_ORIGINS = frozenset({"audited-here", "replayed-here", "independently-external"})
THIRD_PARTY = "independently-external"
OPTIMALITY = "optimality"
UPPER_BOUND = "upper-bound"

CONFIRMED = "confirmed"
REFUTED = "refuted"
DEFECT = "defect recorded"
OPEN = "open"
QUEUED = "queued"
NOT_REGISTERED = "not registered"

BEAD = re.compile(r"\bthink-[a-z0-9]{4}\b")
_ID_ON_MAIN = re.compile(r"\bid: (T-\d{3}|E-[A-Za-z0-9.-]+)")
_REPLY_URL = re.compile(
    r"^https://github\.com/([\w.-]+/[\w.-]+)/issues/(\d+)#issuecomment-\d+$"
)
#: Bead references in register prose, removed from what an author is told: a bead id is
#: this project's bookkeeping and means nothing on an issue.
_BEAD_PARENTHESIS = re.compile(r"\s*\((?:think-[a-z0-9]{4}(?:,\s*)?)+\)")
_BEAD_LEAD = re.compile(r"^think-[a-z0-9]{4}(?:\s+under\s+think-[a-z0-9]{4})?:\s*")

Mapped = Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class Register:
    """The register's results and evidence, each by id."""

    results: dict[str, Mapped]
    evidence: dict[str, Mapped]
    verifiers: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class Entry:
    """One register or evidence entry as an author's result stands on it now."""

    id: str
    rungs: str
    state: str
    status: str
    why: str
    how: str


@dataclass(frozen=True, slots=True)
class ResultState:
    """One reported result, joined to the entries it maps to."""

    key: str
    claim: str
    entries: tuple[Entry, ...]
    state: str
    settled: bool
    reason: str


@dataclass(frozen=True, slots=True)
class IssueState:
    """What an issue is owed, derived from the record and the register."""

    number: int
    results: tuple[ResultState, ...]
    replies_due: tuple[str, ...]
    closeable: bool
    blockers: tuple[str, ...]


def load_register(
    results: Path = RESULTS, evidence: Path = EVIDENCE, verifiers: Path | None = None
) -> Register:
    register = safe_load(results.read_text(encoding="utf-8"))
    entries = safe_load(evidence.read_text(encoding="utf-8"))
    return Register(
        results={str(item["id"]): item for item in register["results"]},
        evidence={str(item["id"]): item for item in entries["evidence"]},
        verifiers=load_verifiers(VERIFIERS if verifiers is None else verifiers),
    )


def load_record(path: Path = RECORD) -> dict[str, Any]:
    return load_yaml(path.read_text(encoding="utf-8"))


def schema_errors(record: Mapped, schema: Path = SCHEMA) -> list[str]:
    """The record against its declared schema, as `validate_schemas` reports it."""
    meta = record.get("softschema") or {}
    problems = [
        f"softschema.{key} missing"
        for key in ("contract", "schema", "status")
        if not meta.get(key)
    ]
    if meta.get("status") not in (None, "enforced"):
        problems.append(f"softschema.status is {meta['status']!r}, expected 'enforced'")
    validator = Draft202012Validator(safe_load(schema.read_text(encoding="utf-8")))
    payload = {key: value for key, value in record.items() if key != "softschema"}
    for error in sorted(validator.iter_errors(payload), key=lambda e: list(e.instance_path)):
        where = "/".join(str(part) for part in error.instance_path) or "<root>"
        problems.append(f"{where}: {error.message}")
    return problems


def _rank(rung: object) -> int:
    return int(str(rung)[1])


#: How a confirming entry's checker stands to the code that produced the certificate,
#: the evidence schema's `relationship_to_generator`, in the words an author is told. The
#: other values (`not-applicable`, `unknown-historical`) say nothing an author can use,
#: and read as not yet recorded.
RELATION_PHRASES = {
    "same-implementation": "reproduced {where} with the author's own checker",
    "independent-implementation": "re-verified {where} by an independent implementation",
    "generator": "reproduced {where} by the program that produced it",
}


def load_verifiers(path: Path = VERIFIERS) -> dict[str, str]:
    """Each verifier's id and the program name a reader is told, or nothing without the file.

    Read as a list of entries under `verifiers`, or as a mapping from id to entry; an
    entry's `name`, else its `program`, else its id, is what a draft prints.
    """
    if not path.exists():
        return {}
    document = safe_load(path.read_text(encoding="utf-8")) or {}
    listed = document.get("verifiers", document) if isinstance(document, Mapping) else document
    if isinstance(listed, Mapping):
        listed = [
            {"id": key, **(value if isinstance(value, Mapping) else {})}
            for key, value in listed.items()
        ]
    names: dict[str, str] = {}
    for item in listed or ():
        if isinstance(item, Mapping) and item.get("id"):
            names[str(item["id"])] = str(item.get("name") or item.get("program") or item["id"])
    return names


def verifier_phrase(entry: Mapped, verifiers: Mapping[str, str] | None = None) -> str:
    """How a confirming evidence entry re-verified the result, or nothing if unrecorded.

    The relation is the entry's `relationship_to_generator`: the author's own checker run
    here, or an independently written one. The programs are its `verifiers`, resolved
    against `frontier/verifiers.yaml`; without the field or the file no program is named,
    rather than one guessed from the replay command.
    """
    template = RELATION_PHRASES.get(str(entry.get("relationship_to_generator")))
    if template is None:
        return ""
    where = "by a third party" if entry.get("origin") == THIRD_PARTY else "here"
    known = verifiers or {}
    names = [known[ident] for ident in entry.get("verifiers") or () if ident in known]
    named = f" ({', '.join(names)})" if names else ""
    return template.format(where=where) + named


def confirmation_phrase(cited: Iterable[str], register: Register, kind: str = "") -> str:
    """How a confirmed result was re-verified, one phrase for each confirming entry.

    An exact value takes its confirmation from its lower half (epistemics.md, Scope and
    Composition), so the upper half's entry, most often the grid's, is not described: an
    author told that their lower bound was "re-verified by an independent implementation"
    because the grid was would be told something false.
    """
    phrases: list[str] = []
    missing: list[str] = []
    for ref in cited:
        entry = register.evidence.get(ref)
        if not entry or entry.get("origin") not in CONFIRMING_ORIGINS:
            continue
        if kind == OPTIMALITY and entry.get("claim") == UPPER_BOUND:
            continue
        if entry.get("replay_status") != "passed":
            continue
        phrase = verifier_phrase(entry, register.verifiers)
        if phrase:
            if phrase not in phrases:
                phrases.append(phrase)
        else:
            missing.append(ref)
    if not phrases:
        return "how it was re-verified is not yet recorded"
    if missing:
        phrases.append(f"for {', '.join(missing)} not yet recorded")
    return "; ".join(phrases)


def entry_state(ident: str, register: Register) -> Entry:
    """A register entry, or an evidence entry, as it stands today."""
    if ident.startswith("T-"):
        return _register_entry(ident, register)
    return _evidence_entry(ident, register)


def _register_entry(ident: str, register: Register) -> Entry:
    record = register.results[ident]
    rungs = f"{record['verification']}/{record['confirmation']}"
    status = result_status.status(record, register.evidence)
    reviews = list(record.get("reviews") or [])
    latest = result_status.latest_review(reviews)
    if latest and latest.get("verdict") == "refuted":
        return Entry(ident, rungs, REFUTED, status, str(latest.get("path")), "")
    if issues := result_status.open_issues(record, register.evidence):
        return Entry(ident, rungs, DEFECT, status, "; ".join(issues), "")
    how = ""
    if _rank(record["confirmation"]) >= result_status.CONFIRMED_FROM:
        how = confirmation_phrase(record["evidence"], register, str(record.get("kind", "")))
    confirmed = (
        _rank(record["verification"]) >= CONFIRMED_RANK
        and _rank(record["confirmation"]) >= CONFIRMED_RANK
    )
    return Entry(ident, rungs, CONFIRMED if confirmed else OPEN, status, "", how)


def _evidence_entry(ident: str, register: Register) -> Entry:
    entry = register.evidence[ident]
    review = entry.get("external_review") or {}
    rungs = f"{entry.get('assurance')}, {entry.get('origin')}"
    if review.get("state") == result_status.DEFECT_FOUND:
        why = f"the read of {review.get('date')} found a defect"
        return Entry(ident, rungs, DEFECT, result_status.INCOMPLETE, why, "")
    if entry.get("replay_status") == result_status.FAILED_REPLAY:
        return Entry(ident, rungs, DEFECT, result_status.INCOMPLETE, "its replay failed", "")
    if entry.get("replay_status") == "passed" and entry.get("origin") in CONFIRMING_ORIGINS:
        how = confirmation_phrase([ident], register)
        return Entry(ident, rungs, CONFIRMED, result_status.CONFIRMED, "", how)
    read = review.get("state") == "informally-verified"
    status = result_status.REVIEWED if read else result_status.RECORDED
    return Entry(ident, rungs, OPEN, status, "", "")


def mapped_ids(result: Mapped) -> list[str]:
    return [*result.get("register", ()), *result.get("evidence", ())]


def result_state(result: Mapped, register: Register) -> ResultState:
    """One reported result's state and whether it is settled.

    The register entries a result maps to are the result; the evidence entries are what
    was checked of it. So a result is confirmed when every register entry it maps to is
    confirmed, or, mapping to evidence alone, when one of those entries is a passing
    confirmation; a report entry beside a confirmed register entry does not hold it open.
    A defect or refutation on any mapped entry decides it. A reported defect
    (`defect: true`) is settled when the record holds the defect against one of the entries
    it names. A result not registered is settled unless it is queued.
    """
    key, claim = str(result["key"]), str(result["claim"])
    if "not_registered" in result:
        queued = bool(result["queued"])
        state = QUEUED if queued else NOT_REGISTERED
        return ResultState(key, claim, (), state, not queued, str(result["not_registered"]))
    entries = tuple(entry_state(ident, register) for ident in mapped_ids(result))
    states = {entry.state for entry in entries}
    if result.get("defect"):
        state = DEFECT if states & {DEFECT, REFUTED} else OPEN
        return ResultState(key, claim, entries, state, state == DEFECT, "")
    deciding = [entry.state for entry in entries if entry.id.startswith("T-")]
    if REFUTED in states:
        state = REFUTED
    elif DEFECT in states:
        state = DEFECT
    elif (deciding and set(deciding) == {CONFIRMED}) or (not deciding and CONFIRMED in states):
        state = CONFIRMED
    else:
        state = OPEN
    return ResultState(key, claim, entries, state, state in {CONFIRMED, REFUTED}, "")


def _current(entry: Entry) -> dict[str, str]:
    """An entry's state in the fields a reply's `reported` item can state."""
    held = {"status": REFUTED if entry.state == REFUTED else entry.status}
    if entry.id.startswith("T-"):
        held["verification"], held["confirmation"] = entry.rungs.split("/")
    return held


def _stated(fields: Mapping[str, object]) -> str:
    rungs = "/".join(
        str(fields[key]) for key in ("verification", "confirmation") if key in fields
    )
    return ", ".join(part for part in (rungs, str(fields.get("status") or "")) if part)


def _moved(entry: Entry, item: Mapped) -> tuple[str, str] | None:
    """What a reply stated of an entry and what holds now, where the two differ.

    Only the fields the reply stated are compared: an acknowledgement that named an id
    and no rung has not been overtaken by a rung."""
    held = _current(entry)
    keys = [
        key for key in ("verification", "confirmation", "status") if key in item and key in held
    ]
    if all(item[key] == held[key] for key in keys):
        return None
    return _stated(item), _stated({key: held[key] for key in keys})


def _last_mention(replies: Sequence[Mapped], key: str) -> tuple[Mapped | None, list[Mapped]]:
    for reply in reversed(replies):
        items = [item for item in reply.get("reported", ()) if item.get("result") == key]
        if items:
            return reply, items
    return None, []


def _describe(state: ResultState) -> str:
    named = ", ".join(
        f"{entry.id} at {entry.rungs}"
        if entry.id.startswith("T-")
        else f"{entry.id} ({entry.rungs})"
        for entry in state.entries
    )
    return f"{named}: {state.state}" if named else state.state


def _uncorrected(replies: Sequence[Mapped]) -> list[tuple[str, str]]:
    """The outdated statements no later reply has said it corrects, with their dates."""
    corrected = {str(url) for reply in replies for url in reply.get("corrects", ())}
    return [
        (str(reply["date"]), str(statement))
        for reply in replies
        if str(reply["url"]) not in corrected
        for statement in reply.get("outdated", ())
    ]


def corrections(issue: Mapped, states: Sequence[ResultState]) -> list[str]:
    """What earlier replies on an issue said that the record no longer holds, for the author.

    The same facts `replies_due` reports, in the words a follow-up uses: an outdated
    statement, an id the result no longer has, a rung or status it no longer reads."""
    replies = list(issue.get("replies", ()))
    found = [
        f"The reply of {date} said {statement}." for date, statement in _uncorrected(replies)
    ]
    for state in states:
        reply, items = _last_mention(replies, state.key)
        if reply is None:
            continue
        named = {str(item["id"]): item for item in items if "id" in item}
        for entry in state.entries:
            item = named.get(entry.id)
            if item is None:
                continue
            if item.get("as") and item["as"] != entry.id:
                said = f"The reply of {reply['date']}"
                found.append(f"{said} named this result {item['as']}; it is {entry.id}.")
            if moved := _moved(entry, item):
                said = f"The reply of {reply['date']} gave {entry.id} as {moved[0]}"
                found.append(f"{said}; it now reads {moved[1]}.")
    return found


def replies_due(issue: Mapped, states: Sequence[ResultState]) -> list[str]:
    """Why a reply is due on an issue, one reason a line, or none."""
    replies = list(issue.get("replies", ()))
    if issue["triage"] == "pending":
        return [] if replies else ["an acknowledgement, once triage has mapped the claims"]
    due: list[str] = []
    if not replies:
        due.append("an acknowledgement: nothing has been posted on this issue")
    due.extend(
        f"a follow-up: the reply of {date} said {statement}"
        for date, statement in _uncorrected(replies)
    )
    for state in states:
        reply, items = _last_mention(replies, state.key)
        if reply is None:
            if state.entries:
                due.append(f"{state.key}: {_describe(state)}, and no reply has said so")
            elif state.state == QUEUED:
                due.append(f"{state.key}: an acknowledgement; not yet imported")
            else:
                due.append(f"{state.key}: say why it is not registered ({state.reason})")
            continue
        when = reply["date"]
        named = {str(item["id"]): item for item in items if "id" in item}
        if state.entries and not named:
            due.append(f"{state.key}: {_describe(state)} since the reply of {when}")
            continue
        for entry in state.entries:
            item = named.get(entry.id)
            if item is None:
                due.append(f"{state.key}: {entry.id} was not named in the reply of {when}")
                continue
            if item.get("as") and item["as"] != entry.id:
                due.append(f"{state.key}: the reply of {when} named {entry.id} as {item['as']}")
            if moved := _moved(entry, item):
                due.append(
                    f"{state.key}: the reply of {when} stated {entry.id} at {moved[0]}; "
                    f"it is now {moved[1]}"
                )
    return due


def closeable(issue: Mapped, states: Sequence[ResultState]) -> tuple[bool, list[str]]:
    """Whether the issue can be closed with a final comment, and what stops it."""
    blockers: list[str] = []
    if issue["triage"] == "pending":
        blockers.append("triage is pending")
    blockers.extend(f"{state.key} is {state.state}" for state in states if not state.settled)
    blockers.extend(
        f"asked: {ask['what']}" for ask in issue.get("asks", ()) if ask["state"] == "queued"
    )
    return not blockers, blockers


def issue_state(issue: Mapped, register: Register) -> IssueState:
    states = tuple(result_state(result, register) for result in issue.get("results", ()))
    ready, blockers = closeable(issue, states)
    return IssueState(
        number=int(issue["number"]),
        results=states,
        replies_due=tuple(replies_due(issue, states)),
        closeable=ready,
        blockers=tuple(blockers),
    )


def _reply_problems(issue: Mapped, repository: str, ids: dict[str, set[str]]) -> list[str]:
    number = issue["number"]
    problems: list[str] = []
    previous = str(issue["opened"])
    seen: set[str] = set()
    for reply in issue.get("replies", ()):
        url = str(reply["url"])
        match = _REPLY_URL.match(url)
        if not match or match.group(1) != repository or int(match.group(2)) != number:
            problems.append(f"#{number}: reply {url} is not a comment on this issue")
        if url in seen:
            problems.append(f"#{number}: reply {url} is recorded twice")
        seen.add(url)
        if str(reply["date"]) < previous:
            problems.append(f"#{number}: reply {url} is dated before the one above it")
        previous = str(reply["date"])
        problems.extend(
            f"#{number}: reply {url} corrects {earlier}, which is not an earlier reply here"
            for earlier in reply.get("corrects", ())
            if earlier not in seen or earlier == url
        )
        for item in reply.get("reported", ()):
            key = item.get("result")
            if key not in ids:
                problems.append(f"#{number}: reply {url} reports unknown result {key!r}")
                continue
            if "id" in item and item["id"] not in ids[key]:
                maps = ", ".join(sorted(ids[key])) or "nothing"
                problems.append(
                    f"#{number}: reply {url} reports {item['id']} for {key}, which maps to "
                    f"{maps}; record a renumbered id as `as`"
                )
            if "as" in item and "id" not in item:
                problems.append(f"#{number}: reply {url} gives `as` without the id it means")
    return problems


def problems(record: Mapped, register: Register) -> list[str]:
    """What is wrong with the record: its schema, and every id it names.

    Every register and evidence id must exist; each reply must be a comment on its own
    issue, in date order, and speak only of the issue's results by their current ids.
    """
    found = schema_errors(record)
    if found:
        return found
    repository = str(record["repository"])
    numbers = [issue["number"] for issue in record["issues"]]
    found.extend(
        f"issue #{number} is recorded twice"
        for number in sorted({n for n in numbers if numbers.count(n) > 1})
    )
    for issue in record["issues"]:
        number = issue["number"]
        if issue.get("closed") and str(issue["closed"]) < str(issue["opened"]):
            found.append(f"#{number}: closed before it was opened")
        ids: dict[str, set[str]] = {}
        for result in issue.get("results", ()):
            key = str(result["key"])
            if key in ids:
                found.append(f"#{number}: result key {key!r} is used twice")
            ids[key] = set(mapped_ids(result))
            found.extend(
                f"#{number} {key}: {ident} is not in results.yaml"
                for ident in result.get("register", ())
                if ident not in register.results
            )
            found.extend(
                f"#{number} {key}: {ident} is not in evidence.yaml"
                for ident in result.get("evidence", ())
                if ident not in register.evidence
            )
        found.extend(_reply_problems(issue, repository, ids))
    return found


def ids_on_main(paths: Sequence[str] = ("packing/frontier/results.yaml",)) -> set[str] | None:
    """The register and evidence ids `origin/main` holds, or None without that ref."""
    held: set[str] = set()
    for path in paths:
        shown = subprocess.run(
            ("git", "show", f"origin/main:{path}"),
            cwd=REPO,
            capture_output=True,
            text=True,
            check=False,
        )
        if shown.returncode:
            return None
        held.update(_ID_ON_MAIN.findall(shown.stdout))
    return held


def head_on_main() -> bool:
    """Whether HEAD is contained in origin/main, which `--draft` requires."""
    probe = subprocess.run(
        ("git", "merge-base", "--is-ancestor", "HEAD", "origin/main"),
        cwd=REPO,
        capture_output=True,
        check=False,
    )
    return probe.returncode == 0


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def summary_lines(record: Mapped, register: Register) -> list[str]:
    """One line an issue: its state, how many results are settled, and what it is owed."""
    lines = []
    for issue in record["issues"]:
        state = issue_state(issue, register)
        settled = sum(result.settled for result in state.results)
        progress = (
            "awaiting triage"
            if issue["triage"] == "pending"
            else f"{settled}/{len(state.results)} settled"
        )
        marks = [
            "reply due" if state.replies_due else "",
            "closeable" if state.closeable and issue["state"] == "open" else "",
        ]
        lines.append(
            f"  #{issue['number']:<4} {issue['state']:<7}{progress:<16}"
            f"{', '.join(mark for mark in marks if mark)}"
        )
    return lines


def report(record: Mapped, register: Register, on_main: set[str] | None) -> list[str]:
    """A Markdown table for each issue, after one summary table over them all."""
    lines = [
        "# Result Requests",
        "",
        "| issue | state | results settled | reply due | closeable |",
        "| --- | --- | --- | --- | --- |",
    ]
    derived = {issue["number"]: issue_state(issue, register) for issue in record["issues"]}
    for issue in record["issues"]:
        state = derived[issue["number"]]
        settled = sum(result.settled for result in state.results)
        triage = "awaiting triage" if issue["triage"] == "pending" else ""
        ready = "yes" if state.closeable else "no"
        lines.append(
            f"| #{issue['number']} | {issue['state']} "
            f"| {triage or f'{settled} of {len(state.results)}'} "
            f"| {'yes' if state.replies_due else 'no'} "
            f"| {'closed' if issue['state'] == 'closed' else ready} |"
        )
    for issue in record["issues"]:
        state = derived[issue["number"]]
        lines.extend(_issue_section(issue, state, on_main))
    return lines


def _on_main(ident: str, on_main: set[str] | None) -> str:
    if on_main is None:
        return "?"
    return "yes" if ident in on_main else "no"


def _issue_section(issue: Mapped, state: IssueState, on_main: set[str] | None) -> list[str]:
    kind = str(issue["kind"]).replace("-", " ")
    closed = f", closed {issue['closed']}" if issue.get("closed") else ""
    lines = [
        "",
        f"## #{issue['number']} {issue['title']}",
        "",
        (
            f"{issue['author']}, opened {issue['opened']}{closed}; {issue['state']}, {kind}. "
            f"Beads: {', '.join(issue['beads']) or 'none'}; answered under "
            f"{issue['answer_bead']}."
        ),
        "",
    ]
    if issue["triage"] == "pending":
        lines += ["Triage is pending.", ""]
    if state.results:
        lines += [
            "| result | maps to | rungs | state | how confirmed | on main |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for result in state.results:
            if not result.entries:
                reason = _cell(result.reason)
                lines.append(
                    f"| {result.key} | {result.state}: {reason} | | {result.state} | | |"
                )
                continue
            for entry in result.entries:
                shown = entry.state if entry.state != OPEN else f"open, {entry.status}"
                lines.append(
                    f"| {result.key} | {entry.id} | {_cell(entry.rungs)} | {shown} "
                    f"| {_cell(entry.how)} | {_on_main(entry.id, on_main)} |"
                )
        lines.append("")
    replies = issue.get("replies", ())
    lines.append(
        "Replies: "
        + (
            "; ".join(f"[{reply['date']} {reply['kind']}]({reply['url']})" for reply in replies)
            if replies
            else "none"
        )
        + "."
    )
    lines.append("")
    if state.replies_due:
        lines.append("Reply due:")
        lines += [f"- {reason}" for reason in state.replies_due]
    else:
        lines.append("Reply due: no.")
    lines.append("")
    if issue["state"] == "closed":
        lines.append("Closeable: the issue is closed.")
    elif state.closeable:
        lines.append("Closeable: yes, with a final comment.")
    else:
        lines.append(f"Closeable: no; {'; '.join(state.blockers)}.")
    lines += ["", f"Close when: {issue['close_when']}"]
    return lines


@dataclass(frozen=True, slots=True)
class BacklogRow:
    """One register entry below `V3` or `C3`, as the backlog lists it."""

    id: str
    rungs: str
    status: str
    activity: str
    beads: tuple[str, ...]
    issues: tuple[int, ...]
    next_rung: str


def backlog_rows(record: Mapped, register: Register) -> list[BacklogRow]:
    """Every register entry below V3 or C3: its next rung, activity, beads and issues.

    The beads are those its `next_rung` and its activity's link name; `devtools.
    intake_sweep` reads the same rows, so the backlog has one definition."""
    serves: dict[str, list[int]] = {}
    for issue in record["issues"]:
        for result in issue.get("results", ()):
            for ident in result.get("register", ()):
                serves.setdefault(ident, [])
                if issue["number"] not in serves[ident]:
                    serves[ident].append(issue["number"])
    rows: list[BacklogRow] = []
    for entry in register.results.values():
        if (
            _rank(entry["verification"]) >= CONFIRMED_RANK
            and _rank(entry["confirmation"]) >= CONFIRMED_RANK
        ):
            continue
        ident = str(entry["id"])
        activity = entry.get("activity") or {}
        doing = result_status.activity_label(activity)
        if doing:
            doing = f"{doing} since {activity.get('since')}"
        text = f"{entry.get('next_rung', '')} {activity.get('link', '')}"
        rows.append(
            BacklogRow(
                id=ident,
                rungs=f"{entry['verification']}/{entry['confirmation']}",
                status=result_status.status(entry, register.evidence),
                activity=doing,
                beads=tuple(sorted(set(BEAD.findall(text)), key=text.index)),
                issues=tuple(serves.get(ident, ())),
                next_rung=str(entry.get("next_rung", "")).strip(),
            )
        )
    return rows


def backlog(record: Mapped, register: Register) -> list[str]:
    """Every register entry below V3 or C3: its next rung, activity, beads and issues."""
    lines = [
        "# Validation Backlog",
        "",
        "| id | rungs | status | activity | beads | issues |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    rows = backlog_rows(record, register)
    for row in rows:
        issues = ", ".join(f"#{number}" for number in row.issues)
        lines.append(
            f"| {row.id} | {row.rungs} | {row.status} | {row.activity} "
            f"| {', '.join(row.beads)} | {issues} |"
        )
    lines.append("")
    for row in rows:
        lines += [f"**{row.id}.** {_cell(row.next_rung)}", ""]
    return lines


def _for_author(text: str) -> str:
    """Register prose with this project's bead references taken out."""
    text = _BEAD_PARENTHESIS.sub("", _BEAD_LEAD.sub("", text.strip()))
    return " ".join(text.split())


def _lead(claim: str) -> str:
    """A claim as the lead of a draft's list item, before its colon: without a closing
    full stop, which would read `.:`. An ellipsis, as in issue 247's repeating decimal
    `3.875000003875...`, is part of the claim and stays."""
    claim = claim.rstrip()
    return claim[:-1] if claim.endswith(".") and not claim.endswith("...") else claim


def _run_here(record: Mapped | None, register: Register) -> str:
    """What the record holds of work done here on a register entry, in words, or nothing.

    `C0` says that nothing is counted toward confirmation, not that nothing ran: a
    complete replay can be retained beside the report entry while it waits for review,
    as T-128's, T-130's and T-131's were. So these words follow the evidence rather than
    the rung: each cited entry whose replay passed, and the `receipts/` directories among
    the entry's artifacts, where a packet keeps the record of each run here.
    """
    if not record:
        return ""
    passed = [
        ref
        for ref in record.get("evidence") or ()
        if (register.evidence.get(ref) or {}).get("replay_status") == "passed"
    ]
    marker = "/receipts/"
    receipts = dict.fromkeys(
        path[: path.index(marker) + len(marker)]
        for path in map(str, record.get("artifacts") or ())
        if marker in path
    )
    parts: list[str] = []
    if passed:
        replays = "replay of {} has" if len(passed) == 1 else "replays of {} have"
        parts.append(f"the {replays.format(', '.join(passed))} passed")
    if receipts:
        where = ", ".join(f"`{path}`" for path in receipts)
        parts.append(f"receipts of what has been run on it here are retained in {where}")
    return " and ".join(parts)


def _plain(entry: Entry, record: Mapped | None, register: Register) -> str:
    """An entry's state in words an author can read without the ladder beside them."""
    if entry.state == CONFIRMED:
        where = f"at {entry.rungs}" if entry.id.startswith("T-") else "here"
        return f"confirmed {where}: {entry.how}"
    if entry.state == REFUTED:
        return f"refuted, by the review at {entry.why}"
    if entry.state == DEFECT:
        return f"a defect is recorded against it: {entry.why}"
    if not entry.id.startswith("T-"):
        return f"recorded as evidence ({entry.rungs}); not yet confirmed here"
    ran = _run_here(record, register) if entry.status == result_status.RECORDED else ""
    words = {
        result_status.RECORDED: "registered as reported"
        if ran
        else "registered as reported: nothing has been read or replayed here yet",
        result_status.REVIEWED: "reviewed: its argument has been read here and no blocking "
        "defect found, and no replay here has passed yet",
        result_status.CONFIRMED: f"replayed, short of confirmation: {entry.how}",
    }[entry.status]
    sentence = f"{words} ({entry.rungs})"
    if ran:
        sentence += f"; {ran}, none of it yet counted toward confirmation"
    activity = (record or {}).get("activity") or {}
    if activity.get("state") == result_status.IN_ANALYSIS:
        sentence += (
            f". Under way here since {activity.get('since')}: {_for_author(activity['what'])}"
        )
    return sentence


def _shown(result: ResultState, reported: Mapped) -> list[Entry]:
    """The entries a draft names for a result: every register entry, and the evidence
    entries that decide something. A report entry beside its register entry adds only
    the word "recorded", which the register entry already says better."""
    if reported.get("defect") or not any(e.id.startswith("T-") for e in result.entries):
        return list(result.entries)
    return [e for e in result.entries if e.id.startswith("T-") or e.state != OPEN]


def _links(states: Sequence[ResultState], register: Register, base: str) -> list[str]:
    paths = [RESULTS_PATH]
    for state in states:
        for entry in state.entries:
            record = register.results.get(entry.id)
            if record is None:
                continue
            paths.extend(str(review["path"]) for review in record.get("reviews") or ())
            values = (record.get("scope") or {}).get("n_values") or []
            if 0 < len(values) <= 6:
                paths.extend(f"packing/frontier/n-{int(n):03d}.md" for n in values)
            else:
                paths.append(STATUS_PATH)
    unique = [path for index, path in enumerate(paths) if path not in paths[:index]]
    return [f"[`{path}`]({base}{path})" for path in unique if (REPO / path).exists()]


def draft(issue: Mapped, register: Register, repository: str) -> str:
    """A status comment for an issue, from the record and the register, ending in the footer."""
    state = issue_state(issue, register)
    base = f"https://github.com/{repository}/blob/main/"
    lines = ["Where this request stands in the record on `main`.", ""]
    if issue["triage"] == "pending":
        lines += ["Thank you. This is being triaged; the claims are not yet mapped.", ""]
    corrected = corrections(issue, state.results)
    if corrected:
        lines += ["**Corrections to earlier replies.**", ""]
        lines += [f"- {line}" for line in corrected]
        lines.append("")
    reported = {str(result["key"]): result for result in issue.get("results", ())}
    imported = [result for result in state.results if result.entries]
    if imported:
        lines += ["**What is registered.**", ""]
        for result in imported:
            if reported[result.key].get("defect"):
                held = (
                    "the record holds this defect"
                    if result.state == DEFECT
                    else "the record does not yet hold this defect"
                )
                lines.append(f"- {_lead(result.claim)}: {held}.")
            else:
                lines.append(f"- {_lead(result.claim)}:")
            for entry in _shown(result, reported[result.key]):
                record = register.results.get(entry.id)
                lines.append(f"  - {entry.id}, {_plain(entry, record, register)}.")
        lines.append("")
    pending = [result for result in state.results if not result.entries]
    if pending:
        lines += ["**Not registered.**", ""]
        lines += [f"- {_lead(result.claim)}: {result.reason}" for result in pending]
        lines.append("")
    queued = _still_queued(issue, state, register)
    if queued:
        lines += ["**What is still queued, and how it will be completed.**", ""]
        lines += [f"- {line}" for line in queued]
        lines.append("")
    links = _links(state.results, register, base)
    if links:
        lines += ["**On `main`.** " + ", ".join(links) + ".", ""]
    if issue["state"] == "closed":
        lines += ["The issue stays closed; this brings what the record says up to date.", ""]
    elif state.closeable:
        lines += [
            "Nothing you asked for is queued, so this issue is closed with this comment.",
            "",
        ]
    else:
        lines += [
            (
                "This issue stays open while anything above is queued, and a reply follows "
                "each change in the record."
            ),
            "",
        ]
    lines.append(FOOTER)
    return "\n".join(lines)


def _still_queued(issue: Mapped, state: IssueState, register: Register) -> list[str]:
    """Each open register entry an unsettled result maps to, with its next rung, once
    however many results map to it; then each ask still queued."""
    queued: list[str] = []
    named: set[str] = set()
    for result in state.results:
        if result.settled:
            continue
        for entry in result.entries:
            record = register.results.get(entry.id)
            if record is None or entry.state != OPEN or entry.id in named:
                continue
            named.add(entry.id)
            queued.append(f"{entry.id}: {_for_author(str(record.get('next_rung', '')))}")
    queued.extend(
        str(ask["what"]) + (f" ({ask['note']})" if ask.get("note") else "")
        for ask in issue.get("asks", ())
        if ask["state"] == "queued"
    )
    return queued


Fetch = Callable[[str], Any]


_PER_PAGE = re.compile(r"[?&]per_page=(\d+)")
#: The largest page GitHub's REST API serves; a larger `per_page` is cut to it.
GITHUB_MAX_PER_PAGE = 100


def _gh_api(path: str) -> Any:
    shown = subprocess.run(("gh", "api", path), capture_output=True, text=True, check=True)
    return json.loads(shown.stdout)


def gh_fetch(path: str, api: Fetch = _gh_api) -> Any:
    """One read-only GitHub API path, every page, through the `gh` CLI.

    A listing is read page by page, by number, until a page comes back short. `gh api
    --paginate` follows the `Link` header instead, whose next page GitHub addresses as
    `repositories/{id}/...`, and a proxy that refuses numeric-id paths, as the agent
    session's did on 2026-10-05, then fails the whole read on the second request.

    The page size must be one GitHub serves, 1 to 100: a page of 100 under `per_page=250`
    would read as the short last page, and `per_page=0` as never short. A first page that
    is not a list is the answer itself, such as an error; a later one would lose the
    pages already read, and is refused with `ValueError`.
    """
    size = _PER_PAGE.search(path)
    if size is None:
        return api(path)
    per_page = int(size.group(1))
    if not 1 <= per_page <= GITHUB_MAX_PER_PAGE:
        raise ValueError(
            f"{path}: per_page={per_page}; GitHub serves 1 to {GITHUB_MAX_PER_PAGE} a page"
        )
    items: list[Any] = []
    for page in itertools.count(1):
        batch = api(f"{path}&page={page}")
        if not isinstance(batch, list):
            if page == 1:
                return batch
            raise ValueError(f"{path}: page {page} is not a list: {str(batch)[:200]}")
        items.extend(batch)
        if len(batch) < per_page:
            break
    return items


def _is_reply(comment: Mapped, owner: str, issue_author: str) -> bool:
    login = str((comment.get("user") or {}).get("login", ""))
    if login == owner:
        return True
    ends = str(comment.get("body") or "").rstrip().endswith(FOOTER_LINE)
    return ends and login != issue_author


def compare_github(record: Mapped, fetch: Fetch = gh_fetch) -> list[str]:
    """Where the live issues differ from the record: issues, states, replies, comments."""
    repository, owner = str(record["repository"]), str(record["owner"])
    differences: list[str] = []
    live = [
        item
        for item in fetch(f"repos/{repository}/issues?state=all&per_page=100")
        if "pull_request" not in item
    ]
    recorded = {issue["number"]: issue for issue in record["issues"]}
    differences.extend(
        f"#{item['number']} is not in the record: {item['title']}"
        for item in live
        if item["number"] not in recorded
    )
    by_number = {item["number"]: item for item in live}
    for number, issue in recorded.items():
        item = by_number.get(number)
        if item is None:
            differences.append(f"#{number} is in the record and not on {repository}")
            continue
        if item["state"] != issue["state"]:
            differences.append(f"#{number} is {item['state']} there and {issue['state']} here")
        comments = fetch(f"repos/{repository}/issues/{number}/comments?per_page=100")
        urls = {str(reply["url"]) for reply in issue.get("replies", ())}
        author = str(issue["author"])
        live_replies = set()
        for comment in comments:
            url = str(comment["html_url"])
            if _is_reply(comment, owner, author):
                live_replies.add(url)
                if url not in urls:
                    differences.append(
                        f"#{number}: reply missing from the record: {url} "
                        f"({comment['user']['login']}, {comment['created_at'][:10]})"
                    )
            elif str(comment["created_at"]) > str(issue["read_through"]):
                differences.append(
                    f"#{number}: unread comment {url} ({comment['user']['login']}, "
                    f"{comment['created_at']})"
                )
        differences.extend(
            f"#{number}: recorded reply not on the issue: {url}"
            for url in sorted(urls - live_replies)
        )
    return differences


def _draft_mode(record: Mapped, register: Register, number: int) -> int:
    issue = next((i for i in record["issues"] if i["number"] == number), None)
    if issue is None:
        print(f"issue #{number} is not in the record", file=sys.stderr)
        return 2
    if not head_on_main():
        print(
            "refusing to draft: HEAD is not contained in origin/main. A T-NNN is "
            "provisional until it merges, and a reply links only to main; fetch and "
            "draft from main.",
            file=sys.stderr,
        )
        return 2
    print(draft(issue, register, str(record["repository"])))
    return 0


def _github_mode(record: Mapped) -> int:
    differences = compare_github(record)
    for difference in differences:
        print(difference)
    print(f"{len(differences)} difference(s) between the record and {record['repository']}")
    return 1 if differences else 0


def _gate_mode(record: Mapped, register: Register) -> int:
    issues = record["issues"]
    print(
        f"result requests: {len(issues)} issues, "
        f"{sum(issue['state'] == 'open' for issue in issues)} open; every id resolves"
    )
    print("\n".join(summary_lines(record, register)))
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n", 1)[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--report", action="store_true", help="a table for each issue")
    mode.add_argument("--backlog", action="store_true", help="entries below V3 or C3")
    mode.add_argument("--draft", type=int, metavar="N", help="a status comment for issue N")
    mode.add_argument("--github", action="store_true", help="compare with the live issues")
    parser.add_argument("--record", type=Path, default=RECORD, help=argparse.SUPPRESS)
    options = parser.parse_args(argv)
    record = load_record(options.record)
    register = load_register()
    found = problems(record, register)
    if found:
        print(
            f"result requests: {len(found)} problem(s) in {options.record.name}",
            file=sys.stderr,
        )
        for problem in found:
            print(f"  {problem}", file=sys.stderr)
        return 1
    if options.report:
        on_main = ids_on_main(
            ("packing/frontier/results.yaml", "packing/frontier/evidence.yaml")
        )
        print("\n".join(report(record, register, on_main)))
    elif options.backlog:
        print("\n".join(backlog(record, register)))
    elif options.draft is not None:
        return _draft_mode(record, register, options.draft)
    elif options.github:
        return _github_mode(record)
    else:
        return _gate_mode(record, register)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
