#!/usr/bin/env python3
"""Render frontier/CERTIFICATE-REACH.md: where the fractional certificate can still go.

The instrument has a ceiling that depends only on ``n`` and the direction net --
``ceil(sqrt(n)) / (1 + D)``, derived in ``sqpack.fractional.certificate.ceiling_side``.
Joining it against the frontier's own bounds answers the question a planner actually
has, which is not "how does the method work" but "which case should the next core run".

Three verdicts come out of the join, and each says something different:

  foreclosed   the ceiling sits at or below the case's existing lower bound, so no
               certificate of this shape can ever improve it. These are exactly the
               cases whose value is the grid bound ceil(sqrt(n)), which is where the
               refuting grid of ceil(sqrt(n))^2 B-squares fits.
  packing      the ceiling clears the best known packing, so the method is not what
               limits this case: the gap to that packing is the whole prize.
  ceiling      the ceiling lands between the two, so it caps the prize below the gap.

The figure to rank on is the last column, which is the most a certificate could add
to the case's lower bound. It is an upper bound on the prize and not a forecast: what
a search actually reaches is set by the covering value at that side, which is lower.

Usage:
    uv run --frozen python -m devtools.render_certificate_reach
    uv run --frozen python -m devtools.render_certificate_reach --check
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from fractions import Fraction

from strif import atomic_output_file

from sqpack.fractional.certificate import ceiling_side_for_net, grid_refutation_order

ROOT = pathlib.Path(__file__).resolve().parent.parent
FRONTIER = ROOT / "frontier"
OUT = FRONTIER / "CERTIFICATE-REACH.md"

BANNER = (
    "<!-- GENERATED by devtools.render_certificate_reach from frontier/n-*.md and "
    "sqpack.fractional.certificate. Do not edit by hand. -->"
)

# Massaccesi's net, which every retained certificate uses: 181 half-tangents from 0 to
# a rational just above tan(pi/8). D is about T / K, so refining the net raises the
# ceiling only as fast as K grows.
ANGLE_LIMIT = Fraction(207107, 500000)
DIRECTION_STEPS = 180
NET = tuple(ANGLE_LIMIT * k / DIRECTION_STEPS for k in range(DIRECTION_STEPS + 1))

LOWER = re.compile(r"verified_lower_bound:\s*\n\s*value: '([^']+)'")
UPPER = re.compile(r"reported_upper_bound:\s*\n\s*value: '([^']+)'")


def cases() -> list[dict]:
    rows = []
    for path in sorted(FRONTIER.glob("n-*.md")):
        n = int(path.stem.split("-")[1])
        text = path.read_text()
        lower = LOWER.search(text)
        upper = UPPER.search(text)
        if not lower:
            continue
        low = float(lower.group(1))
        up = float(upper.group(1)) if upper else None
        ceiling = float(ceiling_side_for_net(n, NET))
        if ceiling <= low:
            verdict, prize = "foreclosed", 0.0
        elif up is not None and ceiling >= up:
            verdict, prize = "packing", up - low
        else:
            verdict, prize = "ceiling", ceiling - low
        rows.append(
            {
                "n": n,
                "order": grid_refutation_order(n),
                "lower": low,
                "upper": up,
                "ceiling": ceiling,
                "verdict": verdict,
                "prize": prize,
            }
        )
    return rows


def render(rows: list[dict]) -> str:
    out = [BANNER, "", "# Where the fractional certificate can still go", ""]
    out += [
        "The most a weighted fractional unavoidable-set certificate could add to each",
        "case's lower bound, at the 181-direction net every retained certificate uses.",
        "`ceiling` is `ceil(sqrt(n)) / (1 + D)`, proved in",
        "`sqpack.fractional.certificate.ceiling_side`.",
        "",
        "**`prize` is what the ceiling allows, not what a search will reach.** The real",
        "limit is the covering value: a certificate exists at side `L` only where the",
        "least total mass that covers every admissible `B`-square falls below `n`, and",
        "that value is well below the ceiling wherever the ceiling is loose. Four",
        "restricted optima have been measured, each an upper bound on the covering value",
        "at its side:",
        "",
        "| side | restricted optimum | from |",
        "| ---: | ---: | --- |",
        "| 3.82 | 11.0000 | converged, n = 11 |",
        "| 3.95 | 11.9706 | retained certificate's mass, n = 12 |",
        "| 3.96 | 11.9936 | converged, n = 12 |",
        "| 4.58 | 16.9628 | converged, n = 17 |",
        "",
        "Those four are the whole of what is known about how the covering value grows.",
        "They are consistent with a quadratic in the side, which would put the reach well",
        "below the `packing` rows below — but four points and a fitted curve are not a",
        "measurement, and no rung has ever been claimed from one. Rank on `prize` to",
        "choose where to look; measure before believing any of it.",
        "",
    ]
    live = [r for r in rows if r["verdict"] != "foreclosed"]
    dead = [r for r in rows if r["verdict"] == "foreclosed"]
    out += [
        f"Of {len(rows)} registered cases, {len(dead)} are foreclosed and {len(live)}",
        "are not. Every foreclosed case sits at the grid bound `ceil(sqrt(n))`, which is",
        "where the refuting grid fits — so the foreclosure costs nothing except where the",
        "case is open and its conjectured value is that bound.",
        "",
        "## Ranked by prize",
        "",
        "| n | m | lower | best packing | ceiling | limited by | prize |",
        "| ---: | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    for r in sorted(live, key=lambda r: -r["prize"]):
        upper = f"{r['upper']:.4f}" if r["upper"] is not None else "—"
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {upper} | "
            f"{r['ceiling']:.4f} | {r['verdict']} | {r['prize']:+.4f} |"
        )
    out += ["", "## Foreclosed", ""]
    out += ["| n | m | lower | ceiling |", "| ---: | ---: | ---: | ---: |"]
    for r in dead:
        out.append(f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {r['ceiling']:.4f} |")
    out += [
        "",
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args()
    text = render(cases())
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            name = OUT.relative_to(ROOT.parent)
            print(f"{name} is stale; run devtools.render_certificate_reach")
            return 1
        return 0
    with atomic_output_file(OUT) as tmp:
        tmp.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
