#!/usr/bin/env python3
"""Render campaign/agenda-map.md from every agenda's frontmatter.

The question this answers is "where are we, and what is still queued" -- the one a
session asks before it picks a slice, and the one that until now was reconstructed by
hand each time from seven agenda files. It was reconstructed wrongly at least once: a
throwaway parser read `status:` where the field is `state:`, and reported all eighty
commitments as unknown (OR-1).

Three cuts, each answering a different question a coordinator actually has:

  live          what may be taken now, in priority order, with its blocker if any
  by agenda     which agendas are closed and which still carry weight
  blocked       what is waiting, and on what -- the dependency edges that matter

Ordering is by agenda then declared priority, never by id: an agenda's queue owns
priority ordering (OR-4), so a map that sorts by id would invent a different one.

Usage:
    uv run --frozen python -m devtools.render_agenda_map
    uv run --frozen python -m devtools.render_agenda_map --check
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from collections import Counter
from dataclasses import dataclass
from typing import Self

from strif import atomic_output_file

from sqpack.yamlio import safe_load

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENDAS = ROOT / "campaign" / "agendas"
OUT = ROOT / "campaign" / "agenda-map.md"

BANNER = (
    "<!-- GENERATED by devtools.render_agenda_map from campaign/agendas/. "
    "Do not edit by hand. -->"
)

# `check_documentation` requires this on every mapped durable document, generated views
# included, so the generator emits it rather than a later hand-edit adding it back.
FOOTER = (
    "<!-- This document follows common-doc-guidelines.md.\n"
    "See github.com/jlevy/practical-prose and review guidelines before editing.\n"
    "-->"
)

# Declared-state order, most actionable first. `tentative` is in the schema and has
# never been used; it is listed so a first use appears in the right place rather than
# being sorted to the end as an unknown.
STATE_ORDER = ("ready", "tentative", "blocked", "stopped", "complete")

# What each state means for a session picking work. The schema names the values; it
# does not say which of them a coordinator may act on, and that is the whole question
# this document exists to answer.
STATE_MEANING = {
    "ready": "may be taken now",
    "tentative": "declared but not yet committed to",
    "blocked": "waiting on a named predecessor",
    "stopped": "abandoned deliberately, with the reason in the agenda",
    "complete": "discharged",
}


@dataclass(frozen=True, slots=True)
class Commitment:
    """One BC cell, flattened out of its agenda for cross-agenda reporting."""

    agenda: str
    agenda_status: str
    doc: str
    id: str
    state: str
    priority: int
    purpose: str
    owner_focus: str
    question: str
    bead: str
    depends_on: tuple[str, ...]

    @classmethod
    def of(cls, agenda: dict, doc: str, item: dict) -> Self:
        return cls(
            agenda=agenda["id"],
            agenda_status=agenda["status"],
            doc=doc,
            id=item["id"],
            state=item["state"],
            priority=item["priority"],
            purpose=item["purpose"],
            owner_focus=item["owner_focus"],
            question=" ".join(item["question"].split()),
            bead=item["bead"],
            depends_on=tuple(item.get("depends_on", [])),
        )

    @property
    def link(self) -> str:
        return f"[`{self.id}`](agendas/{self.doc}#)"


def frontmatter(path: pathlib.Path) -> dict:
    """The YAML frontmatter of a softschema document."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path.name}: no frontmatter")
    end = text.index("\n---", 4)
    return safe_load(text[4:end])


def load() -> list[Commitment]:
    out: list[Commitment] = []
    for path in sorted(AGENDAS.glob("agenda-*.md")):
        agenda = frontmatter(path)["agenda"]
        out += [Commitment.of(agenda, path.name, item) for item in agenda["items"]]
    return out


def state_rank(c: Commitment) -> int:
    return STATE_ORDER.index(c.state) if c.state in STATE_ORDER else len(STATE_ORDER)


def truncate(text: str, width: int) -> str:
    """Shorten to one table cell, on a word boundary, never mid-word."""
    if len(text) <= width:
        return text
    return text[:width].rsplit(" ", 1)[0] + "…"


def render(commitments: list[Commitment]) -> str:
    done = {c.id for c in commitments if c.state == "complete"}
    live = [c for c in commitments if c.state in ("ready", "tentative")]
    blocked = [c for c in commitments if c.state == "blocked"]
    counts = Counter(c.state for c in commitments)

    out = [BANNER, "", "# Agenda map", ""]
    out += [
        (
            f"{len(commitments)} agenda commitments across "
            f"{len({c.agenda for c in commitments})} agendas, as declared in each "
            "agenda's own frontmatter."
        ),
        "Source of truth is [`agendas/`](agendas/); this view is regenerated, never edited.",
        "",
        "An agenda's queue owns priority ordering, so this map preserves each agenda's",
        "order rather than imposing one across them.",
        "",
    ]

    out += ["## The short version", ""]
    tally = ", ".join(f"**{counts[s]}** {s}" for s in STATE_ORDER if counts[s])
    out += [f"- {tally}.", ""]

    # A blocked cell whose predecessors are all discharged is the interesting case: it
    # is takeable and nothing says so, which is exactly how a queue silently stalls.
    unblocked = [c for c in blocked if c.depends_on and set(c.depends_on) <= done]
    if unblocked:
        rows = ", ".join(f"`{c.id}`" for c in unblocked)
        out += [
            (
                f"- **{len(unblocked)} blocked commitments have every predecessor "
                f"complete** and are takeable now: {rows}. A cell whose blocker is "
                "discharged but whose `state` still reads `blocked` is invisible to a "
                "coordinator reading the agenda, which is how a queue stalls without "
                "anyone deciding it should."
            ),
            "",
        ]

    stale = [c for c in blocked if not c.depends_on]
    if stale:
        rows = ", ".join(f"`{c.id}`" for c in stale)
        out += [
            (
                f"- **{len(stale)} blocked commitments name no predecessor** ({rows}), "
                "so what they wait on is prose rather than an edge, and nothing can "
                "tell when it clears."
            ),
            "",
        ]

    out += ["## Live queue", ""]
    if live:
        out += [
            "Commitments a session may take now, in each agenda's declared order.",
            "",
            "| agenda | id | pri | focus | purpose | question | bead |",
            "| --- | --- | ---: | --- | --- | --- | --- |",
        ]
        for c in sorted(live, key=lambda c: (c.agenda, c.priority)):
            out.append(
                f"| {c.agenda} | `{c.id}` | {c.priority} | {c.owner_focus} | {c.purpose} "
                f"| {truncate(c.question, 110)} | `{c.bead}` |"
            )
    else:
        out += ["No commitment is in a takeable state.", ""]
    out += [""]

    out += ["## Blocked, and on what", ""]
    if blocked:
        out += [
            "| agenda | id | pri | waits on | all predecessors complete | question |",
            "| --- | --- | ---: | --- | --- | --- |",
        ]
        for c in sorted(blocked, key=lambda c: (c.agenda, c.priority)):
            deps = ", ".join(f"`{d}`" for d in c.depends_on) or "*(unnamed)*"
            clear = "yes" if c.depends_on and set(c.depends_on) <= done else "no"
            out.append(
                f"| {c.agenda} | `{c.id}` | {c.priority} | {deps} | {clear} "
                f"| {truncate(c.question, 90)} |"
            )
    else:
        out += ["Nothing is blocked.", ""]
    out += [""]

    out += ["## By agenda", ""]
    out += [
        "| agenda | status | " + " | ".join(STATE_ORDER) + " | total |",
        "| --- | --- | " + " | ".join("---:" for _ in STATE_ORDER) + " | ---: |",
    ]
    for name in sorted({c.agenda for c in commitments}):
        rows = [c for c in commitments if c.agenda == name]
        per = Counter(c.state for c in rows)
        cells = " | ".join(str(per[s]) if per[s] else "" for s in STATE_ORDER)
        out.append(f"| {name} | {rows[0].agenda_status} | {cells} | {len(rows)} |")
    out += [""]

    out += ["## What the states mean", ""]
    out += [f"- `{s}` — {STATE_MEANING[s]}" for s in STATE_ORDER]
    out += [""]

    out += [FOOTER]

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    commitments = load()
    text = render(commitments)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(
                f"  {OUT.relative_to(ROOT.parent)} is stale; "
                "run `uv run --frozen python -m devtools.render_agenda_map`",
                file=sys.stderr,
            )
            return 1
        counts = Counter(c.state for c in commitments)
        agendas = len({c.agenda for c in commitments})
        print(
            f"  agenda map matches {len(commitments)} commitments across {agendas} "
            f"agendas: {counts['ready']} ready, {counts['blocked']} blocked, "
            f"{counts['complete']} complete"
        )
        return 0

    with atomic_output_file(OUT) as tmp:
        tmp.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
