#!/usr/bin/env python3
"""Render frontier/CERTIFICATE-REACH.md: where the fractional certificate can still go.

The instrument has a ceiling that depends only on ``n`` and the direction net --
``ceil(sqrt(n)) / (1 + D)``, derived in ``sqpack.fractional.certificate.ceiling_side``.
Joining it against the frontier's own bounds answers the question a planner actually
has, which is not "how does the method work" but "which case should the next core run".

Three verdicts come out of the join, and each says something different:

  foreclosed   the ceiling sits at or below the case's existing lower bound, so no
               certificate of this shape can ever improve it. These are exactly the
               cases whose value is the grid bound ceil(sqrt(n)), which is where the
               refuting grid of ceil(sqrt(n))^2 B-squares fits.
  packing      the ceiling clears the best known packing, so the method is not what
               limits this case: the gap to that packing is the whole prize.
  ceiling      the ceiling lands between the two, so it caps the prize below the gap.

The figure to rank on is the last column, which is the most a certificate could add
to the case's lower bound. It is an upper bound on the prize and not a forecast: what
a search actually reaches is set by the covering value at that side, which is lower.

A second join adds what the record now shows about that gap between prize and
reach: every retained certificate lands within 0.001 of the same fraction of its
case's best known packing. That regularity is measured from three points, not
proved, and the document says so plainly where it appears -- see
`measured_attainment` and `predict_reach` for where the two figures it produces,
`ratio` and `predicted`, come from.

Usage:
    uv run --frozen python -m devtools.render_certificate_reach
    uv run --frozen python -m devtools.render_certificate_reach --check
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from fractions import Fraction

from strif import atomic_output_file

from sqpack.fractional.certificate import (
    ceiling_side_for_net,
    grid_refutation_order,
    least_size_certified,
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
FRONTIER = ROOT / "frontier"
CASES = ROOT / "cases"
OUT = FRONTIER / "CERTIFICATE-REACH.md"

BANNER = (
    "<!-- GENERATED by devtools.render_certificate_reach from frontier/n-*.md and "
    "sqpack.fractional.certificate. Do not edit by hand. -->"
)

# Massaccesi's net, which every retained certificate uses: 181 half-tangents from 0 to
# tan(pi/8) rounded down. D is about T / K, so refining the net raises the ceiling only
# as fast as K grows.
ANGLE_LIMIT = Fraction(207107, 500000)
DIRECTION_STEPS = 180
NET = tuple(ANGLE_LIMIT * k / DIRECTION_STEPS for k in range(DIRECTION_STEPS + 1))

LOWER = re.compile(r"verified_lower_bound:\s*\n\s*value: '([^']+)'")
UPPER = re.compile(r"reported_upper_bound:\s*\n\s*value: '([^']+)'")


def cases() -> list[dict]:
    rows = []
    for path in sorted(FRONTIER.glob("n-*.md")):
        n = int(path.stem.split("-")[1])
        text = path.read_text()
        lower = LOWER.search(text)
        upper = UPPER.search(text)
        if not lower:
            continue
        low = float(lower.group(1))
        up = float(upper.group(1)) if upper else None
        ceiling = float(ceiling_side_for_net(n, NET))
        if ceiling <= low:
            verdict, prize = "foreclosed", 0.0
        elif up is not None and ceiling >= up:
            verdict, prize = "packing", up - low
        else:
            verdict, prize = "ceiling", ceiling - low
        rows.append(
            {
                "n": n,
                "order": grid_refutation_order(n),
                "lower": low,
                "upper": up,
                "ceiling": ceiling,
                "verdict": verdict,
                "prize": prize,
            }
        )
    return rows


def retained_certificates() -> list[dict]:
    """Every retained first-party certificate, found by globbing the case packages.

    A case package's own ``__main__.py`` always replays ``certificate.json`` as the
    rung currently in force -- every package's ``replay.py`` sets
    ``CERTIFICATE_PATH = Path(__file__).with_name("certificate.json")``, and a
    package that also keeps a weaker historical rung stores it under a different
    filename (``certificate-<side>.json``), never this one. So globbing straight to
    that filename, rather than importing each package's Python, finds exactly the
    rungs the register currently holds.

    The row is keyed by ``least_size_certified``, not by the JSON's own ``n`` field:
    the package named ``n20_fractional_certificate`` carries a certificate recorded
    at ``n = 20``, but its mass of 946131/50000 = 18.922620 certifies every integer
    above that, so the case it moves first -- and the one this document keys it to
    -- is ``n = 19``.
    """
    rows = []
    for path in sorted(CASES.glob("n*_fractional_certificate/certificate.json")):
        record = json.loads(path.read_text())
        total_mass = Fraction(str(record["total_mass"]))
        outer_side = Fraction(str(record["outer_side"]))
        rows.append(
            {
                "package": path.parent.name,
                "n": least_size_certified(total_mass),
                "lower": float(outer_side),
            }
        )
    return rows


def measured_attainment(rows: list[dict]) -> list[dict]:
    """Join every retained certificate against its case's ceiling and best packing.

    ``rows`` is `cases`'s output. A retained certificate's own target ``n`` (from
    `retained_certificates`) picks the row that carries its ceiling and best known
    packing, exactly as every other figure in this document is derived rather than
    looked up by hand. ``binds`` names whichever of the two is the tighter cap, and
    ``ratio`` is the retained lower bound divided by that binding value -- against
    the best packing where the packing binds, against the ceiling where it does not.
    """
    by_n = {row["n"]: row for row in rows}
    out = []
    for cert in retained_certificates():
        case = by_n[cert["n"]]
        best_packing = case["upper"]
        ceiling = case["ceiling"]
        lower = cert["lower"]
        if best_packing is None:
            raise ValueError(f"n = {cert['n']}: retained certificate has no best packing")
        if ceiling >= best_packing:
            binds, ratio = "packing", lower / best_packing
        else:
            binds, ratio = "ceiling", lower / ceiling
        out.append(
            {
                "n": cert["n"],
                "package": cert["package"],
                "lower": lower,
                "best_packing": best_packing,
                "ceiling": ceiling,
                "binds": binds,
                "ratio": ratio,
            }
        )
    return sorted(out, key=lambda r: r["n"])


def mean_packing_ratio(measured: list[dict]) -> float:
    """The mean ``ratio`` over certificates the best packing binds, not the ceiling.

    ``n = 12`` is the case this excludes: its ceiling sits below its best packing, so
    its ratio measures how close the certificate came to the method's own ceiling,
    not to a packing, and averaging it in would mix two different questions.
    """
    packing_bound = [row["ratio"] for row in measured if row["binds"] == "packing"]
    if not packing_bound:
        raise ValueError("no packing-limited retained certificates to average")
    return sum(packing_bound) / len(packing_bound)


def predicted_reach(rows: list[dict], ratio: float) -> list[dict]:
    """Every live row plus what the mean packing ratio would extrapolate to.

    ``predicted`` is ``min(ratio * best_packing, ceiling)`` -- the mean ratio applied
    to the case's own best packing, capped at the method's own ceiling so the
    extrapolation never claims more than `ceiling_side_for_net` allows. ``predicted
    gain`` is ``predicted - lower``, clamped at zero: a case already past its
    prediction (as a case with no prize at all would be) gets no negative row.
    A row with no recorded best packing is dropped rather than given a fabricated
    prediction; every live case in the retained register carries one today.
    """
    out = []
    for row in rows:
        best_packing = row["upper"]
        if best_packing is None:
            continue
        predicted = min(ratio * best_packing, row["ceiling"])
        out.append(
            {
                **row,
                "predicted": predicted,
                "predicted_gain": max(predicted - row["lower"], 0.0),
            }
        )
    return out


def render(rows: list[dict]) -> str:
    out = [BANNER, "", "# Where the fractional certificate can still go", ""]
    out += [
        "The most a weighted fractional unavoidable-set certificate could add to each",
        "case's lower bound, at the 181-direction net every retained certificate uses.",
        "`ceiling` is `ceil(sqrt(n)) / (1 + D)`, proved in",
        "`sqpack.fractional.certificate.ceiling_side`.",
        "",
        "**`prize` is what the ceiling allows, not what a search will reach.** The real",
        "limit is the covering value: a certificate exists at side `L` only where the",
        "least total mass that covers every admissible `B`-square falls below `n`, and",
        "that value is well below the ceiling wherever the ceiling is loose. Four",
        "restricted optima have been measured, each an upper bound on the covering value",
        "at its side:",
        "",
        "| side | restricted optimum | from |",
        "| ---: | ---: | --- |",
        "| 3.82 | 11.0000 | converged, n = 11 |",
        "| 3.95 | 11.9706 | retained certificate's mass, n = 12 |",
        "| 3.96 | 11.9936 | converged, n = 12 |",
        "| 4.58 | 16.9628 | converged, n = 17 |",
        "",
        "Those four are the whole of what is known about how the covering value grows.",
        "They are consistent with a quadratic in the side, which would put the reach well",
        "below the `packing` rows below — but four points and a fitted curve are not a",
        "measurement, and no rung has ever been claimed from one. Rank on `prize` to",
        "choose where to look; measure before believing any of it.",
        "",
    ]
    live = [r for r in rows if r["verdict"] != "foreclosed"]
    dead = [r for r in rows if r["verdict"] == "foreclosed"]
    out += [
        f"Of {len(rows)} registered cases, {len(dead)} are foreclosed and {len(live)}",
        "are not. Every foreclosed case sits at the grid bound `ceil(sqrt(n))`, which is",
        "where the refuting grid fits — so the foreclosure costs nothing except where the",
        "case is open and its conjectured value is that bound.",
        "",
        "## Ranked by prize",
        "",
        "| n | m | lower | best packing | ceiling | limited by | prize |",
        "| ---: | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    for r in sorted(live, key=lambda r: -r["prize"]):
        upper = f"{r['upper']:.4f}" if r["upper"] is not None else "—"
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {upper} | "
            f"{r['ceiling']:.4f} | {r['verdict']} | {r['prize']:+.4f} |"
        )

    measured = measured_attainment(rows)
    ratio = mean_packing_ratio(measured)
    out += [
        "",
        "## Measured attainment",
        "",
        "Every retained first-party fractional certificate, joined against its case's",
        "best packing and ceiling. `ratio` is the retained lower bound divided by",
        "whichever of the two `limited by` names -- the only honest denominator, since",
        "the other one was never in reach.",
        "",
        "| n | package | retained lower bound | best packing | ceiling",
        "| limited by | ratio |",
        "| ---: | --- | ---: | ---: | ---: | --- | ---: |",
    ]
    for r in measured:
        out.append(
            f"| {r['n']} | {r['package']} | {r['lower']:.4f} | {r['best_packing']:.4f} | "
            f"{r['ceiling']:.4f} | {r['binds']} | {r['ratio']:.5f} |"
        )
    out += [
        "",
        "## What three points would predict, if the ratio held",
        "",
        f"**This is an extrapolation from three points, not a measurement.** The three",
        "packing-limited rows above -- n = 11, n = 17, n = 19 -- land inside a band",
        "0.001 wide, and their mean is the `ratio` this section's numbers all come",
        f"from: `{ratio:.5f}`. That the three numbers are exact rationals decided by",
        "an exact verifier does not make their mean a rate. No rung in this register",
        "has ever been claimed from a fitted curve, and this one is not the exception:",
        "it is offered here as a place to look, not as a result.",
        "",
        "The ratio is also not purely about how good a covering value the method can",
        "reach -- it is an observation about where searches were stopped as much as",
        "about where they could go. Two of the three runs behind it were halted on",
        "projected cost before they answered whether their side could be pushed",
        "higher; only one ran its covering search to a converged optimum (see each",
        "case's `next_rung` in `frontier/results.yaml`). A ratio built half from where",
        "searches were stopped and half from where they could go is not a rate to",
        "spend a rung's confidence on.",
        "",
        "`predicted` below is `min(ratio * best_packing, ceiling)` and `predicted",
        "gain` is `predicted - lower`, clamped at zero. Read them as where to look",
        "next, never as a result standing in for one: the number to act on when a",
        "case is actually run is still the restricted optimum a converged search",
        "reaches, not this extrapolation.",
        "",
        "## Ranked by predicted gain",
        "",
        "| n | m | lower | best packing | ceiling | limited by | prize | predicted",
        "| predicted gain |",
        "| ---: | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: |",
    ]
    for r in sorted(predicted_reach(live, ratio), key=lambda r: -r["predicted_gain"]):
        upper = f"{r['upper']:.4f}" if r["upper"] is not None else "—"
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {upper} | "
            f"{r['ceiling']:.4f} | {r['verdict']} | {r['prize']:+.4f} | "
            f"{r['predicted']:.4f} | {r['predicted_gain']:+.4f} |"
        )
    out += ["", "## Foreclosed", ""]
    out += ["| n | m | lower | ceiling |", "| ---: | ---: | ---: | ---: |"]
    for r in dead:
        out.append(f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {r['ceiling']:.4f} |")
    out += [
        "",
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args()
    text = render(cases())
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            name = OUT.relative_to(ROOT.parent)
            print(f"{name} is stale; run devtools.render_certificate_reach")
            return 1
        return 0
    with atomic_output_file(OUT) as tmp:
        tmp.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
