#!/usr/bin/env python3
"""Generate `frontier/INVENTORY.md`: what this repository knows, and on whose authority.

`STATUS.md` answers what the bounds are. This answers a different question that the
register could always support and never displayed: **which of these results are ours?**

Four independent facts decide that, and conflating any two of them loses the answer:

- **assurance** -- is there an argument that admits no error, or a computation that could
  be off? That is the whole of the ladder; the rest is which kind.
- **method** -- exact arithmetic decides equality, an interval encloses and can only
  decide strict inequalities, a proof is a proof, and a numerical check is a measurement.
- **origin**, with **external_review** -- did the work happen here, or are we relying on
  someone else's argument, and if theirs, has anyone here read it?
- **novelty** -- is the *result* ours, or are we confirming a published one?

The fourth is about the result and the third is about the verification, which is the
distinction most easily lost: certifying someone else's bound exactly is real work and is
not the same as establishing a new bound.

Usage, from `packing/`:
    uv run --frozen --all-extras --group dev python -m devtools.render_evidence_inventory \
        --update
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from sqpack.yamlio import safe_load

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "frontier" / "evidence.yaml"
FRONTIER = ROOT / "frontier"
OUTPUT = FRONTIER / "INVENTORY.md"

#: Every block on a case record that can name evidence. Counting citations across all
#: hundred is what turns "this record is load-bearing" from an impression into a number,
#: and the numbers are not close: one record carries 88 cases and the next carries 2.
EVIDENCE_BLOCKS = (
    "reported_upper_bound",
    "verified_upper_bound",
    "reported_lower_bound",
    "verified_lower_bound",
    "rigidity",
)

FORMAL_METHODS = {
    "exact-algebraic",
    "interval-certified",
    "published-proof",
    "proof-audited",
    "proof-assistant-checked",
}
EXTERNAL_ORIGINS = {"external", "independently-external"}

#: What each method can actually conclude, which the assurance level alone does not say.
#: Both of the first two are formal and they are not interchangeable: an enclosure of
#: positive width decides strict inequalities and never an equality, so it can prove two
#: squares do not overlap and cannot prove they touch.
DECIDES = {
    "exact-algebraic": "equalities and inequalities, no tolerance",
    "interval-certified": "strict inequalities only",
    "numerical-multiprecision": "nothing formally; a measurement at a tolerance",
    "numerical-f64": "nothing formally; a measurement at a tolerance",
    "published-proof": "whatever its theorem states",
    "proof-audited": "whatever its theorem states",
    "proof-assistant-checked": "its theorem, against a named kernel",
}


def scope_text(record: dict) -> str:
    scope = record.get("scope") or {}
    if values := scope.get("n_values"):
        return ", ".join(str(v) for v in values) if len(values) <= 4 else f"{len(values)} sizes"
    if (low := scope.get("n_min")) is not None:
        return f"{low} to {scope.get('n_max', '?')}"
    return "-"


def ours(record: dict) -> bool:
    """Was the argument made here? External proofs are not, however well reviewed."""
    return record.get("origin") not in EXTERNAL_ORIGINS and record.get("origin") is not None


def dependents() -> Counter:
    """How many of the hundred cases cite each evidence record, over every block."""
    counts: Counter = Counter()
    for path in sorted(FRONTIER.glob("n-*.md")):
        case = safe_load(path.read_text(encoding="utf-8").split("---\n")[1])["packing"]
        cited = {
            ref
            for block in EVIDENCE_BLOCKS
            if isinstance(case.get(block), dict)
            for ref in (case[block].get("evidence") or [])
        }
        counts.update(cited)
    return counts


def render() -> str:
    records = safe_load(EVIDENCE.read_text(encoding="utf-8"))["evidence"]
    load = dependents()

    lines = [
        "<!-- GENERATED by devtools.render_evidence_inventory. Do not edit by hand. -->",
        "",
        "# Evidence inventory",
        "",
        "What this repository knows about square packing, and on whose authority.",
        "[`STATUS.md`](STATUS.md) says what the bounds are; this says which of them are",
        "ours, which rest on someone else's argument, and how far each has been checked.",
        "",
    ]

    formal = [r for r in records if r.get("assurance") == "verified"]
    own_formal = [r for r in formal if ours(r)]
    external = [r for r in records if r.get("origin") in EXTERNAL_ORIGINS]
    unreviewed = [
        r for r in external if (r.get("external_review") or {}).get("state") == "not-reviewed"
    ]
    novel = [r for r in records if r.get("novelty") in {"apparently-novel", "confirmed-novel"}]
    unassessed = [r for r in records if "novelty" not in r]

    lines += [
        "## The short version",
        "",
        (
            f"- **{len(records)}** evidence records. **{len(formal)}** are formal; "
            f"**{len(own_formal)}** of those were established here."
        ),
        (
            f"- **{len(external)}** rest on an argument made elsewhere, of which "
            f"**{len(unreviewed)}** have been read by nobody here."
        ),
        (
            f"- **{len(novel)}** claim to be first established here. "
            f"**{len(unassessed)}** make no novelty statement at all - not assessed, "
            "which is not the same as not novel."
        ),
        "",
        "A formal claim on an unread external proof is still formal: the proof proves its",
        "claim whether or not we read it. The count above is not a doubt about those",
        "results, it is a statement about what this repository has itself examined.",
        "",
        "## Every record",
        "",
        (
            "| evidence | cases | claim | assurance | method decides "
            "| whose work | read here | novelty |"
        ),
        "| --- | ---: | --- | --- | --- | --- | --- | --- |",
    ]

    for record in records:
        decides = DECIDES.get(record.get("method"), "-")
        whose = "here" if ours(record) else ("elsewhere" if record.get("origin") else "-")
        review = (record.get("external_review") or {}).get("state", "-")
        novelty = record.get("novelty") or "*not assessed*"
        lines.append(
            f"| `{record['id']}` | {load.get(record['id'], 0)} "
            f"| {record.get('claim', '-')} | {record.get('assurance', '-')} "
            f"| {decides} | {whose} | {review} | {novelty} |"
        )

    lines += ["", "## What the register rests on", ""]
    for label, counter in (
        ("assurance", Counter(str(r.get("assurance")) for r in records)),
        ("method", Counter(str(r.get("method") or "reported") for r in records)),
        ("novelty", Counter(str(r.get("novelty") or "not assessed") for r in records)),
    ):
        parts = ", ".join(f"{k} {v}" for k, v in sorted(counter.items()))
        lines.append(f"- **{label}**: {parts}")

    lines += [
        "",
        (
            "The `cases` column is how many of the hundred frontier records cite each "
            "piece of evidence, and it is the reason to read this table rather than count "
            "records. Ranked below are the *formal* records only: a `reported` record "
            "cited by ninety-eight cases is the catalogue everyone reports from and is "
            "labelled as such, which is the register working rather than risk. The risk is "
            "a verified claim resting on an argument nobody has examined."
        ),
        "",
    ]

    lines += ["## What this repository established itself", ""]
    lines += [
        (
            "Claims marked `apparently-novel`: first established here as far as the "
            "archived corpus shows, ordered by how much of the frontier each carries. "
            "The label is a statement about a search, never a claim of priority, so each "
            "names the corpus it was searched against and that corpus's known holes."
        ),
        "",
        "| result | n | what is new | cases | assurance |",
        "| --- | --- | --- | ---: | --- |",
    ]
    own = [r for r in records if r.get("novelty") == "apparently-novel"]
    own.sort(key=lambda r: (-load.get(r["id"], 0), r["id"]))
    for record in own:
        basis = record.get("novelty_basis") or {}
        lines.append(
            f"| `{record['id']}` | {scope_text(record)} "
            f"| {basis.get('novel_object', '-')} "
            f"| {load.get(record['id'], 0)} | {record.get('assurance', '-')} |"
        )
    lines += [
        "",
        (
            "The `n` column is what each covers and `cases` is how many frontier records "
            "cite it, which are different numbers: a screen can span eighty sizes and be "
            "cited by none, because a screen reports structure rather than settling a "
            "bound."
        ),
        "",
    ]

    # Rank the FORMAL records only. A `reported` record cited by ninety-eight cases is the
    # catalogue everyone reports from, and it is labelled reported -- that is not
    # concentrated risk, it is the register working. The risk is a *verified* claim resting
    # on an argument nobody has examined, so that is what this ranks.
    ranked = [(load.get(r["id"], 0), r) for r in records if r.get("assurance") == "verified"]
    ranked.sort(key=lambda pair: -pair[0])
    lines += ["| evidence | cases | whose work | read here |", "| --- | ---: | --- | --- |"]
    for count, record in ranked[:5]:
        whose = "here" if ours(record) else ("elsewhere" if record.get("origin") else "-")
        review = (record.get("external_review") or {}).get("state", "-")
        lines.append(f"| `{record['id']}` | {count} | {whose} | {review} |")

    # The narrative is about the most-cited record we did NOT produce. A verified record of
    # our own being cited ninety-three times is the grid bound doing its job; a verified
    # record from elsewhere being cited eighty-eight times is a dependency.
    borrowed = [pair for pair in ranked if not ours(pair[1])]
    top_count, top = borrowed[0] if borrowed else ranked[0]
    state = (top.get("external_review") or {}).get("state")
    read_line = {
        "not-reviewed": (
            "It is an external proof nobody here has read, which makes it simultaneously "
            "the most load-bearing argument in the register and the least examined. That "
            "is not a doubt about the result -- a published proof proves its claim whether "
            "or not we read it -- but if one thing here deserved an informal review, the "
            "arithmetic says which."
        ),
        "informally-verified": (
            "It is an external proof, and it has been read here: its record carries the "
            "review, what was re-derived, and the four things that were not. The arithmetic "
            "is what picked it out for reading -- being cited this heavily is the reason to "
            "open an argument, not a reason to trust it."
        ),
        "defect-found": (
            "It is an external proof that was read here and found wanting; its record says "
            "what fails and what was done about it. A record this heavily cited failing "
            "review is the most consequential thing this table can show."
        ),
    }.get(state, "Its review state is not recorded, which the assurance contract refuses.")
    lines += [
        "",
        (
            f"The most-cited argument this repository did not produce is `{top['id']}`, "
            f"carrying {top_count} of the hundred cases. {read_line}"
        ),
        "",
        (
            "`[Stromquist 2003]` is why that matters rather than being a formality: its "
            "`n = 11` argument needed a source-distinct repair, which "
            "`E-n011-repaired-lower` supplies."
        ),
        "",
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update", action="store_true", help="regenerate the inventory")
    mode.add_argument("--check", action="store_true", help="fail if it has drifted")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT.name} has drifted from the evidence register; "
                "run devtools.render_evidence_inventory --update"
            )
            return 1
        records = safe_load(EVIDENCE.read_text(encoding="utf-8"))["evidence"]
        print(f"inventory agrees with {len(records)} evidence records")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
