#!/usr/bin/env python3
"""Generate `frontier/INVENTORY.md`: what this repository knows, and on whose authority.

`STATUS.md` answers what the bounds are. This answers a different question that the
register could always support and never displayed: **which of these results are ours?**

Four independent facts decide that, and conflating any two of them loses the answer:

- **assurance** -- is there an argument that admits no error, or a computation that could
  be off? That is the whole of the ladder; the rest is which kind.
- **method** -- exact arithmetic decides equality, an interval encloses and can only
  decide strict inequalities, a proof is a proof, and a numerical check is a measurement.
- **origin**, with **external_review** -- did the work happen here, or are we relying on
  someone else's argument, and if theirs, has anyone here read it?
- **novelty** -- is the *result* ours, or are we confirming a published one?

The fourth is about the result and the third is about the verification, which is the
distinction most easily lost: certifying someone else's bound exactly is real work and is
not the same as establishing a new bound.

Usage, from `packing/`:
    uv run --frozen --all-extras --group dev python -m devtools.render_evidence_inventory \
        --update
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from sqpack.yamlio import safe_load

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "frontier" / "evidence.yaml"
OUTPUT = ROOT / "frontier" / "INVENTORY.md"

FORMAL_METHODS = {
    "exact-algebraic",
    "interval-certified",
    "published-proof",
    "proof-audited",
    "proof-assistant-checked",
}
EXTERNAL_ORIGINS = {"external", "independently-external"}

#: What each method can actually conclude, which the assurance level alone does not say.
#: Both of the first two are formal and they are not interchangeable: an enclosure of
#: positive width decides strict inequalities and never an equality, so it can prove two
#: squares do not overlap and cannot prove they touch.
DECIDES = {
    "exact-algebraic": "equalities and inequalities, no tolerance",
    "interval-certified": "strict inequalities only",
    "numerical-multiprecision": "nothing formally; a measurement at a tolerance",
    "numerical-f64": "nothing formally; a measurement at a tolerance",
    "published-proof": "whatever its theorem states",
    "proof-audited": "whatever its theorem states",
    "proof-assistant-checked": "its theorem, against a named kernel",
}


def scope_text(record: dict) -> str:
    scope = record.get("scope") or {}
    if values := scope.get("n_values"):
        return ", ".join(str(v) for v in values) if len(values) <= 4 else f"{len(values)} sizes"
    if (low := scope.get("n_min")) is not None:
        return f"{low} to {scope.get('n_max', '?')}"
    return "-"


def ours(record: dict) -> bool:
    """Was the argument made here? External proofs are not, however well reviewed."""
    return record.get("origin") not in EXTERNAL_ORIGINS and record.get("origin") is not None


def render() -> str:
    records = safe_load(EVIDENCE.read_text(encoding="utf-8"))["evidence"]

    lines = [
        "<!-- GENERATED by devtools.render_evidence_inventory. Do not edit by hand. -->",
        "",
        "# Evidence inventory",
        "",
        "What this repository knows about square packing, and on whose authority.",
        "[`STATUS.md`](STATUS.md) says what the bounds are; this says which of them are",
        "ours, which rest on someone else's argument, and how far each has been checked.",
        "",
    ]

    formal = [r for r in records if r.get("assurance") == "verified"]
    own_formal = [r for r in formal if ours(r)]
    external = [r for r in records if r.get("origin") in EXTERNAL_ORIGINS]
    unreviewed = [
        r for r in external if (r.get("external_review") or {}).get("state") == "not-reviewed"
    ]
    novel = [r for r in records if r.get("novelty") in {"apparently-novel", "confirmed-novel"}]
    unassessed = [r for r in records if "novelty" not in r]

    lines += [
        "## The short version",
        "",
        (
            f"- **{len(records)}** evidence records. **{len(formal)}** are formal; "
            f"**{len(own_formal)}** of those were established here."
        ),
        (
            f"- **{len(external)}** rest on an argument made elsewhere, of which "
            f"**{len(unreviewed)}** have been read by nobody here."
        ),
        (
            f"- **{len(novel)}** claim to be first established here. "
            f"**{len(unassessed)}** make no novelty statement at all - not assessed, "
            "which is not the same as not novel."
        ),
        "",
        "A formal claim on an unread external proof is still formal: the proof proves its",
        "claim whether or not we read it. The count above is not a doubt about those",
        "results, it is a statement about what this repository has itself examined.",
        "",
        "## Every record",
        "",
        (
            "| evidence | n | claim | assurance | method decides "
            "| whose work | read here | novelty |"
        ),
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]

    for record in records:
        decides = DECIDES.get(record.get("method"), "-")
        whose = "here" if ours(record) else ("elsewhere" if record.get("origin") else "-")
        review = (record.get("external_review") or {}).get("state", "-")
        novelty = record.get("novelty") or "*not assessed*"
        lines.append(
            f"| `{record['id']}` | {scope_text(record)} "
            f"| {record.get('claim', '-')} | {record.get('assurance', '-')} "
            f"| {decides} | {whose} | {review} | {novelty} |"
        )

    lines += ["", "## What the register rests on", ""]
    for label, counter in (
        ("assurance", Counter(str(r.get("assurance")) for r in records)),
        ("method", Counter(str(r.get("method") or "reported") for r in records)),
        ("novelty", Counter(str(r.get("novelty") or "not assessed") for r in records)),
    ):
        parts = ", ".join(f"{k} {v}" for k, v in sorted(counter.items()))
        lines.append(f"- **{label}**: {parts}")

    lines += [
        "",
        (
            "The external proofs are the concentrated risk, and not equally: "
            "`[Nagamochi 2005]` supplies the lower bound for every `n` from 4 to 100, "
            "which makes it simultaneously the most load-bearing argument here and one "
            "nobody here has worked through. `[Stromquist 2003]` is why that matters "
            "rather than a formality: its `n = 11` argument needed a source-distinct "
            "repair, which `E-n011-repaired-lower` supplies."
        ),
        "",
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update", action="store_true", help="regenerate the inventory")
    mode.add_argument("--check", action="store_true", help="fail if it has drifted")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT.name} has drifted from the evidence register; "
                "run devtools.render_evidence_inventory --update"
            )
            return 1
        records = safe_load(EVIDENCE.read_text(encoding="utf-8"))["evidence"]
        print(f"inventory agrees with {len(records)} evidence records")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
