"""Write the verifiable-claim documents: one self-contained file per certificate.

Each file carries the claim, the theorem and its proof, the standard-library verifier
`verify_claim.py` byte for byte, and the certificate it decides, byte for byte as
well, so a reader can paste that one file into a coding agent or check it by hand
without the rest of the repository. Both files come from one template, so the shared
text cannot drift between them, and `--check` refuses a stale copy; the test suite runs
that check.

Run from `packing/`:

    uv run --frozen --group dev python -m devtools.render_verifiable_claim [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from fractions import Fraction
from pathlib import Path

from devtools.render_certificate_page import (
    REPO,
    TEMPLATES,
    VERIFIER_CLAIM,
    WALKTHROUGH,
    Facts,
    bound_substitutions,
    claim_path,
    decimal,
    derive,
    fill,
    repo_file,
    runtime_phrase,
)

TEMPLATE = TEMPLATES / "verifiable_claim.md"


def frac(value: Fraction) -> str:
    return f"{value.numerator}/{value.denominator}"


def standing(facts: Facts, headline: Facts) -> str:
    """Where this bound stands among the project's, for a reader who has only this file."""
    if facts is headline:
        return "It is the tighter of the two bounds the project proves."
    return "It is the looser of the two bounds the project proves, with the simpler numbers."


def render_claim(facts: Facts, sibling: Facts, headline: Facts) -> str:
    """One document: the template filled with this certificate, its verifier and its file.

    The template names the least covered mass at direction 0, so the certificate's
    declared least has to be the upright direction's, which `derive` computed exactly;
    a certificate whose least cell lies at another direction is refused rather than
    described wrongly.
    """
    declared = Fraction(json.loads(facts.source.read_text(encoding="utf-8"))["least_cell_mass"])
    if facts.least_mass != declared:
        raise SystemExit(
            f"{facts.source.name}: the least cell is not at the upright direction "
            f"({facts.least_mass} there, {declared} declared); the template says it is"
        )
    values = {
        "FILE_NAME": claim_path(facts).name,
        "CERT_NAME": facts.source.name,
        "CERT_URL": repo_file(facts.source),
        "L_FRAC": frac(facts.outer_side),
        "L_DEC": decimal(facts.outer_side),
        "N_ATOMS": str(len(facts.atoms)),
        "N_DIRECTIONS": str(facts.steps + 1),
        "LEAST_FRAC": frac(facts.least_mass),
        "WITNESS_CENTER": f"({frac(facts.witness[0])}, {frac(facts.witness[1])})",
        "RUNTIME": runtime_phrase(facts),
        "STANDING": standing(facts, headline),
        "OTHER_FILE_NAME": claim_path(sibling).name,
        "OTHER_CLAIM_URL": repo_file(claim_path(sibling)),
        "OTHER_L_FRAC": frac(sibling.outer_side),
        "VERIFIER_NAME": VERIFIER_CLAIM.name,
        "VERIFIER_URL": repo_file(VERIFIER_CLAIM),
        "VERIFIER_SOURCE": VERIFIER_CLAIM.read_text(encoding="utf-8").rstrip("\n"),
        "CERTIFICATE_JSON": facts.source.read_text(encoding="utf-8").rstrip("\n"),
        "BEST_PACKING_TEX": bound_substitutions()["BEST_PACKING_TEX"],
    }
    # The banner is prepended here rather than written in the template, so the
    # template itself is not mistaken for a generated view.
    banner = (
        f"<!-- GENERATED by devtools.render_verifiable_claim from "
        f"devtools/templates/{TEMPLATE.name}, {VERIFIER_CLAIM.name} and "
        f"{facts.source.name}. Edit those, then regenerate. -->\n\n"
    )
    text = banner + fill(TEMPLATE.read_text(encoding="utf-8"), values, where=TEMPLATE.name)
    left = {m.group(1) for m in re.finditer(r"\{\{([A-Z_]+)\}\}", text)}
    if left:
        raise SystemExit(f"{TEMPLATE.name}: a substituted value carried {sorted(left)} into it")
    return text


def documents() -> list[tuple[Path, str]]:
    """Every claim document with its fresh text, in walkthrough order."""
    facts = [derive(path) for path in WALKTHROUGH]
    if len(facts) != 2:
        raise SystemExit("each document names its one sibling; the walkthrough has to be two")
    headline = max(facts, key=lambda f: f.outer_side)
    return [
        (claim_path(f), render_claim(f, sibling, headline))
        for f, sibling in ((facts[0], facts[1]), (facts[1], facts[0]))
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if a committed document differs from a fresh render",
    )
    args = parser.parse_args(argv)

    stale = []
    for path, text in documents():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
            continue
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)} ({len(text) / 1024:.0f} KB)")
    for path in stale:
        print(f"{path.relative_to(REPO)} is stale; rerender it", file=sys.stderr)
    if stale:
        return 1
    if args.check:
        print("the verifiable-claim documents are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
