#!/usr/bin/env python3
"""Render campaign/agenda-map.md from every agenda's frontmatter.

The question this answers is "where are we, and what is still queued" -- the one a
session asks before it picks a slice, and the one that until now was reconstructed by
hand each time from seven agenda files. It was reconstructed wrongly at least once: a
throwaway parser read `status:` where the field is `state:`, and reported all eighty
commitments as unknown (OR-1).

Three cuts, each answering a different question a coordinator actually has:

  live          what may be taken now, in priority order, with its blocker if any
  by agenda     which agendas are closed and which still carry weight
  blocked       what is waiting, and on what -- the dependency edges that matter

Ordering is by agenda then declared priority, never by id: an agenda's queue owns
priority ordering (OR-4), so a map that sorts by id would invent a different one.

Usage:
    uv run --frozen python -m devtools.render_agenda_map
    uv run --frozen python -m devtools.render_agenda_map --check
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from collections import Counter
from dataclasses import dataclass
from typing import Self

from strif import atomic_output_file

from sqpack.yamlio import safe_load

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENDAS = ROOT / "campaign" / "agendas"
OUT = ROOT / "campaign" / "agenda-map.md"

BANNER = (
    "<!-- GENERATED by devtools.render_agenda_map from campaign/agendas/. "
    "Do not edit by hand. -->"
)

# `check_documentation` requires this on every mapped durable document, generated views
# included, so the generator emits it rather than a later hand-edit adding it back.
FOOTER = (
    "<!-- This document follows common-doc-guidelines.md.\n"
    "See github.com/jlevy/practical-prose and review guidelines before editing.\n"
    "-->"
)

# Declared-state order, most actionable first. `tentative` is in the schema and has
# never been used; it is listed so a first use appears in the right place rather than
# being sorted to the end as an unknown.
STATE_ORDER = ("ready", "tentative", "blocked", "stopped", "complete")

# What each state means for a session picking work. The schema names the values; it
# does not say which of them a coordinator may act on, and that is the whole question
# this document exists to answer.
STATE_MEANING = {
    "ready": "may be taken now",
    "tentative": "declared but not yet committed to",
    "blocked": "waiting on a named predecessor",
    "stopped": "not run here; the agenda says why, and `discharged_by` names where it moved",
    "complete": "discharged",
}


@dataclass(frozen=True, slots=True)
class Commitment:
    """One BC cell, flattened out of its agenda for cross-agenda reporting."""

    agenda: str
    agenda_status: str
    doc: str
    id: str
    state: str
    priority: int
    purpose: str
    owner_focus: str
    question: str
    bead: str
    depends_on: tuple[str, ...]
    blocked_on: str
    discharged_by: str

    @classmethod
    def of(cls, agenda: dict, doc: str, item: dict) -> Self:
        return cls(
            agenda=agenda["id"],
            agenda_status=agenda["status"],
            doc=doc,
            id=item["id"],
            state=item["state"],
            priority=item["priority"],
            purpose=item["purpose"],
            owner_focus=item["owner_focus"],
            question=" ".join(item["question"].split()),
            bead=item["bead"],
            depends_on=tuple(item.get("depends_on", [])),
            blocked_on=" ".join(item.get("blocked_on", "").split()),
            discharged_by=item.get("discharged_by", ""),
        )

    @property
    def link(self) -> str:
        return f"[`{self.id}`](agendas/{self.doc}#)"


def frontmatter(path: pathlib.Path) -> dict:
    """The YAML frontmatter of a softschema document."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path.name}: no frontmatter")
    end = text.index("\n---", 4)
    return safe_load(text[4:end])


def load() -> list[Commitment]:
    out: list[Commitment] = []
    for path in sorted(AGENDAS.glob("agenda-*.md")):
        agenda = frontmatter(path)["agenda"]
        out += [Commitment.of(agenda, path.name, item) for item in agenda["items"]]
    return out


def state_rank(c: Commitment) -> int:
    return STATE_ORDER.index(c.state) if c.state in STATE_ORDER else len(STATE_ORDER)


def violations(commitments: list[Commitment]) -> list[str]:
    """Queue invariants the schema cannot state, because they relate fields to states.

    Both are the shapes D-374 recorded: work offered as takeable after another agenda
    finished it, and a blocked cell whose blocker nothing can observe. A schema can
    require a field but not require it *conditionally on a sibling's value*, so the
    refusal lives here, where `--check` makes it a gate failure rather than a warning.
    """
    known = {c.id for c in commitments}
    complete = {c.id for c in commitments if c.state == "complete"}
    out: list[str] = []
    for c in sorted(commitments, key=lambda c: c.id):
        if c.discharged_by and c.state in ("ready", "tentative"):
            out.append(
                f"{c.id} is {c.state} but names discharged_by: {c.discharged_by}; "
                "a commitment another one discharges is not takeable"
            )
        if c.discharged_by and c.discharged_by not in known:
            out.append(
                f"{c.id} names discharged_by: {c.discharged_by}, which is not a commitment"
            )
        if c.state == "blocked" and not c.depends_on and not c.blocked_on:
            out.append(
                f"{c.id} is blocked with no depends_on and no blocked_on; "
                "what it waits on is unobservable"
            )
        # The same defect one step later. A cell whose every predecessor has since
        # completed is blocked on nothing this file can see, so either it is takeable and
        # the state is wrong, or something else holds it and is unwritten. `BC-025` sat in
        # that state for a day: genuinely blocked -- H-047's regularizer does not exist and
        # five of its seven instances retain no pose -- with neither reason recorded, while
        # the map advertised it as takeable. Reporting it was never enough, which is
        # `D-401`. Note the asymmetry this closes: `ledger.py` already refuses a `ready`
        # cell with incomplete dependencies, so the queue was guarded against over-claiming
        # readiness and not at all against under-claiming it.
        if (
            c.state == "blocked"
            and c.depends_on
            and set(c.depends_on) <= complete
            and not c.blocked_on
        ):
            out.append(
                f"{c.id} is blocked, every predecessor is complete, and no blocked_on "
                "says why; either it is takeable and the state is wrong, or the real "
                "blocker is unwritten"
            )
        out.extend(
            f"{c.id} depends on {dep}, which is not a commitment"
            for dep in c.depends_on
            if dep not in known
        )
    return out


def plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def truncate(text: str, width: int) -> str:
    """Shorten to one table cell, on a word boundary, never mid-word."""
    if len(text) <= width:
        return text
    return text[:width].rsplit(" ", 1)[0] + "…"


def render(commitments: list[Commitment]) -> str:
    done = {c.id for c in commitments if c.state == "complete"}
    live = [c for c in commitments if c.state in ("ready", "tentative")]
    blocked = [c for c in commitments if c.state == "blocked"]
    counts = Counter(c.state for c in commitments)

    out = [BANNER, "", "# Agenda map", ""]
    out += [
        (
            f"{len(commitments)} agenda commitments across "
            f"{len({c.agenda for c in commitments})} agendas, as declared in each "
            "agenda's own frontmatter."
        ),
        "Source of truth is [`agendas/`](agendas/); this view is regenerated, never edited.",
        "",
        "An agenda's queue owns priority ordering, so this map preserves each agenda's",
        "order rather than imposing one across them.",
        "",
    ]

    out += ["## The short version", ""]
    tally = ", ".join(f"**{counts[s]}** {s}" for s in STATE_ORDER if counts[s])
    out += [f"- {tally}.", ""]

    # A blocked cell whose predecessors are all discharged and which states no other
    # blocker is takeable, and nothing says so. That is how a queue silently stalls.
    # A cell that also carries `blocked_on` is not in this set: its edge cleared but its
    # stated condition did not, and calling it takeable would be the same kind of wrong
    # claim the map exists to remove.
    unblocked = [
        c for c in blocked if c.depends_on and set(c.depends_on) <= done and not c.blocked_on
    ]
    if unblocked:
        rows = ", ".join(f"`{c.id}`" for c in unblocked)
        out += [
            (
                f"- **{plural(len(unblocked), 'blocked commitment')} "
                f"{'has' if len(unblocked) == 1 else 'have'} every "
                f"predecessor complete** and no other stated blocker, so {rows} "
                f"{'is' if len(unblocked) == 1 else 'are'} takeable now. A cell whose "
                "blocker is discharged but whose `state` still reads `blocked` is "
                "invisible to a coordinator reading the agenda."
            ),
            "",
        ]

    # Blocked on something that is not a commitment. This is a legitimate state, not a
    # defect -- an artifact that does not exist yet blocks work as surely as a
    # predecessor does. It is called out because no dependency edge will ever clear it,
    # so it needs a person to notice rather than a queue to advance.
    external = [c for c in blocked if not c.depends_on and c.blocked_on]
    if external:
        rows = ", ".join(f"`{c.id}`" for c in external)
        out += [
            (
                f"- **{plural(len(external), 'blocked commitment')} wait on something "
                f"that is not a commitment** ({rows}). No edge will clear these; each "
                "names its own condition in the table below, and someone has to decide "
                "it is met."
            ),
            "",
        ]

    out += ["## Live queue", ""]
    if live:
        out += [
            "Commitments a session may take now, in each agenda's declared order.",
            "",
            "| agenda | id | pri | focus | purpose | question | bead |",
            "| --- | --- | ---: | --- | --- | --- | --- |",
        ]
        for c in sorted(live, key=lambda c: (c.agenda, c.priority)):
            out.append(
                f"| {c.agenda} | `{c.id}` | {c.priority} | {c.owner_focus} | {c.purpose} "
                f"| {truncate(c.question, 110)} | `{c.bead}` |"
            )
    else:
        out += ["No commitment is in a takeable state.", ""]
    out += [""]

    out += ["## Blocked, and on what", ""]
    if blocked:
        out += [
            (
                "A commitment blocked by other commitments names them; one blocked by "
                "something else states it, because a blocker nobody can observe never "
                "clears."
            ),
            "",
            "| agenda | id | pri | waits on | predecessors done | what else |",
            "| --- | --- | ---: | --- | --- | --- |",
        ]
        for c in sorted(blocked, key=lambda c: (c.agenda, c.priority)):
            deps = ", ".join(f"`{d}`" for d in c.depends_on) or "—"
            clear = "yes" if c.depends_on and set(c.depends_on) <= done else "no"
            other = truncate(c.blocked_on, 120) if c.blocked_on else "—"
            out.append(f"| {c.agenda} | `{c.id}` | {c.priority} | {deps} | {clear} | {other} |")
    else:
        out += ["Nothing is blocked.", ""]
    out += [""]

    discharged = [c for c in commitments if c.discharged_by]
    out += ["## Discharged elsewhere", ""]
    if discharged:
        out += [
            (
                "A commitment whose exit another agenda's commitment satisfied. "
                "Recorded as an edge because prose could not be read: this is what the "
                "queue was getting wrong when it offered four finished commitments as "
                "takeable."
            ),
            "",
            "| id | state | discharged by | question |",
            "| --- | --- | --- | --- |",
        ]
        for c in sorted(discharged, key=lambda c: c.id):
            out.append(
                f"| `{c.id}` | {c.state} | `{c.discharged_by}` | {truncate(c.question, 100)} |"
            )
    else:
        out += ["No commitment names another as its discharge.", ""]
    out += [""]

    out += ["## By agenda", ""]
    out += [
        "| agenda | status | " + " | ".join(STATE_ORDER) + " | total |",
        "| --- | --- | " + " | ".join("---:" for _ in STATE_ORDER) + " | ---: |",
    ]
    for name in sorted({c.agenda for c in commitments}):
        rows = [c for c in commitments if c.agenda == name]
        per = Counter(c.state for c in rows)
        cells = " | ".join(str(per[s]) if per[s] else "" for s in STATE_ORDER)
        out.append(f"| {name} | {rows[0].agenda_status} | {cells} | {len(rows)} |")
    out += [""]

    out += ["## What the states mean", ""]
    out += [f"- `{s}` — {STATE_MEANING[s]}" for s in STATE_ORDER]
    out += [""]

    out += [FOOTER]

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    commitments = load()
    # Invariants first, in both modes: rendering a map of a queue that contradicts
    # itself would put the contradiction in a generated document and call it current.
    if broken := violations(commitments):
        for problem in broken:
            print(f"  {problem}", file=sys.stderr)
        return 1

    text = render(commitments)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(
                f"  {OUT.relative_to(ROOT.parent)} is stale; "
                "run `uv run --frozen python -m devtools.render_agenda_map`",
                file=sys.stderr,
            )
            return 1
        counts = Counter(c.state for c in commitments)
        agendas = len({c.agenda for c in commitments})
        print(
            f"  agenda map matches {len(commitments)} commitments across {agendas} "
            f"agendas: {counts['ready']} ready, {counts['blocked']} blocked, "
            f"{counts['complete']} complete"
        )
        return 0

    with atomic_output_file(OUT) as tmp:
        tmp.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
