"""Validate the bounded web-reading experiment and regenerate its byte-count report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from devtools.validate_schemas import check, payload_and_meta

CAMPAIGN = Path(__file__).resolve().parents[1] / "benchmarks/exact-catalogue-web"
FOOTER = """<!-- This document follows common-doc-guidelines.md.
See github.com/jlevy/practical-prose and review guidelines before editing.
-->"""


def report(root: Path = CAMPAIGN) -> str:
    hypotheses = {}
    for path in sorted((root / "hypotheses").glob("*.md")):
        if errors := check(path):
            raise ValueError(f"{path}: {errors}")
        payload, _ = payload_and_meta(path)
        if payload["id"] in hypotheses:
            raise ValueError("duplicate hypothesis id")
        hypotheses[payload["id"]] = payload
    if not hypotheses:
        raise ValueError("no registered hypothesis")
    board = (root / "ideas.md").read_text(encoding="utf-8")
    if any(identity not in board for identity in hypotheses):
        raise ValueError("hypothesis missing from idea board")
    lines = [
        "<!-- Generated by devtools.report_exact_catalogue_web; do not edit by hand. -->",
        "# Exact Catalogue Web Payload",
        "",
        "Raw file bytes for the default unselected route. These deterministic counts",
        "do not measure latency, compression or browser memory.",
        "",
        "| Experiment | Complete HTML control | Initial browser assets | Fraction | Verdict |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    rows: list[str] = []
    detail_lines: list[str] = []
    seen: set[str] = set()
    for path in sorted((root / "experiments").glob("*.md")):
        if errors := check(path):
            raise ValueError(f"{path}: {errors}")
        payload, _ = payload_and_meta(path)
        identity = payload["id"]
        if identity in seen:
            raise ValueError("duplicate experiment id")
        seen.add(identity)
        references = payload["hypotheses"]
        if any(reference not in hypotheses for reference in references):
            raise ValueError("unknown experiment hypothesis")
        measured = json.loads((root / payload["measurement"]).read_text(encoding="utf-8"))
        control, candidate = measured["control_bytes"], measured["candidate_bytes"]
        if control <= 0 or candidate <= 0 or candidate != sum(measured["assets"].values()):
            raise ValueError("invalid byte-count observation")
        limits = [hypotheses[reference]["maximum_fraction"] for reference in references]
        accepted = all(candidate <= control * limit for limit in limits)
        if measured["passes_acceptance"] is not accepted:
            raise ValueError("measurement verdict differs from registered threshold")
        fraction = candidate / control
        verdict = "accepted" if accepted else "rejected"
        rows.append(
            f"| [{identity}]({path.relative_to(root).as_posix()}) | {control:,} B | "
            f"{candidate:,} B | {fraction:.2%} | {verdict} |"
        )
        coverage = measured["coverage"]
        detail_lines.extend(
            [
                "",
                f"{identity}: {payload['judgment']}",
                "",
                (
                    f"The independent projection check restored {coverage['current']} current "
                    f"and {coverage['historical']} historical records, "
                    f"{coverage['coefficient_vectors']} coefficient vectors and "
                    f"{coverage['integer_coefficients']:,} integer strings."
                ),
                "All original metadata compares exactly; redundant polynomial text/LaTeX",
                "remain in the complete archives. Clicked record/coefficient files are omitted",
                "from the initial-route metric. Required Chromium controls and an independent",
                "Astra review cover the lazy behavior and mathematical labels.",
            ]
        )
    if not seen:
        raise ValueError("no recorded experiment")
    return "\n".join([*lines, *rows, *detail_lines, "", FOOTER, ""])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = report()
    destination = CAMPAIGN / "report.md"
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != rendered:
            raise SystemExit("exact-catalogue web report is stale")
        print("exact-catalogue web record and generated report are current")
    else:
        destination.write_text(rendered, encoding="utf-8")
        print(destination)


if __name__ == "__main__":
    main()
